Repository TYPO3-Documentation/TYPO3CMS-Reference-CoreApi, pull requests merged in 2020-12, with the labels that each got.

#1154 [FEATURE] Add indexes to Extension development section
  Documentation/ExtensionArchitecture/ComposerJson/Index.rst
  Documentation/ExtensionArchitecture/ConfigurationFiles/Index.rst
  Documentation/ExtensionArchitecture/ConfigurationOptions/Index.rst
  Documentation/ExtensionArchitecture/CreateNewDistribution/Index.rst
  Documentation/ExtensionArchitecture/CreateNewExtension/Index.rst
  Documentation/ExtensionArchitecture/CustomExtensionRepository/Index.rst
  Documentation/ExtensionArchitecture/DeclarationFile/Index.rst
  Documentation/ExtensionArchitecture/Documentation/Index.rst
  Documentation/ExtensionArchitecture/ExtendingTca/Examples/Index.rst
  Documentation/ExtensionArchitecture/ExtendingTca/Index.rst
  Documentation/ExtensionArchitecture/ExtendingTca/StoringChanges/Index.rst
  Documentation/ExtensionArchitecture/ExtendingTca/Verifying/Index.rst
  Documentation/ExtensionArchitecture/ExtensionKey/Index.rst
  Documentation/ExtensionArchitecture/ExtensionManagement/Index.rst
  Documentation/ExtensionArchitecture/FilesAndLocations/Index.rst
  Documentation/ExtensionArchitecture/Index.rst
  Documentation/ExtensionArchitecture/Introduction/Index.rst
  Documentation/ExtensionArchitecture/NamingConventions/Index.rst
  Documentation/ExtensionArchitecture/PublishExtension/Index.rst
Labels: Doing

#1215 Add conditions syntax examples
  Documentation/ApiOverview/TypoScriptSyntax/Syntax/Conditions.rst
Labels: Needs backport

#1123 Add clarifications to Soft References page
  Documentation/ApiOverview/SoftReferences/Index.rst
Labels: Doing, help wanted
