Repository TYPO3-Documentation/TYPO3CMS-Reference-CoreApi, pull requests merged in 2022-03, with the labels that each got.

#1737 Update sentence
  Documentation/ExtensionArchitecture/ConfigurationFiles/Index.rst
Labels: backport 11.5

#1739 fix format for $folder->getFile
  Documentation/ApiOverview/Fal/UsingFal/ExamplesFileFolder.rst
Labels: backport 11.5

#1741 use foo, bar instead of dependency in example code
  Documentation/ApiOverview/DependencyInjection/Index.rst
Labels: backport 11.5

#1743 remove confusing sentence
  Documentation/CodingGuidelines/CglPhp/CodingBestPractices/Singletons.rst
Labels: backport 11.5

#1751 change to: pid=###PAGEID###
  Documentation/Security/GuidelinesIntegrators/Typoscript.rst
Labels: backport 11.5

#1757 explain the prerequisites
  Documentation/ApiOverview/UpdateWizards/Creation.rst
Labels: backport 11.5

#1735 Document category mounts
  Documentation/ApiOverview/Categories/Index.rst
Labels: backport 11.5, backport 10.4

#1762 Introduce link target for Autoconfigure
  Documentation/ApiOverview/DependencyInjection/Index.rst
Labels: backport 11.5

#1769 use [] instead of php array()
  Documentation/ApiOverview/Fluid/Syntax.rst
Labels: backport 11.5

#1763 Raise attention on "cachedParametersWhiteList"
  Documentation/ApiOverview/CachingFramework/Index.rst
Labels: backport 11.5

#1770 write more small hints what Fluid is
  Documentation/ApiOverview/Fluid/Introduction.rst
Labels: backport 11.5

#1761 Remove the outdated example and suggest to use events
  Documentation/ApiOverview/Hooks/Hooks/Index.rst
Labels: backport 11.5

#1787 Fix Syntax error on page EventDispatcher (PSR-14 Events).
  Documentation/ApiOverview/Hooks/EventDispatcher/Index.rst
Labels: backport 11.5, backport 10.4

#1788 [DOCS] Fix typo in key for system maintainer list
  Documentation/Security/GuidelinesIntegrators/InstallTool.rst
Labels: backport 10.4
