Repository TYPO3-Documentation/TYPO3CMS-Reference-CoreApi, pull requests merged in 2022-01, with the labels that each got.

#1644 [TASK] Remove references to the `ignore-as-root` switch
  Documentation/Testing/ExtensionTesting.rst
Labels: backport required

#1648 Fix single quotes in code example
  Documentation/ApiOverview/PageTitleApi/Index.rst
Labels: backport required

#1655 Add a warning that imports are still resolved.
  Documentation/ApiOverview/TypoScriptSyntax/Syntax/TypoScriptSyntax.rst
Labels: backport 11.5, backport 10.4

#1660 [TASK] Deprecate composer.json typo3-ter declaration
  Documentation/ExtensionArchitecture/ComposerJson/Index.rst
Labels: backport 11.5, backport 10.4

#1662 Update instructions
  Documentation/ApiOverview/Internationalization/TranslationServer/Crowdin/ExtensionIntegration.rst
Labels: backport 11.5, backport 10.4

#1666 fix small typo
  Documentation/ApiOverview/AccessControl/Roles/Index.rst
Labels: backport 11.5, backport 10.4, backport 9.5

#1677 [FEATURE] Bugfix: #93635 - Add mail configuration for setting smtp do…
  Documentation/ApiOverview/GlobalValues/Typo3ConfVars/MAIL.rst
Labels: backport 11.5
