Repository TYPO3-Documentation/TYPO3CMS-Reference-CoreApi, pull requests merged in 2022-06, with the labels that each got.

#1849 Add path information
  Documentation/ApiOverview/Context/Index.rst
Labels: backport 11.5, backport 10.4

#1898 Add anchor
  Documentation/ApiOverview/Database/Connection/Index.rst
Labels: backport 11.5

#1897 Insert anchor
  Documentation/ApiOverview/Database/BasicCrud/Index.rst
Labels: backport 11.5

#1896 Add naming conventions for mm tables
  Documentation/ExtensionArchitecture/BestPractises/NamingConventions.rst
Labels: backport 11.5

#1912 [TASK] #93182 - Changed file extension for gzip compressed files
  Documentation/Configuration/Typo3ConfVars/BE.rst
  Documentation/Configuration/Typo3ConfVars/FE.rst
Labels: changelog

#1919 Fixed wrong extension key in text and imagecaption
  Documentation/ApiOverview/ContentElements/AddingYourOwnContentElements.rst
Labels: backport-required

#1921 Add Documentation on "How to send spooled mails"
  Documentation/ApiOverview/Mail/Index.rst
Labels: backport 11.5

#1923 Fix services.yaml code-blocks
  Documentation/ApiOverview/DependencyInjection/Index.rst
Labels: backport 11.5

#1929 [DOC] Change Resources/Public/Icons/Extension.svg minimal dimensions …
  Documentation/ExtensionArchitecture/FileStructure/Resources/Public/Index.rst
Labels: backport-required
