Repository TYPO3-Documentation/TYPO3CMS-Reference-CoreApi, pull requests merged in 2022-08, with the labels that each got.

#2024 No space before colon for return type declatarion
  Documentation/CodingGuidelines/CglPhp/PhpFileFormatting/UsingPhpdoc.rst
Labels: backport 11.5

#2029 [TASK] Explain $GLOBALS['TYPO3_CONF_VARS']['BE']['defaultPermissions']
  Documentation/Configuration/Typo3ConfVars/BE.rst
Labels: backport 11.5

#2032 [FEATURE] #84244 - Allow adding additional query restrictions
  Documentation/ApiOverview/Database/RestrictionBuilder/Index.rst
  Documentation/Configuration/Typo3ConfVars/DB.rst
Labels: backport 11.5

#2037 [BUGFIX] Use correct heading for customPermOptions
  Documentation/Configuration/Typo3ConfVars/BE.rst
Labels: backport 11.5

#2034 [TASK] Remove $GLOBALS['TYPO3_CONF_VARS']['BE']['fluidPageModule']
  Documentation/Configuration/Typo3ConfVars/BE.rst
Labels: backport 11.5

#2039 [TASK] Explain $GLOBALS['TYPO3_CONF_VARS']['BE']['defaultUC']
  Documentation/Configuration/Typo3ConfVars/BE.rst
Labels: backport 11.5

#2041 [TASK] Explain $GLOBALS['TYPO3_CONF_VARS']['BE']['HTTP']
  Documentation/Configuration/Typo3ConfVars/BE.rst
Labels: backport 11.5

#2048 [TASK] Correct spelling of TYPO3 versions
  Documentation/ApiOverview/AccessControl/MoreAboutFileMounts/Index.rst
  Documentation/ApiOverview/Autoloading/Index.rst
  Documentation/ApiOverview/BackendLayout/Index.rst
  Documentation/ApiOverview/CachingFramework/Architecture/Index.rst
  Documentation/ApiOverview/ContentElements/AddingYourOwnContentElements.rst
  Documentation/ApiOverview/Deprecation/Index.rst
  Documentation/ApiOverview/Examples/ContextualMenu/Index.rst
  Documentation/ApiOverview/Fal/UsingFal/ExamplesFileSearch.rst
  Documentation/ApiOverview/FlashMessages/Index.rst
  Documentation/ApiOverview/FormProtection/Index.rst
  Documentation/ApiOverview/Http/Index.rst
  Documentation/ApiOverview/Icon/Index.rst
  Documentation/ApiOverview/Internationalization/TranslationServer/Crowdin.rst
  Documentation/ApiOverview/LinkBrowser/LinkBrowserApi/Index.rst
  Documentation/ApiOverview/SiteHandling/Basics.rst
  Documentation/ApiOverview/SiteHandling/ErrorHandling.rst
  Documentation/ApiOverview/SiteHandling/WriteCustomErrorHandler.rst
  Documentation/ApiOverview/Workspaces/Index.rst
  Documentation/CodeSnippets/Config/EventsBackend.php
  Documentation/CodeSnippets/Config/EventsCore.php
  Documentation/CodeSnippets/Config/EventsFrontend.php
  Documentation/CodeSnippets/Config/EventsRecordlist.php
  Documentation/CodingGuidelines/CglTypoScript/Index.rst
  Documentation/Configuration/Typo3ConfVars/FE.rst
  Documentation/Configuration/Typo3ConfVars/SYS.rst
  Documentation/Configuration/TypoScriptSyntax/Syntax/Includes.rst
  Documentation/Configuration/TypoScriptSyntax/Syntax/TypoScriptSyntax.rst
  Documentation/Events/Concept/Index.rst
  Documentation/Events/EventDispatcher/Index.rst
  Documentation/Events/Hooks/Index.rst
  Documentation/ExtensionArchitecture/BestPractises/ConfigurationFiles.rst
  Documentation/ExtensionArchitecture/BestPractises/NamingConventions.rst
  Documentation/ExtensionArchitecture/Extbase/Reference/Controller/ActionController.rst
  Documentation/ExtensionArchitecture/Extbase/Reference/FrontendPlugins.rst
  Documentation/ExtensionArchitecture/Extbase/Reference/Repository.rst
  Documentation/ExtensionArchitecture/Extbase/Reference/Validation.rst
  Documentation/ExtensionArchitecture/HowTo/CreateNewExtension.rst
  Documentation/ExtensionArchitecture/HowTo/FrontendPlugin/AbstractPlugin.rst
  Documentation/Images/ManualScreenshots/Backend/BackendModulesConfiguration.rst.txt
  Documentation/Images/ManualScreenshots/Backend/GenericBackendMessage.rst.txt
  Documentation/Testing/History.rst
Labels: backport 11.5

#2057 [BUGFIX] Remove unavailable additionalClasses option in FontawesomeIconProvider
  Documentation/CodeSnippets/Manual/Extension/Configuration/IconsPhp.rst.txt
Labels: backport 10.4

#2059 Unify capitalization cache FE / BE
  Documentation/ApiOverview/CachingFramework/FrontendsBackends/Index.rst
Labels: backport 11.5, backport 10.4

#2067 [BUGFIX] Show namespaces of password hashing classes correctly
  Documentation/Configuration/Typo3ConfVars/BE.rst
  Documentation/Configuration/Typo3ConfVars/FE.rst
Labels: backport 11.5

#2058 Add information about configuring Redis cache
  Documentation/ApiOverview/CachingFramework/FrontendsBackends/Index.rst
Labels: backport 11.5, backport 10.4

#2064 Improve Persistence Chapter
  Documentation/CodeSnippets/Config/Extbase.php
  Documentation/CodeSnippets/Extbase/Annotation/Cascade.rst.txt
  Documentation/CodeSnippets/Extbase/Annotation/IgnoreValidation.rst.txt
  Documentation/CodeSnippets/Extbase/Annotation/Lazy.rst.txt
  Documentation/CodeSnippets/Extbase/Annotation/Multiple.rst.txt
  Documentation/CodeSnippets/Extbase/Annotation/Transient.rst.txt
  Documentation/CodeSnippets/Extbase/Annotation/Validate.rst.txt
  Documentation/CodeSnippets/Extbase/Controllers/BlogControllerNew.rst.txt
  Documentation/CodeSnippets/Extbase/Controllers/BlogControllerUpdate.rst.txt
  Documentation/CodeSnippets/Extbase/Domain/ModelWithAdditionalGetters.rst.txt
  Documentation/CodeSnippets/Extbase/Domain/ModelWithPublicGetters.rst.txt
  Documentation/CodeSnippets/Extbase/Domain/ModelWithPublicProperty.rst.txt
  Documentation/CodeSnippets/Extbase/Domain/Optional1on1.rst.txt
  Documentation/CodeSnippets/Extbase/Domain/Relationship1onN2.rst.txt
  Documentation/CodeSnippets/Extbase/Domain/Relationship1onNUni.rst.txt
  Documentation/CodeSnippets/Extbase/Domain/RelationshipNonM.rst.txt
  Documentation/CodeSnippets/Extbase/Persistence/ExtbasePersistenceClasses.rst.txt
  Documentation/CodeSnippets/Extbase/Persistence/TCA.rst.txt
  Documentation/CodeSnippets/Extbase/Validator/ObjectValidatorUsage.rst.txt
  Documentation/CodeSnippets/Extbase/Validator/PropertyValidatorUsage.rst.txt
  Documentation/CodeSnippets/Extbase/Validator/ValidatorWithArgumentUsage.rst.txt
  Documentation/CodeSnippets/Extbase/View/HtmlResponse.rst.txt
  Documentation/ExtensionArchitecture/Extbase/Reference/Domain/Model.rst
  Documentation/ExtensionArchitecture/Extbase/Reference/Domain/Persistence.rst
  Documentation/ExtensionArchitecture/Extbase/Reference/Index.rst
Labels: backport 11.5

#2076 [TASK] replace data-content with data-bs-content in Modals
  Documentation/ApiOverview/JavaScript/Modules/Modals.rst
Labels: backport 11.5

#2078 [TASK] Revise chapter about commands
  Documentation/ApiOverview/CommandControllers/Index.rst
Labels: backport 11.5

#2083 [TASK] Beautify chapter "Using the DataHandler in scripts"
  Documentation/ApiOverview/Typo3CoreEngine/UsingDataHandler/Index.rst
Labels: backport 11.5

#2075 Add forwarding to a different controller
  Documentation/CodeSnippets/Config/Extbase.php
  Documentation/CodeSnippets/Extbase/Controllers/ForwardAction.rst.txt
  Documentation/ExtensionArchitecture/Extbase/Reference/Controller/ActionController.rst
Labels: backport 11.5

#2085 [BUGFIX] Correct link to Fluid documentation
  Documentation/ApiOverview/Fluid/DevelopCustomViewhelper.rst
  Documentation/Settings.cfg
Labels: backport 11.5

#2090 Change default rst indentation to 4 spaces
  .editorconfig
Labels: backport 11.5, backport 10.4

#2094 [BUGFIX] around the forwarding problem
  Documentation/ExtensionArchitecture/Concepts/Extbase.rst
Labels: backport 11.5

#1991 [SECURITY] Update information about Indexes
  Documentation/Security/GuidelinesAdministrators/DirectoryIndexing.rst
Labels: backport 11.5

#2097 Add information about Extbase examples and tutorials
  Documentation/ExtensionArchitecture/Extbase/Examples/Index.rst
  Documentation/ExtensionArchitecture/Extbase/Index.rst
  Documentation/ExtensionArchitecture/Extbase/Tutorials/Index.rst
Labels: backport 11.5

#2098 Show video tutorials on how to create backend modules
  Documentation/ExtensionArchitecture/HowTo/BackendModule/Index.rst
  Documentation/ExtensionArchitecture/HowTo/BackendModule/Tutorials.rst
Labels: backport 11.5

#2101 Apply coding guidelines to the blog_example
  Documentation/CodeSnippets/Extbase/Annotation/Cascade.rst.txt
  Documentation/CodeSnippets/Extbase/Annotation/IgnoreValidation.rst.txt
  Documentation/CodeSnippets/Extbase/Annotation/Lazy.rst.txt
  Documentation/CodeSnippets/Extbase/Annotation/Multiple.rst.txt
  Documentation/CodeSnippets/Extbase/Controllers/BlogControllerNew.rst.txt
  Documentation/CodeSnippets/Extbase/Domain/Relationship1onN2.rst.txt
  Documentation/CodeSnippets/Extbase/Domain/Relationship1onNUni.rst.txt
  Documentation/CodeSnippets/Extbase/Persistence/ExtbasePersistenceClasses.rst.txt
  Documentation/CodeSnippets/Extbase/Persistence/TCA.rst.txt
  Documentation/CodeSnippets/Extbase/View/HtmlResponse.rst.txt
Labels: backport 11.5

#2105 [TASK] Remove setDescription in command example
  Documentation/ApiOverview/CommandControllers/Index.rst
Labels: backport 11.5

#2111 [BUGFIX] Correct caption of code snippet in TypoScript Configuration
  Documentation/ExtensionArchitecture/Extbase/Reference/TypoScriptConfiguration.rst
Labels: backport 11.5

#2110 Add a chapter on how Localization and Translation can be handled in TypoScript
  Documentation/ExtensionArchitecture/HowTo/Localization/TypoScript.rst
Labels: backport 11.5

#2099 Create a tutorial for a minimal extension
  Documentation/ExtensionArchitecture/Index.rst
  Documentation/ExtensionArchitecture/Tutorials/Index.rst
  Documentation/ExtensionArchitecture/Tutorials/MinimalExtension.rst
  Documentation/Includes.rst.txt
Labels: backport 11.5

#2074 Move Property Mapper from Extbase Fluid Book
  Documentation/CodeSnippets/Config/Extbase.php
  Documentation/CodeSnippets/Extbase/PropertyManager/IntegerMapping.rst.txt
  Documentation/CodeSnippets/Extbase/PropertyManager/ObjectMapping.rst.txt
  Documentation/CodeSnippets/Extbase/PropertyManager/PropertyMapperInjection.rst.txt
  Documentation/ExtensionArchitecture/Extbase/Reference/Controller/PropertyMapping.rst
Labels: backport 11.5

#2052 Point out possible problems with redis cache backend
  Documentation/ApiOverview/CachingFramework/FrontendsBackends/Index.rst
Labels: backport 11.5, backport 10.4

#2117 Extbase Typo3QuerySettings and Localization
  Documentation/ExtensionArchitecture/Extbase/Reference/Domain/Repository.rst
Labels: backport 11.5

#2120 [TASK] Rename "Symfony console commands" chapter to "Console commands"
  Documentation/ApiOverview/CommandControllers/Index.rst
  Documentation/Index.rst
Labels: backport 11.5

#2112 [TASK] Revise HTTP section
  Documentation/ApiOverview/Http/Index.rst
Labels: backport 11.5

#2123 Restructure the menu of TYPO3 Explained
  Documentation/ApiOverview/Index.rst
  Documentation/ExtensionArchitecture/Index.rst
  Documentation/Index.rst
Labels: backport 11.5, backport 10.4

#2128 Adjust language files part in Extension File Structure
  Documentation/ExtensionArchitecture/FileStructure/Resources/Private/Language.rst
Labels: backport 11.5

#2122 Identifiers in localized models
  Documentation/ExtensionArchitecture/Extbase/Reference/Domain/Model.rst
Labels: backport 11.5

#2119 [TASK] Revise section "Managing translations for backend"
  Documentation/ApiOverview/Internationalization/ManagingTranslations.rst
  Documentation/Images/ExternalImages/System/InternationalizationXliffWithVirtaal.png
  Documentation/Images/ExternalImages/System/t3ll.png
Labels: backport 11.5

#2139 [BUGFIX] Add configuration back to toctree
  Documentation/ExtensionArchitecture/HowTo/Index.rst
Labels: backport 11.5

#2137 Remove orphaned pages
  Documentation/ApiOverview/Examples/ContentElementWizard/Index.rst
  Documentation/ApiOverview/SiteHandling/ErrorHandling.rst
  Documentation/ExtensionArchitecture/Concepts/Extbase.rst
Labels: backport 11.5

#2138 Move chapters to logic positions
  Documentation/ApiOverview/Backend/BackendLayout.rst
  Documentation/ApiOverview/Backend/BackendRouting.rst
  Documentation/ApiOverview/Backend/BackendUserObject.rst
  Documentation/ApiOverview/Backend/Clipboard.rst
  Documentation/ApiOverview/Backend/ContextualMenu.rst
  Documentation/ApiOverview/Backend/CustomPermissions.rst
  Documentation/ApiOverview/Backend/EditLinks.rst
  Documentation/ApiOverview/Backend/Index.rst
  Documentation/ApiOverview/Examples/Index.rst
  Documentation/ApiOverview/Seo/CanonicalApi.rst
  Documentation/ApiOverview/Seo/Index.rst
  Documentation/ApiOverview/Seo/MetaTagApi.rst
  Documentation/ApiOverview/Seo/PageTitleApi.rst
  Documentation/ApiOverview/Seo/XmlSitemap.rst
  Documentation/CodeSnippets/Extbase/Annotation/IgnoreValidation.rst.txt
  Documentation/CodeSnippets/Extbase/Controllers/BlogControllerNew.rst.txt
  Documentation/CodeSnippets/Extbase/Controllers/ForwardAction.rst.txt
  Documentation/CodeSnippets/Extbase/PropertyManager/IntegerMapping.rst.txt
  Documentation/CodeSnippets/Extbase/PropertyManager/ObjectMapping.rst.txt
  Documentation/CodeSnippets/Extbase/View/HtmlResponse.rst.txt
  Documentation/ParsingHtml/Index.rst
Labels: backport 11.5

#2136 Tea in a nutshell part 1: Extension configuration, installation and directory structure
  Documentation/CodeSnippets/Config/Tutorials/Tea.php
  Documentation/CodeSnippets/Tutorials/Tea/ComposerJsonSimplified.rst.txt
  Documentation/CodeSnippets/Tutorials/Tea/ExtEmconf.rst.txt
  Documentation/CodeSnippets/codesnippets.php
  Documentation/ExtensionArchitecture/FileStructure/Documentation/Index.rst
  Documentation/ExtensionArchitecture/Index.rst
  Documentation/ExtensionArchitecture/Tutorials/Index.rst
  Documentation/ExtensionArchitecture/Tutorials/Tea/DirectoryStructure.rst
  Documentation/ExtensionArchitecture/Tutorials/Tea/ExtensionConfiguration.rst
  Documentation/ExtensionArchitecture/Tutorials/Tea/Index.rst
  Documentation/Settings.cfg
Labels: backport 11.5

#2134 Restructure TYPO3_CONF_VARS
  Documentation/Configuration/Typo3ConfVars/BE.rst
  Documentation/Configuration/Typo3ConfVars/DB.rst
  Documentation/Configuration/Typo3ConfVars/EXT.rst
  Documentation/Configuration/Typo3ConfVars/FE.rst
  Documentation/Configuration/Typo3ConfVars/GFX.rst
  Documentation/Configuration/Typo3ConfVars/HTTP.rst
  Documentation/Configuration/Typo3ConfVars/Index.rst
  Documentation/Configuration/Typo3ConfVars/MAIL.rst
  Documentation/Configuration/Typo3ConfVars/SYS.rst
Labels: backport 11.5

#2145 [BUGFIX] Correct formatting of cards in tutorials section
  Documentation/ExtensionArchitecture/Tutorials/Index.rst
Labels: backport 11.5

#2144 [BUGFIX] Resolve rendering warnings
  Documentation/ApiOverview/ContentElements/CreatePlugins.rst
  Documentation/ApiOverview/ContentElements/Index.rst
  Documentation/ApiOverview/ContentElements/Introduction.rst
  Documentation/ApiOverview/DataFormats/Index.rst
  Documentation/ApiOverview/Fluid/Syntax.rst
  Documentation/ApiOverview/GlobalValues/Index.rst
  Documentation/ApiOverview/ParsingHtml/Index.rst
  Documentation/ExtensionArchitecture/BestPractises/NamingConventions.rst
  Documentation/ExtensionArchitecture/Tutorials/MinimalExtension.rst
  Documentation/ExtensionArchitecture/Tutorials/Tea/DirectoryStructure.rst
  Documentation/Security/GuidelinesAdministrators/DirectoryIndexing.rst
Labels: backport 11.5
