Repository TYPO3-Documentation/TYPO3CMS-Reference-CoreApi, pull requests merged in 2022-02, with the labels that each got.

#1681 Improve search result for AdditionalConfiguration
  Documentation/ApiOverview/GlobalValues/Typo3ConfVars/Index.rst
Labels: backport 11.5, backport 10.4

#1680 [FEATURE] Reference the SEO manual
  Documentation/ApiOverview/CanonicalApi/Index.rst
  Documentation/ApiOverview/Seo/Index.rst
  Documentation/ApiOverview/XmlSitemap/Index.rst
  Documentation/Settings.cfg
Labels: backport 11.5, backport 10.4

#1682 Use Environment API in the example
  Documentation/ApiOverview/GlobalValues/Typo3ConfVars/Index.rst
Labels: backport 11.5

#1687 [TASK] Use ResponseInterface instead of concrete implementation
  Documentation/ApiOverview/Ajax/Backend/Index.rst
Labels: backport 11.5, backport 10.4

#1690 Document the option to set multiple locales
  Documentation/ApiOverview/SiteHandling/AddLanguages.rst
Labels: backport 11.5

#1692 Add Quick start section on dispatching events
  Documentation/ApiOverview/Hooks/EventDispatcher/Index.rst
Labels: backport 11.5, backport 10.4

#1695 #94312 - Removed BE/loginSecurityLevel and FE/loginSecurityLevel
  Documentation/ApiOverview/Authentication/Index.rst
Labels: backport 11.5

#1678 [BUGFIX] Do not set default TSconfig directly in TYPO3_CONF_VARS
  Documentation/ApiOverview/GlobalValues/Typo3ConfVars/BE.rst
Labels: backport 11.5

#1698 [TASK] Remove outdated table syntax
  Documentation/ApiOverview/Rte/Transformations/Overview.rst
  Documentation/ApiOverview/TypoScriptSyntax/TypoScriptParserApi/CustomTypoScript.rst
Labels: backport 11.5, backport 10.4, backport 9.5, backport 8.7, backport 7.6

#1697 Fix Link Syntax
  Documentation/ExtensionArchitecture/ConfigurationFiles/Index.rst
Labels: backport 11.5, backport 10.4

#1706 Update Index.rst
  Documentation/ApiOverview/XmlSitemap/Index.rst
Labels: backport 11.5

#1702 [TASK] Remove old wiki links
  Documentation/ApiOverview/CachingFramework/Index.rst
  Documentation/ApiOverview/Internationalization/TranslationServer/Pootle.rst
  Documentation/Settings.cfg
  Documentation/Testing/History.rst
Labels: backport 11.5, backport 10.4, backport 9.5, backport 8.7, backport 7.6

#1709 wrong Sphinx
  Documentation/ApiOverview/BackendLayout/Index.rst
Labels: backport 11.5

#1714 list all logger methods with explanation
  Documentation/ApiOverview/Logging/Logger/Index.rst
Labels: backport 11.5

#1712 Update CustomBackendPreview.rst
  Documentation/ApiOverview/ContentElements/CustomBackendPreview.rst
Labels: backport 11.5

#1719 [DOCS] Add missing AfterFileMetaDataUpdatedEvent documentation
  Documentation/ApiOverview/Hooks/Events/Core/Resource/AfterFileMetaDataUpdatedEvent.rst
  Documentation/CodeSnippets/Events/Core/Resource/AfterFileMetaDataUpdatedEvent.rst.txt
Labels: backport 11.5, backport 10.4

#1722 Mention use statements for classes in the snippet
  Documentation/ApiOverview/CommandControllers/Index.rst
Labels: backport 11.5

#1724 Change table to defination list
  Documentation/ApiOverview/CachingFramework/Index.rst
Labels: backport 11.5

#1725 Example should go to AdditionalConfiguration.php
  Documentation/ApiOverview/CachingFramework/Index.rst
Labels: backport 11.5

#1729 Add notice about special handling of BCC recipients in sendmail
  Documentation/ApiOverview/Mail/Index.rst
Labels: backport 11.5

#1731 give more details about the allowed labels and values
  Documentation/ExtensionArchitecture/ConfigurationOptions/Index.rst
Labels: backport 11.5
