Repository TYPO3-Documentation/TYPO3CMS-Reference-CoreApi, pull requests merged in 2022-07, with the labels that each got.

#1938 [TASK] Add TYPO3_CONF_VARS defaultScheme
  Documentation/Configuration/Typo3ConfVars/SYS.rst
Labels: backport 11.5

#1947 [TASK] Add ViewHelpers to Fluid syntax
  Documentation/ApiOverview/Fluid/Syntax.rst
Labels: backport 11.5

#1953 Move page "Create custom ViewHelper" from Extbase book
  Documentation/ApiOverview/Fluid/DevelopCustomViewhelper.rst
  Documentation/ApiOverview/Fluid/Index.rst
Labels: backport 11.5

#1955 [TASK] Update references due to Fluid migration
  Documentation/ApiOverview/Fluid/Introduction.rst
Labels: backport 11.5

#1957 [TASK] Remove outdated note for Fluid
  Documentation/ApiOverview/Fluid/Index.rst
Labels: backport 11.5

#1958 Migrate Fluid page "Using TypoScript for rendering: The cObject ViewHelper" from Extbase book
  Documentation/ApiOverview/Fluid/Index.rst
  Documentation/ApiOverview/Fluid/UsingTypoScriptCObjectViewHelper.rst
Labels: backport 11.5

#1963 [TASK] Migrate Fluid comments from Extbase book
  Documentation/ApiOverview/Fluid/Syntax.rst
Labels: backport 11.5

#1962 Replace term object "object accessors"
  Documentation/ApiOverview/Fluid/Introduction.rst
Labels: backport 11.5

#1967 [TASK] Create page "Using Fluid in TYPO3"
  Documentation/ApiOverview/Fluid/Index.rst
  Documentation/ApiOverview/Fluid/UsingFluidInTypo3.rst
Labels: backport 11.5

#1969 [TASK] Add boolean conditions to Fluid syntax
  Documentation/ApiOverview/Fluid/Syntax.rst
Labels: backport 11.5

#1971 [TASK] Fix formatting
  Documentation/ApiOverview/Fluid/Syntax.rst
Labels: backport 11.5

#1974 [TASK] Remove additional Fluid links
  Documentation/ApiOverview/Fluid/Introduction.rst
Labels: backport 11.5

#1980 Move Extbase Reference from Extbase-Fluid Book
  Documentation/CodeSnippets/Config/Extbase.php
  Documentation/CodeSnippets/Extbase/Api/ValidatorInterface.rst.txt
  Documentation/CodeSnippets/Extbase/FrontendPlugins/ConfigurePlugin.rst.txt
  Documentation/CodeSnippets/Extbase/FrontendPlugins/ConfigureRssPlugin.rst.txt
  Documentation/CodeSnippets/Extbase/FrontendPlugins/NewContentElementWizard.rst.txt
  Documentation/CodeSnippets/Extbase/FrontendPlugins/RegisterPlugin.rst.txt
  Documentation/CodeSnippets/Extbase/FrontendPlugins/TypoScriptPluginRss.rst.txt
  Documentation/CodeSnippets/codesnippets.php
  Documentation/ExtensionArchitecture/Concepts/Extbase/Index.rst
  Documentation/ExtensionArchitecture/Concepts/Extbase/Reference/Caching.rst
  Documentation/ExtensionArchitecture/Concepts/Extbase/Reference/ClassHierarchy.rst
  Documentation/ExtensionArchitecture/Concepts/Extbase/Reference/DomainModel.rst
  Documentation/ExtensionArchitecture/Concepts/Extbase/Reference/FrontendPlugins.rst
  Documentation/ExtensionArchitecture/Concepts/Extbase/Reference/Index.rst
  Documentation/ExtensionArchitecture/Concepts/Extbase/Reference/Localization.rst
  Documentation/ExtensionArchitecture/Concepts/Extbase/Reference/Repository.rst
  Documentation/ExtensionArchitecture/Concepts/Extbase/Reference/TypoScriptConfiguration.rst
  Documentation/ExtensionArchitecture/Concepts/Extbase/Reference/Validation.rst
  Documentation/ExtensionArchitecture/Concepts/Index.rst
  Documentation/Images/ManualScreenshots/Extbase/ListType.png
  Documentation/Images/ManualScreenshots/Extbase/NewPlugin.png
Labels: backport 11.5

#1985 fix typos in History.rst
  Documentation/Testing/History.rst
Labels: backport 11.5, backport 10.4

#1976 [TASK] Add labels in Fluid introduction
  Documentation/ApiOverview/Fluid/Introduction.rst
Labels: backport 11.5

#1978 [TASK] Expand section about partials
  Documentation/ApiOverview/Fluid/Introduction.rst
Labels: backport 11.5

#1996 [BUGFIX] remove pagination widget from EXT:news routing example
  Documentation/ApiOverview/Routing/Examples.rst
Labels: backport 11.5

#2002 Fix position of returntype-hint
  Documentation/ApiOverview/ContentElements/CustomDataProcessing.rst
Labels: backport 11.5

#2004 [TASK] Revise system categories
  Documentation/ApiOverview/Categories/Index.rst
Labels: backport 11.5

#2010 Update 'Directory structure' with '_assets'
  Documentation/ApiOverview/DirectoryStructure/Index.rst
Labels: backport 11.5

#2016 [BUGFIX] Correct heading of authentication events list
  Documentation/Events/Events/Core/Authentication/Index.rst
Labels: backport 11.5

#2015 [TASK] Remove superfluous toctree captions
  Documentation/Events/Events/Backend/Index.rst
  Documentation/Events/Events/Core/Index.rst
  Documentation/Events/Events/Extbase/Index.rst
  Documentation/Events/Events/ExtensionManager/Index.rst
  Documentation/Events/Events/Index.rst
  Documentation/Events/Events/Info/Index.rst
  Documentation/Events/Events/Linkvalidator/Index.rst
  Documentation/Events/Events/Recordlist/Index.rst
  Documentation/Events/Events/Setup/Index.rst
Labels: backport 11.5, backport 10.4

#2011 Add information about shutdown of SOAP interface
  Documentation/ExtensionArchitecture/HowTo/PublishExtension/PublishToTER/Index.rst
Labels: backport 11.5, backport 10.4

#2008 [TASK] Add missing PSR-14 events for EXT:felogin
  Documentation/CodeSnippets/Config/EventsFrontendLogin.php
  Documentation/CodeSnippets/Events/FrontendLogin/BeforeRedirectEvent.rst.txt
  Documentation/CodeSnippets/Events/FrontendLogin/LoginErrorOccurredEvent.rst.txt
  Documentation/CodeSnippets/Events/FrontendLogin/LogoutConfirmedEvent.rst.txt
  Documentation/CodeSnippets/Events/FrontendLogin/PasswordChangeEvent.rst.txt
  Documentation/Events/Events/FrontendLogin/BeforeRedirectEvent.rst
  Documentation/Events/Events/FrontendLogin/LoginConfirmedEvent.rst
  Documentation/Events/Events/FrontendLogin/LoginErrorOccurredEvent.rst
  Documentation/Events/Events/FrontendLogin/LogoutConfirmedEvent.rst
  Documentation/Events/Events/FrontendLogin/ModifyLoginFormViewEvent.rst
  Documentation/Events/Events/FrontendLogin/PasswordChangeEvent.rst
  Documentation/Events/Events/FrontendLogin/SendRecoveryEmailEvent.rst
Labels: backport 11.5

#2019 [TASK] Remove superfluous toctree captions (#2015)
  Documentation/Events/Events/Backend/Index.rst
  Documentation/Events/Events/Core/Index.rst
  Documentation/Events/Events/Extbase/Index.rst
  Documentation/Events/Events/ExtensionManager/Index.rst
  Documentation/Events/Events/Index.rst
  Documentation/Events/Events/Linkvalidator/Index.rst
  Documentation/Events/Events/Recordlist/Index.rst
  Documentation/Events/Events/Setup/Index.rst
Labels: backport 10.4
