Repository TYPO3-Documentation/TYPO3CMS-Reference-CoreApi, pull requests merged in 2023-01, with the labels that each got.

#2578 [TASK] Add reference to TsRef
  Documentation/ApiOverview/Seo/MetaTagApi.rst
Labels: backport 11.5

#2579 [TASK] Improve sitemap.xml routing
  Documentation/ApiOverview/Seo/XmlSitemap.rst
Labels: backport 11.5

#2583 Update Index.rst
  Documentation/ExtensionArchitecture/FileStructure/Configuration/Index.rst
Labels: backport 11.5

#2585 [TASK] Use dependency injection for example in broadcast channels
  Documentation/ApiOverview/Backend/BroadcastChannels.rst
  Documentation/ApiOverview/Backend/_BroadcastChannels/_BackendControllerHook.php
  Documentation/ApiOverview/Backend/_BroadcastChannels/_my-broadcast-service.js
  Documentation/ApiOverview/Backend/_BroadcastChannels/_my-event-handler.js
Labels: backport 11.5

#2586 [TASK] Remove warning about non-existing document
  Documentation/ApiOverview/Database/Index.rst
Labels: backport 11.5

#2582 [TASK] Use "MyVendor" instead of "Vendor" in PHP namespaces
  Documentation/ApiOverview/Backend/Ajax.rst
  Documentation/ApiOverview/Backend/LoginProvider.rst
  Documentation/ApiOverview/DependencyInjection/Index.rst
  Documentation/ApiOverview/Events/Hooks/Index.rst
  Documentation/ApiOverview/FileProcessing/Index.rst
  Documentation/ApiOverview/FlashMessages/Render.rst
  Documentation/ApiOverview/FlexForms/Index.rst
  Documentation/ApiOverview/Namespaces/Index.rst
  Documentation/ApiOverview/RequestLifeCycle/Middlewares.rst
  Documentation/ApiOverview/Rte/InTheBackend/PlugRte.rst
  Documentation/ApiOverview/SiteHandling/_basics-config.yaml
  Documentation/ApiOverview/SoftReferences/Index.rst
  Documentation/ApiOverview/SymfonyExpressionLanguage/Index.rst
  Documentation/ApiOverview/Xclasses/Index.rst
Labels: backport 11.5

#2584 [TASK] Add example for "groupBy" as replacement for "distinct"
  Documentation/ApiOverview/Database/QueryBuilder/Index.rst
Labels: backport 11.5

#2594 [TASK] Correct spelling of page TSconfig and user TSconfig
  Documentation/ApiOverview/FormEngine/DataCompiling/Index.rst
  Documentation/ApiOverview/LinkHandling/Linkhandler/Index.rst
  Documentation/ExtensionArchitecture/FileStructure/ExtLocalconf.rst
Labels: backport 11.5

#2607 [TASK] Streamline icon API chapter
  Documentation/ApiOverview/Icon/Index.rst
  Documentation/ApiOverview/Icon/_IconFactoryExample.php
Labels: backport 11.5

#2606 [TASK] Streamline backend routing chapter
  Documentation/ApiOverview/Backend/BackendRouting.rst
  Documentation/ApiOverview/Backend/_BackendRouting/_UriBuilderExample.php
Labels: backport 11.5

#2601 [TASK] Fix indentation of code blocks
  Documentation/ApiOverview/Backend/LoginProvider.rst
Labels: backport 11.5

#2615 [TASK] Streamline upgrade wizards section
  Documentation/ExtensionArchitecture/HowTo/UpdateExtensions/UpdateWizards/Concept.rst
  Documentation/ExtensionArchitecture/HowTo/UpdateExtensions/UpdateWizards/Creation.rst
  Documentation/ExtensionArchitecture/HowTo/UpdateExtensions/UpdateWizards/Index.rst
  Documentation/ExtensionArchitecture/HowTo/UpdateExtensions/UpdateWizards/_ExampleUpgradeWizard.php
Labels: backport 11.5

#2626 [TASK] Refine documentation about file storages
  Documentation/ApiOverview/Fal/Administration/Storages.rst
Labels: backport 11.5, backport 10.4

#2631 Update RecordLinkHandler.rst
  Documentation/ApiOverview/LinkHandling/Linkhandler/RecordLinkHandler.rst
Labels: backport-required

#2630 [TASK] Add missing TYPO3_CONF_VARS|SYS|linkHandler configuration
  Documentation/Configuration/Typo3ConfVars/SYS.rst
Labels: backport 11.5

#2623 [FEATURE] Add Extbase URI builder chapter
  Documentation/CodeSnippets/Config/ExtensionDevelopment/Extbase.php
  Documentation/CodeSnippets/Extbase/UriBuilder.rst.txt
  Documentation/ExtensionArchitecture/Extbase/Reference/Index.rst
  Documentation/ExtensionArchitecture/Extbase/Reference/UriBuilder.rst
  Documentation/ExtensionArchitecture/Extbase/Reference/_UriBuilder/_MyClass.php
  Documentation/ExtensionArchitecture/Extbase/Reference/_UriBuilder/_MyController.php
Labels: backport 11.5

#2638 [TASK] Add note about using Microsoft/Outlook 365 to send emails
  Documentation/ApiOverview/Mail/Index.rst
Labels: backport 11.5

#2640 [TASK] Streamline configuration module chapter
  Documentation/Configuration/ConfigurationModule/Index.rst
  Documentation/Configuration/ConfigurationModule/_MyProvider.php
Labels: backport 11.5
