Repository TYPO3-Documentation/TYPO3CMS-Reference-CoreApi, pull requests merged in 2023-09, with the labels that each got.

#3397 small changes
  Documentation/ApiOverview/ContentElements/CustomDataProcessing.rst
Labels: backport 12.4

#3400 [BUGFIX] Add hints what Extbase ForwardResponse needs to work properly
  Documentation/CodeSnippets/Extbase/Controllers/ForwardAction.rst.txt
  Documentation/ExtensionArchitecture/Extbase/Reference/Controller/ActionController.rst
Labels: backport 12.4

#3402 [TASK] Remove DataHandler->checkStoredRecord()
  Documentation/Configuration/Typo3ConfVars/BE.rst
Labels: changelog

#3405 [CI] Streamline GitHub workflow configuration for tests
  .github/workflows/tests.yml
Labels: backport 12.4

#3407 [FEATURE] Add UriBuilder->buildUriFromRequest()
  Documentation/ApiOverview/Backend/BackendRouting.rst
  Documentation/ApiOverview/Backend/_BackendRouting/_UriBuilderExample.php
Labels: changelog

#3404 [TASK] Add link to blog article in the message bus chapter
  Documentation/ApiOverview/MessageBus/Index.rst
Labels: backport 12.4

#3406 [TASK] Remove deprecated code in SiteLanguage
  Documentation/ApiOverview/SiteHandling/AddLanguages.rst
Labels: changelog

#3410 [BUGFIX] Fix example in MM naming convention
  Documentation/ExtensionArchitecture/BestPractises/NamingConventions.rst
Labels: backport 11.5, backport 12.4

#3414 [TASK] Remove mentions of the Pootle translation server
  Documentation/ApiOverview/Localization/TranslationServer/Crowdin.rst
  Documentation/ApiOverview/Localization/TranslationServer/Crowdin/Faq.rst
  Documentation/ApiOverview/Localization/TranslationServer/Index.rst
  Documentation/ApiOverview/Localization/TranslationServer/Pootle.rst
Labels: content outdated, backport 11.5, backport 12.4

#3417 [TASK] Remove page about Pootle translation server
  Documentation/ApiOverview/Localization/TranslationServer/Pootle.rst
Labels: content outdated

#3418 [TASK] Revise translation server introduction chapter
  Documentation/ApiOverview/Localization/TranslationServer/Index.rst
Labels: content, backport 11.5, backport 12.4

#3420 [TASK] Revise Crowdin extension integration chapter
  Documentation/ApiOverview/Localization/TranslationServer/Crowdin/ExtensionIntegration.rst
  Documentation/Images/ExternalImages/Crowdin/IntegrationBranchConfiguration.png
  Documentation/Images/ExternalImages/Crowdin/IntegrationBranches.png
  Documentation/Images/ExternalImages/Crowdin/IntegrationConfigurationFile.png
  Documentation/Images/ExternalImages/Crowdin/IntegrationOverview.png
  Documentation/Images/ExternalImages/Crowdin/IntegrationPushTranslations.png
  Documentation/Images/ExternalImages/Crowdin/IntegrationResult.png
  Documentation/Images/ExternalImages/Crowdin/IntegrationSetup.png
Labels: content, content outdated, backport 11.5, backport 12.4

#3419 [TASK] Revise Crowdin introduction chapter
  Documentation/ApiOverview/Localization/TranslationServer/Crowdin.rst
Labels: content, backport 11.5, backport 12.4

#3424 [TASK] Revise Crowdin FAQ page
  Documentation/ApiOverview/Localization/TranslationServer/Crowdin/Faq.rst
Labels: content, backport 11.5, backport 12.4

#3427 Fix formatting (#3426)
  Documentation/ApiOverview/Autoloading/Background.rst
Labels: backport 12.4

#3433 [TASK] Revise "Online translation with Crowdin" chapter
  Documentation/ApiOverview/Localization/TranslationServer/Crowdin/OnlineTranslation.rst
  Documentation/Settings.cfg
Labels: content, backport 11.5, backport 12.4

#3434 [TASK] Revise Crowdin workflow chapter
  Documentation/ApiOverview/Localization/TranslationServer/Crowdin/Workflow.rst
Labels: content, backport 11.5, backport 12.4

#3440 [TASK] Regenerate code snippets
  Documentation/ApiOverview/LinkHandling/Tutorials/_CustomLinkBrowser/_GitHubLinkHandlerInitialize.rst.txt
  Documentation/CodeSnippets/Events/Linkvalidator/BeforeRecordIsAnalyzedEvent/ExampleInject.rst.txt
  Documentation/CodeSnippets/Examples/Http/MeowInformationRequester.rst.txt
  Documentation/ExtensionArchitecture/HowTo/Localization/_php/_LanguageServiceFactoryDI.rst.txt
Labels: backport 12.4

#3443 [TASK] Revise "Custom translation servers" chapter
  Documentation/ApiOverview/Events/Events/Install/ModifyLanguagePackRemoteBaseUrlEvent.rst
  Documentation/ApiOverview/Events/Events/Install/_ModifyLanguagePackRemoteBaseUrlEvent/_CustomMirror.php
  Documentation/ApiOverview/Events/Events/Install/_ModifyLanguagePackRemoteBaseUrlEvent/_Services.yaml
  Documentation/ApiOverview/Localization/TranslationServer/Custom.rst
Labels: content, backport 11.5, backport 12.4

#3445 [Fix] field 'table_local' dosn't exist in 'sys_file_reference'
  Documentation/ApiOverview/Fal/UsingFal/ExamplesFileFolder.rst
Labels: changelog, backport 12.4

#3449 [TASK] Use PHP attribute to register ModifyLanguagePackRemoteBaseUrlEvent
  Documentation/ApiOverview/Events/Events/Install/ModifyLanguagePackRemoteBaseUrlEvent.rst
  Documentation/ApiOverview/Events/Events/Install/_ModifyLanguagePackRemoteBaseUrlEvent/_CustomMirror.php
  Documentation/ApiOverview/Events/Events/Install/_ModifyLanguagePackRemoteBaseUrlEvent/_Services.yaml
  Documentation/ApiOverview/Localization/TranslationServer/Custom.rst
Labels: changelog

#3456 [BUGFIX] Add missing semicolons
  Documentation/ApiOverview/SessionStorageFramework/UserSessionManagement.rst
  Documentation/ApiOverview/SessionStorageFramework/_UserSessionManager.rst.txt
Labels: backport 11.5, backport 12.4

#3451 Update RestrictAccessToFiles.rst (#3450)
  Documentation/Security/GuidelinesAdministrators/RestrictAccessToFiles.rst
Labels: backport 12.4

#3455 [TASK] #101941 - Various GFX-related legacy options removed
  Documentation/Configuration/Typo3ConfVars/GFX.rst
Labels: changelog

#3454 [TASK] Deprecate $GLOBALS['TYPO3_CONF_VARS']['BE']['defaultPageTSconfig']
  Documentation/Configuration/Typo3ConfVars/BE.rst
Labels: changelog

#3464 [TASK] Add note for AfterUserLoggedInEvent
  Documentation/ApiOverview/Events/Events/Core/Authentication/AfterUserLoggedInEvent.rst
Labels: changelog

#3463 [FEATURE] #101933 - Dispatch AfterUserLoggedInEvent for frontend user login
  Documentation/ApiOverview/Events/Events/Core/Authentication/AfterUserLoggedInEvent.rst
Labels: changelog

#3461 [TASK] Add note to CSP's policy builder approach
  Documentation/ApiOverview/ContentSecurityPolicy/Index.rst
Labels: backport 12.4

#3460 [TASK] Add Extbase card on extension architecture chapter
  Documentation/ExtensionArchitecture/Index.rst
Labels: backport 11.5, backport 12.4

#3458 [TASK] #101950 - Removed legacy setting 'GFX/processor_allowTemporaryMasksAsPng'
  Documentation/Configuration/Typo3ConfVars/GFX.rst
Labels: changelog

#3459 [TASK] Add more links to cache architecture chapter
  Documentation/ApiOverview/CachingFramework/Architecture/Index.rst
Labels: backport 12.4

#3470 [TASK] #102009 - Remove cache_imagesizes
  Documentation/ApiOverview/CachingFramework/Architecture/Index.rst
Labels: changelog

#3471 [TASK] Revise "Ajax in the backend" chapter
  Documentation/ApiOverview/Backend/Ajax.rst
  Documentation/ApiOverview/Backend/_Ajax/_AjaxRoutes.php
  Documentation/ApiOverview/Backend/_Ajax/_Calculate.js
  Documentation/ApiOverview/Backend/_Ajax/_ExampleController1.php
  Documentation/ApiOverview/Backend/_Ajax/_ExampleController2.php
  Documentation/ApiOverview/Backend/_Ajax/_ExampleController3.php
Labels: content, backport 12.4

#3472 [TASK] Extract JavaScript snippets from "Ajax, client-side" chapter
  Documentation/ApiOverview/Backend/AjaxClientSide.rst
  Documentation/ApiOverview/Backend/_Ajax/_MyRequest1.js
  Documentation/ApiOverview/Backend/_Ajax/_MyRequest2.js
  Documentation/ApiOverview/Backend/_Ajax/_MyRequestPromise1.js
  Documentation/ApiOverview/Backend/_Ajax/_MyRequestPromise2.js
  Documentation/ApiOverview/Backend/_Ajax/_MyRequestPromise3.js
Labels: content

#3481 Add hint to constants when accessing site settings
  Documentation/ApiOverview/SiteHandling/SiteSettings.rst
Labels: backport 12.4

#3480 [DOCS] Add example for IsContentUsedOnPageLayoutEvent PSR-14 event
  Documentation/ApiOverview/Events/Events/Backend/IsContentUsedOnPageLayoutEvent.rst
  Documentation/ApiOverview/Events/Events/Backend/_IsContentUsedOnPageLayoutEvent/_ContentUsedOnPage.php
  Documentation/ApiOverview/Events/Events/Backend/_IsContentUsedOnPageLayoutEvent/_Services.yaml
Labels: backport 12.4

#3479 [BUGFIX] Correct mentioned hooks for FlexForm events
  Documentation/ApiOverview/Events/Events/Core/Configuration/AfterFlexFormDataStructureIdentifierInitializedEvent.rst
  Documentation/ApiOverview/Events/Events/Core/Configuration/AfterFlexFormDataStructureParsedEvent.rst
  Documentation/ApiOverview/Events/Events/Core/Configuration/BeforeFlexFormDataStructureIdentifierInitializedEvent.rst
  Documentation/ApiOverview/Events/Events/Core/Configuration/BeforeFlexFormDataStructureParsedEvent.rst
Labels: bug, backport 12.4

#3478 [TASK] Revise "JavaScript form helpers" chapter
  Documentation/ApiOverview/Backend/JavaScript/Forms/Index.rst
Labels: content, backport 12.4

#3477 [TASK] Revise "Navigation via JavaScript" chapter
  Documentation/ApiOverview/Backend/JavaScript/Navigation/Index.rst
Labels: content, backport 12.4

#3476 [TASK] Extract JavaScript code snippets from Event API
  Documentation/ApiOverview/Backend/JavaScript/EventApi/Index.rst
  Documentation/ApiOverview/Backend/JavaScript/EventApi/_DebounceEvent.js
  Documentation/ApiOverview/Backend/JavaScript/EventApi/_DirectBinding.js
  Documentation/ApiOverview/Backend/JavaScript/EventApi/_EventDelegation.js
  Documentation/ApiOverview/Backend/JavaScript/EventApi/_RegularEvent.js
  Documentation/ApiOverview/Backend/JavaScript/EventApi/_ReleaseEvent.js
  Documentation/ApiOverview/Backend/JavaScript/EventApi/_RequestAnimationFrameEvent.js
  Documentation/ApiOverview/Backend/JavaScript/EventApi/_ThrottleEvent.js
Labels: content, backport 12.4

#3490 [BUGFIX] Fix typos in Extbase's type converter chapter
  Documentation/ExtensionArchitecture/Extbase/Reference/Controller/TypeConverter.rst
Labels: backport 12.4

#3491 [TASK] #102043 - Adjust namespace for InMemoryTransport/InMemoryTransportFactory
  Documentation/ApiOverview/MessageBus/Index.rst
  Documentation/ApiOverview/MessageBus/_custom-transport.yaml
  Documentation/ApiOverview/MessageBus/_in-memory-transport.yaml
Labels: changelog, backport 12.4

#3492 [TASK] Add example for ModifyDatabaseQueryForContentEvent
  Documentation/ApiOverview/Events/Events/Backend/ModifyDatabaseQueryForContentEvent.rst
  Documentation/ApiOverview/Events/Events/Backend/_ModifyDatabaseQueryForContentEvent/_MyEventListener.php
  Documentation/ApiOverview/Events/Events/Backend/_ModifyDatabaseQueryForContentEvent/_Services.yaml
Labels: content missing, backport 12.4

#3493 [TASK] #102023 - Remove security.usePasswordPolicyForFrontendUsers
  Documentation/ApiOverview/PasswordPolicies/Index.rst
  Documentation/Configuration/Typo3ConfVars/SYS.rst
Labels: changelog

#3494 [BUGFIX] Correct typo in GFX/processor_colorspace
  Documentation/Configuration/Typo3ConfVars/GFX.rst
Labels: backport 11.5, backport 12.4

#3495 [TASK] Add admonition about using Extbase in CLI context
  Documentation/ApiOverview/CommandControllers/Index.rst
Labels: backport 11.5, backport 12.4
