Repository TYPO3-Documentation/TYPO3CMS-Reference-CoreApi, pull requests merged in 2023-10, with the labels that each got.

#3504 [TASK] #102020 - Remove legacy setting 'GFX/gdlib_png'
  Documentation/Configuration/Typo3ConfVars/GFX.rst
Labels: changelog

#3508 Renaming local_packages to packages
  Documentation/ApiOverview/DirectoryStructure/Index.rst
  Documentation/ExtensionArchitecture/Concepts/SystemAndLocalExtensions.rst
  Documentation/ExtensionArchitecture/FileStructure/Configuration/Index.rst
  Documentation/ExtensionArchitecture/FileStructure/Configuration/TypoScript/Index.rst
  Documentation/ExtensionArchitecture/HowTo/CreateNewExtension.rst
  Documentation/ExtensionArchitecture/Tutorials/Kickstart/Make/Index.rst
Labels: backport 11.5, backport 12.4

#3475 [TASK] Rename and move the page about AjaxRequest
  Documentation/ApiOverview/Backend/Ajax.rst
  Documentation/ApiOverview/Backend/AjaxClientSide.rst
  Documentation/ApiOverview/Backend/JavaScript/AjaxRequest/Index.rst
  Documentation/ApiOverview/Backend/JavaScript/AjaxRequest/_MyRequest1.js
  Documentation/ApiOverview/Backend/JavaScript/AjaxRequest/_MyRequest2.js
  Documentation/ApiOverview/Backend/JavaScript/AjaxRequest/_MyRequestPromise1.js
  Documentation/ApiOverview/Backend/JavaScript/AjaxRequest/_MyRequestPromise2.js
  Documentation/ApiOverview/Backend/JavaScript/AjaxRequest/_MyRequestPromise3.js
  Documentation/ApiOverview/Backend/JavaScript/Index.rst
Labels: content structure, backport 12.4

#3515 [DOCS] Change non-existant API `all` method to `getAll`
  Documentation/ApiOverview/SiteHandling/AccessingSiteConfiguration.rst
Labels: backport 12.4

#3519 [FEATURE] #101970 - Ajax API accepts native URL and URLSearchParams objects as arguments
  Documentation/ApiOverview/Backend/JavaScript/AjaxRequest/Index.rst
  Documentation/ApiOverview/Backend/JavaScript/AjaxRequest/_MyRequest1.js
  Documentation/ApiOverview/Backend/JavaScript/AjaxRequest/_MyRequest2.js
Labels: changelog

#3520 [FEATURE] #101818 - Add BeforeLoadedPageTsConfigEvent
  Documentation/ApiOverview/Events/Events/Core/TypoScript/BeforeLoadedPageTsConfigEvent.rst
  Documentation/ApiOverview/Events/Events/Core/TypoScript/_BeforeLoadedPageTsConfigEvent/_MyEventListener.php
  Documentation/CodeSnippets/Config/Api/Events/EventsCore.php
  Documentation/CodeSnippets/Events/Core/BeforeLoadedPageTsConfigEvent.rst.txt
  Documentation/_includes/EventsAttributeAddedNew.rst.txt
Labels: changelog

#3527 [TASK] #102113 - Remove legacy setting 'GFX/gdlib'
  Documentation/Configuration/Typo3ConfVars/GFX.rst
Labels: changelog

#3521 [FEATURE] #101807 - Automatic inclusion of user TSconfig of extensions
  Documentation/ApiOverview/PageTypes/CreateNewPageType.rst
  Documentation/ApiOverview/PageTypes/_ext_localconf.php
  Documentation/ApiOverview/PageTypes/_ext_tables.php
  Documentation/ApiOverview/PageTypes/_user.tsconfig
  Documentation/Configuration/Typo3ConfVars/BE.rst
  Documentation/ExtensionArchitecture/FileStructure/Configuration/Index.rst
  Documentation/ExtensionArchitecture/FileStructure/Configuration/UserTsconfig.rst
  Documentation/ExtensionArchitecture/FileStructure/ExtLocalconf.rst
Labels: changelog

#3530 add the global variables
  Documentation/ApiOverview/Authentication/Index.rst
Labels: backport 11.5, backport 12.4

#3526 [TASK] Decouple FlexForms event listener examples from EXT:examples
  Documentation/ApiOverview/Events/Events/Core/Configuration/AfterFlexFormDataStructureIdentifierInitializedEvent.rst
  Documentation/ApiOverview/Events/Events/Core/Configuration/_AfterFlexFormDataStructureIdentifierInitializedEvent/_FlexFormParsingModifyEventListener.php
  Documentation/ApiOverview/Events/Events/Core/Configuration/_AfterFlexFormDataStructureIdentifierInitializedEvent/_Services.yaml
  Documentation/CodeSnippets/Config/Api/Events/EventsCore.php
  Documentation/CodeSnippets/Events/Core/FlexFormParsingModifyEventListener/FlexFormParsingModifyEventListener.rst.txt
Labels: backport 12.4

#3542 [DOCS] Fix typo in guidelines
  Documentation/Security/GuidelinesExtensionDevelopment/Index.rst
Labels: backport 11.5, backport 12.4

#3538 [TASK] Fix CGL issues after update to php-cs-fixer v3.35.1
  Documentation/ApiOverview/Events/Events/Redirects/_ModifyRedirectManagementControllerViewDataEvent/_MyEventListener.php
  Documentation/ApiOverview/Events/Events/Redirects/_SlugRedirectChangeItemCreatedEvent/_AddPageTypeZeroSource/_MyEventListener.php
  Documentation/ApiOverview/Events/Events/Redirects/_SlugRedirectChangeItemCreatedEvent/_MyEventListener.php
Labels: backport 12.4

#3545 [BUGFIX] Correct confval value for BE/flexformForceCDATA
  Documentation/Configuration/Typo3ConfVars/BE.rst
Labels: backport 11.5, backport 12.4

#3541 [TASK] Run "composer normalize" in current version
  composer.json
Labels: backport 12.4

#3528 [TASK] #102065 - Document breaking change for INCLUDE_TYPOSCRIPT with DIR
  Documentation/Configuration/TypoScript/Syntax/FileImports/Index.rst
Labels: changelog, backport 12.4

#3540 [TASK] Link in example section to combined example in FlexForm events
  Documentation/ApiOverview/Events/Events/Core/Configuration/AfterFlexFormDataStructureParsedEvent.rst
  Documentation/ApiOverview/Events/Events/Core/Configuration/BeforeFlexFormDataStructureIdentifierInitializedEvent.rst
  Documentation/ApiOverview/Events/Events/Core/Configuration/BeforeFlexFormDataStructureParsedEvent.rst
Labels: backport 12.4

#3523 [FEATURE] #101838 - Add BeforeLoadedUserTsConfigEvent
  Documentation/ApiOverview/Events/Events/Core/TypoScript/BeforeLoadedUserTsConfigEvent.rst
  Documentation/ApiOverview/Events/Events/Core/TypoScript/_BeforeLoadedUserTsConfigEvent/_MyEventListener.php
  Documentation/CodeSnippets/Config/Api/Events/EventsCore.php
  Documentation/CodeSnippets/Events/Core/BeforeLoadedUserTsConfigEvent.rst.txt
Labels: changelog

#3547 [TASK] Adjust ModifyPageLayoutContentEvent page
  Documentation/ApiOverview/Events/Events/Backend/ModifyPageLayoutContentEvent.rst
  Documentation/ApiOverview/Events/Events/Backend/_ModifyPageLayoutContentEvent/_MyEventListener.php
Labels: backport 12.4

#3546 [TASK] Add missing info about auto-created DB fields from TCA in v12
  Documentation/ExtensionArchitecture/FileStructure/ExtTablesSql.rst
Labels: changelog, backport 12.4

#3395 [FEATURE] Introduce PSR-14 ModifyRecordOverlayIconIdentifierEvent #629
  Documentation/ApiOverview/Events/Events/Core/Imaging/Index.rst
  Documentation/ApiOverview/Events/Events/Core/Imaging/ModifyRecordOverlayIconIdentifierEvent.rst
  Documentation/ApiOverview/Events/Events/Core/Imaging/_ModifyRecordOverlayIconIdentifierEvent/_MyEventListener.php
  Documentation/CodeSnippets/Config/Api/Events/EventsCore.php
  Documentation/CodeSnippets/Events/Core/ModifyRecordOverlayIconIdentifierEvent.rst.txt
Labels: changelog

#3561 [CI] Lint every supported PHP version
  .github/workflows/tests.yml
Labels: backport 12.4

#3556 Restructure remarks of QueryBuilder->insert() section
  Documentation/ApiOverview/Database/QueryBuilder/Index.rst
Labels: backport 11.5, backport 12.4

#3569 [TASK] Revise soft references chapter
  Documentation/ApiOverview/SoftReferences/Index.rst
  Documentation/ApiOverview/SoftReferences/_MyController.php
  Documentation/ApiOverview/SoftReferences/_Services.yaml
  Documentation/ApiOverview/SoftReferences/_YourSoftReferenceParser.yaml
  Documentation/ApiOverview/SoftReferences/_tt_content_bodytext.php
Labels: content, backport 12.4

#3571 Fix example for cache config
  Documentation/ApiOverview/CachingFramework/QuickStart/_settings.php
Labels: backport 11.5, backport 12.4

#3575 [BUGFIX] Correct spelling of Configuration/TsConfig folder
  Documentation/ExtensionArchitecture/FileStructure/Configuration/Index.rst
Labels: backport 11.5, backport 12.4

#3574 [BUGFIX] Correct error in the error handling example
  Documentation/ApiOverview/ErrorAndExceptionHandling/Examples/Index.rst
Labels: backport 11.5, backport 12.4

#3555 [TASK] #102146 - Remove legacy setting BE/flexformForceCDATA
  Documentation/Configuration/Typo3ConfVars/BE.rst
Labels: changelog

#3581 [TASK] Link page types in "Redirect headers" chapter
  Documentation/ApiOverview/PageTypes/RedirectHeaders.rst
  Documentation/ApiOverview/PageTypes/TypesOfPages.rst
Labels: backport 12.4

#3582 [TASK] Remove mentioning of methods in description of ModifyPageLayoutContentEvent
  Documentation/ApiOverview/Events/Events/Backend/ModifyPageLayoutContentEvent.rst
Labels: backport 12.4

#3586 [TASK] Replace $GLOBALS['PAGES_TYPES'] in ext_tables.php chapter
  Documentation/ExtensionArchitecture/FileStructure/ExtTables.rst
Labels: backport 12.4

#3583 [TASK] Revise "Global values/Constants" chapter
  Documentation/ApiOverview/GlobalValues/Constants/Index.rst
Labels: backport 11.5, backport 12.4

#3588 [BUGFIX] Correct file name in ['config']['MM'] section
  Documentation/ExtensionArchitecture/FileStructure/ExtTablesSql.rst
Labels: backport 11.5, backport 12.4

#3595 [TASK] Restructure list of TCA types considering auto-creation of fields
  Documentation/ExtensionArchitecture/FileStructure/ExtTablesSql.rst
Labels: backport 12.4

#3594 [TASK] Describe TYPO3 constant
  Documentation/ApiOverview/GlobalValues/Constants/Index.rst
  Documentation/ExtensionArchitecture/FileStructure/ExtLocalconf.rst
  Documentation/ExtensionArchitecture/FileStructure/ExtTables.rst
  Documentation/ExtensionArchitecture/HowTo/ExtendingTca/Examples/Index.rst
Labels: content missing, backport 11.5, backport 12.4

#3599 [FEATURE] #102032 - Introduce native enum FileType
  Documentation/ApiOverview/GlobalValues/Constants/Index.rst
Labels: changelog

#3603 [TASK] #102101 - Document TypoScript parse edge case behavior
  Documentation/Configuration/TypoScript/Syntax/Operators/Index.rst
Labels: changelog, backport 12.4

#3605 [TASK] Add allowed values for $GLOBALS['TYPO3_CONF_VARS']['GFX']['jpg_quality']
  Documentation/Configuration/Typo3ConfVars/GFX.rst
Labels: backport 12.4

#3602 [BUGFIX] Add missing TypoScript code snippets
  Documentation/CodeSnippets/TypoScriptSyntax/CodeBlock1.rst.txt
  Documentation/CodeSnippets/TypoScriptSyntax/CodeBlock2.rst.txt
  Documentation/CodeSnippets/TypoScriptSyntax/CodeBlock3.rst.txt
  Documentation/CodeSnippets/TypoScriptSyntax/CodeBlockInvalidClosingBrace.rst.txt
  Documentation/CodeSnippets/TypoScriptSyntax/CodeBlockInvalidCondition.rst.txt
  Documentation/CodeSnippets/TypoScriptSyntax/CodeBlockInvalidImport.rst.txt
  Documentation/CodeSnippets/TypoScriptSyntax/Comments.rst.txt
  Documentation/CodeSnippets/TypoScriptSyntax/Conditions1.rst.txt
  Documentation/CodeSnippets/TypoScriptSyntax/Conditions2.rst.txt
  Documentation/CodeSnippets/TypoScriptSyntax/Conditions3.rst.txt
  Documentation/CodeSnippets/TypoScriptSyntax/Conditions4.rst.txt
  Documentation/CodeSnippets/TypoScriptSyntax/Conditions5.rst.txt
  Documentation/CodeSnippets/TypoScriptSyntax/Identifiers1.rst.txt
  Documentation/CodeSnippets/TypoScriptSyntax/Identifiers2.rst.txt
  Documentation/CodeSnippets/TypoScriptSyntax/OperatorAssignment.rst.txt
  Documentation/CodeSnippets/TypoScriptSyntax/OperatorCopy1.rst.txt
  Documentation/CodeSnippets/TypoScriptSyntax/OperatorCopy2.rst.txt
  Documentation/CodeSnippets/TypoScriptSyntax/OperatorCopy3.rst.txt
  Documentation/CodeSnippets/TypoScriptSyntax/OperatorCopy4.rst.txt
  Documentation/CodeSnippets/TypoScriptSyntax/OperatorMultiLine.rst.txt
  Documentation/CodeSnippets/TypoScriptSyntax/OperatorReference.rst.txt
  Documentation/CodeSnippets/TypoScriptSyntax/OperatorUnset.rst.txt
Labels: bug

#3606 Mention process database and errorlog
  Documentation/ApiOverview/Typo3CoreEngine/Database/Index.rst
Labels: backport 11.5, backport 12.4

#3608 Use associated array keys when defining TCA field 'CType' items.
  Documentation/ApiOverview/ContentElements/_AddingYourOwnContentElements/_tt_content.php
Labels: backport 12.4

#3609 Add the content element icon to TCA typeicon_classes
  Documentation/ApiOverview/ContentElements/_AddingYourOwnContentElements/_tt_content.php
Labels: backport 12.4

#3612 [DOCS] Add note on accessing defaults in FlexForm attributs
  Documentation/ApiOverview/FlexForms/Index.rst
Labels: backport 11.5, backport 12.4

#3600 [FEATURE] #101553 - Auto-create DB fields from TCA columns for various types
  Documentation/ExtensionArchitecture/FileStructure/ExtTablesSql.rst
Labels: changelog

#3618 [TASK] #102260 - Remove NotifySoftReferenceParser
  Documentation/ApiOverview/SoftReferences/Index.rst
  Documentation/ApiOverview/SoftReferences/_Services.yaml
Labels: changelog

#3601 [FEATURE] #102177 - Add configuration option for WebP quality
  Documentation/Configuration/Typo3ConfVars/GFX.rst
Labels: changelog

#3587 [TASK] #102113 - Add migration note for removed GFX/gdlib setting
  Documentation/Configuration/Typo3ConfVars/GFX.rst
Labels: changelog

#3621 [BUGFIX] Correct minimum value of image quality settings
  Documentation/Configuration/Typo3ConfVars/GFX.rst
Labels: backport 12.4

#3623 [TASK] Add links to TCA manual for type/subtype of preview renderer
  Documentation/ApiOverview/ContentElements/CustomBackendPreview.rst
Labels: backport 12.4

#3625 [TASK] Update screenshot of New Content Element Wizard
  Documentation/ApiOverview/ContentElements/AddingYourOwnContentElements.rst
  Documentation/ApiOverview/ContentElements/ContentElementsWizard.rst
  Documentation/Images/AutomaticScreenshots/CustomContentElements/ContentElementWizard.png
  Documentation/Images/AutomaticScreenshots/CustomContentElements/ContentElementWizard.rst.txt
  Documentation/Images/ManualScreenshots/Backend/ContentElementWizard.png
  Documentation/screenshots.json
Labels: backport 12.4

#3626 [BUGFIX] Correct some rendering issues
  Documentation/ApiOverview/FlexForms/Index.rst
  Documentation/ApiOverview/Localization/TranslationServer/Crowdin/Faq.rst
  Documentation/ExtensionArchitecture/Extbase/Reference/Controller/ActionController.rst
  Documentation/ExtensionArchitecture/FileStructure/ExtConfTemplate.rst
Labels: backport 11.5, backport 12.4

#3631 [FEATURE] #98517 - Username in password recovery mail
  Documentation/ApiOverview/Backend/AccessControl/PasswordReset/Index.rst
Labels: changelog, backport 12.4

#3630 [BUGFIX] #100788 - Ensure content object is available in UriBuilder
  Documentation/ExtensionArchitecture/Extbase/Reference/UriBuilder.rst
Labels: changelog, backport 12.4

#3635 Update _JavaScriptModulesExtended.php
  Documentation/ApiOverview/Backend/JavaScript/ES6/_JavaScriptModulesExtended.php
Labels: backport 12.4

#3634 [TASK] #98517 - Emphasize TypoScript info on file includes within curly braces
  Documentation/Configuration/TypoScript/Syntax/FileImports/Index.rst
Labels: changelog, backport 12.4
