Repository TYPO3-Documentation/TYPO3CMS-Reference-CoreApi, pull requests merged in 2023-08, with the labels that each got.

#3280 [TASK] Replaces default values for navigationComponent
  Documentation/ExtensionArchitecture/HowTo/BackendModule/ModuleConfiguration.rst
Labels: backport 12.4

#2809 [FEATURE] #98487 - Update CreateNewPageType for v12
  Documentation/ApiOverview/PageTypes/CreateNewPageType.rst
Labels: backport 12.4

#3282 [TASK] List available sizes for IconViewHelper
  Documentation/ApiOverview/Icon/Index.rst
Labels: backport 12.4

#3283 [TASK] Move snippets into separate files in event dispatcher chapter
  Documentation/ApiOverview/Events/EventDispatcher/Index.rst
  Documentation/ApiOverview/Events/EventDispatcher/_DoingThisAndThatEvent.php
  Documentation/ApiOverview/Events/EventDispatcher/_NullMailer.php
  Documentation/ApiOverview/Events/EventDispatcher/_ServicesWithMethod.yaml
  Documentation/ApiOverview/Events/EventDispatcher/_ServicesWithoutMethod.yaml
  Documentation/ApiOverview/Events/EventDispatcher/_SomeClass.php
  Documentation/ApiOverview/Events/EventDispatcher/_SomeClass2.php
Labels: backport 11.5, backport 12.4

#3284 [TASK] Add namespace and strict_types=1 to hook snippets
  Documentation/ApiOverview/Events/Hooks/Index.rst
  Documentation/ApiOverview/Events/Hooks/_SomeClass.php
  Documentation/ApiOverview/Events/Hooks/_SomeClassPostProc.php
Labels: backport 11.5, backport 12.4

#3293 [TASK] Remove RequireJS content
  Documentation/ApiOverview/Backend/BroadcastChannels.rst
  Documentation/ApiOverview/Backend/JavaScript/Index.rst
  Documentation/ApiOverview/Backend/JavaScript/RequireJS/Dependency/Index.rst
  Documentation/ApiOverview/Backend/JavaScript/RequireJS/Extensions/Index.rst
  Documentation/ApiOverview/Backend/JavaScript/RequireJS/Index.rst
  Documentation/ApiOverview/Backend/JavaScript/RequireJS/Shim/Index.rst
  Documentation/Settings.cfg
Labels: changelog

#3292 [TASK] Use "option" instead "confval" to avoid warnings in site handling
  Documentation/ApiOverview/SiteHandling/AddLanguages.rst
  Documentation/ApiOverview/SiteHandling/BaseVariants.rst
  Documentation/ApiOverview/SiteHandling/ErrorHandling/FluidErrorHandler.rst
  Documentation/ApiOverview/SiteHandling/ErrorHandling/Index.rst
  Documentation/ApiOverview/SiteHandling/ErrorHandling/PageErrorHandler.rst
  Documentation/ApiOverview/SiteHandling/ErrorHandling/WriteCustomErrorHandler.rst
Labels: backport 12.4

#3290 [TASK] Overhaul Create new pagetype
  Documentation/ApiOverview/PageTypes/CreateNewPageType.rst
  Documentation/ApiOverview/PageTypes/_Icons.php
  Documentation/ApiOverview/PageTypes/_UserConfiguration.tsconfig
  Documentation/ApiOverview/PageTypes/_ext_localconf.php
  Documentation/ApiOverview/PageTypes/_ext_tables.php
  Documentation/ApiOverview/PageTypes/_pages.php
Labels: backport 12.4

#3298 [TASK] Remove event tag from event listener registration
  Documentation/ApiOverview/Events/EventDispatcher/Index.rst
  Documentation/ApiOverview/Events/EventDispatcher/_ServicesWithMethod.yaml
  Documentation/ApiOverview/Events/EventDispatcher/_ServicesWithoutMethod.yaml
Labels: backport 12.4

#3306 Add feature flag "allowInsecureSiteResolutionByQueryParameters"
  Documentation/Configuration/Typo3ConfVars/SYS.rst
Labels: backport 11.5, backport 12.4

#3301 [BUGFIX] Correct display of namespace of EventDispatcherInterface
  Documentation/ExtensionArchitecture/HowTo/Events/Index.rst
Labels: bug, backport 12.4

#3310 [TASK] Add user TSconfig as a "should" for ext_localconf.php
  Documentation/ExtensionArchitecture/FileStructure/ExtLocalconf.rst
Labels: backport 11.5, backport 12.4

#3315 [TASK] Remove TYPO3CONF_VARS|FE|defaultUserTSconfig
  Documentation/Configuration/Typo3ConfVars/FE.rst
Labels: changelog

#3314 [TASK] Add video from dev days about Content Security Policy
  Documentation/ApiOverview/ContentSecurityPolicy/Index.rst
Labels: backport 12.4

#3317 [TASK] Revise enumeration chapter
  Documentation/ApiOverview/Enumerations/Enumeration.rst
  Documentation/ApiOverview/Enumerations/_Enumerations/_LikeWildcard.php
  Documentation/ApiOverview/Enumerations/_Enumerations/_SomeClass.php
  Documentation/ApiOverview/Enumerations/_Enumerations/_SomeClass2.php
  Documentation/ApiOverview/Enumerations/_Enumerations/_SomeClass3.php
  Documentation/ApiOverview/Enumerations/_Enumerations/_VersionState.php
Labels: backport 11.5, backport 12.4

#3271 [TASK] Remove paragraph about PHP 8 using log channels
  Documentation/ApiOverview/Logging/Logger/Index.rst
Labels: backport 12.4

#3294 [TASK] Streamline event dispatcher chapter
  Documentation/ApiOverview/Events/EventDispatcher/Index.rst
Labels: backport 11.5, backport 12.4

#3318 [TASK] Revise bitsets chapter
  Documentation/ApiOverview/Enumerations/BitSet.rst
  Documentation/ApiOverview/Enumerations/_BitSet/_Permissions.php
  Documentation/ApiOverview/Enumerations/_BitSet/_PlainExample.php
  Documentation/ApiOverview/Enumerations/_BitSet/_PlainExample2.php
Labels: backport 11.5, backport 12.4

#3319 [TASK] Add example for PolicyMutatedEvent
  Documentation/ApiOverview/Events/Events/Core/Security/PolicyMutatedEvent.rst
  Documentation/ApiOverview/Events/Events/Core/Security/_PolicyMutatedEvent/_MyEventListener.php
  Documentation/ApiOverview/Events/Events/Core/Security/_PolicyMutatedEvent/_Services.yaml
Labels: backport 12.4

#3328 [FEATURE] Add "nonce" request attribute
  Documentation/ApiOverview/RequestLifeCycle/RequestAttributes/Nonce.rst
Labels: backport 12.4

#3332 [TASK] Adjust nonce request attribute chapter
  Documentation/ApiOverview/RequestLifeCycle/RequestAttributes/Nonce.rst
Labels: changelog

#3334 [TASK] Add screenshots to event dispatcher chapter
  Documentation/ApiOverview/Events/EventDispatcher/Index.rst
  Documentation/Images/ManualScreenshots/Events/AdminPanelEvents.png
  Documentation/Images/ManualScreenshots/Events/ConfigurationEventListeners.png
Labels: backport 12.4

#3336 [TASK] Move icon configuration snippet
  Documentation/ApiOverview/Icon/Index.rst
  Documentation/ApiOverview/Icon/_Icons.php
  Documentation/CodeSnippets/Manual/Extension/Configuration/IconsPhp.rst.txt
Labels: backport 12.4

#3338 [BUGFIX] Correct path to code snippet for Configuration/Icons.php
  Documentation/ExtensionArchitecture/FileStructure/Configuration/Icons.rst
Labels: backport 12.4

#3341 Update ModifyUrlForCanonicalTagEvent.rst
  Documentation/ApiOverview/Events/Events/SEO/ModifyUrlForCanonicalTagEvent.rst
Labels: backport 12.4

#3342 [TASK] Revise ext_tables.sql chapter
  Documentation/ExtensionArchitecture/FileStructure/ExtTablesSql.rst
Labels: backport 11.5, backport 12.4

#3347 [TASK] Move code snippets for ModifyUrlForCanonicalTagEvent into separate files
  Documentation/ApiOverview/Events/Events/SEO/ModifyUrlForCanonicalTagEvent.rst
  Documentation/ApiOverview/Events/Events/SEO/_ModifyUrlForCanonicalTagEvent/_MyEventListener.php
  Documentation/ApiOverview/Events/Events/SEO/_ModifyUrlForCanonicalTagEvent/_Services.yaml
Labels: backport 12.4

#3350 [FEATURE] #95061 - Auto creation of MM tables from TCA
  Documentation/ExtensionArchitecture/FileStructure/ExtTablesSql.rst
Labels: backport 11.5, backport 12.4

#3333 [TASK] Add "Nonce" section to "Content Security Policy" chapter
  Documentation/ApiOverview/ContentSecurityPolicy/Index.rst
Labels: backport 12.4

#3354 [FEATURE] #97173 - Auto creation of database fields for TCA "slug"
  Documentation/ExtensionArchitecture/FileStructure/ExtTablesSql.rst
Labels: backport 12.4

#3359 [BUGFIX] Correct indentations to avoid quote style in frontend plugins chapter
  Documentation/ExtensionArchitecture/Extbase/Reference/FrontendPlugins.rst
Labels: reST formatting, backport 12.4

#3360 [TASK] Streamline "Extending the TYPO3 Core" chapter
  Documentation/ApiOverview/Events/Concept/Index.rst
Labels: backport 12.4

#3357 [TASK] Add webhooks chapter
  Documentation/ApiOverview/Webhooks/Index.rst
  Documentation/Settings.cfg
Labels: backport 12.4

#3365 [TASK] Link nonce attribute in request overview page
  Documentation/ApiOverview/RequestLifeCycle/Typo3Request.rst
Labels: backport 12.4

#3358 [TASK] Move PHP code snippets into separate files in ext_conf_template.txt chapter
  Documentation/ExtensionArchitecture/FileStructure/ExtConfTemplate.rst
  Documentation/ExtensionArchitecture/FileStructure/_ExtConfTemplate/_MyClass.php
  Documentation/ExtensionArchitecture/FileStructure/_ExtConfTemplate/_MyClass2.php
Labels: backport 11.5, backport 12.4

#3367 [TASK] #101160 - Re-introduce hreflang attribute of site language configuration
  Documentation/ApiOverview/SiteHandling/AddLanguages.rst
  Documentation/CodeSnippets/Manual/Entity/SiteLanguage.rst.txt
Labels: changelog, backport 12.4

#3373 [TASK] Move code snippets into separate files in "backend routing" chapter
  Documentation/ApiOverview/Backend/BackendRouting.rst
  Documentation/ApiOverview/Backend/_BackendRouting/_MyRouteController.php
  Documentation/ApiOverview/Backend/_BackendRouting/_RoutesBackend.php
  Documentation/ApiOverview/Backend/_BackendRouting/_RoutesMyRoute.php
Labels: backport 12.4

#3372 [TASK] Remove outdated warning for ModifyResultItemInLiveSearchEvent
  Documentation/ApiOverview/Events/Events/Backend/ModifyResultItemInLiveSearchEvent.rst
Labels: backport 12.4

#3371 [TASK] Rephrase section about performance optimization in custom FAL drivers
  Documentation/ApiOverview/Fal/UsingFal/ExamplesFileSearch.rst
Labels: backport 12.4

#3361 [FEATURE] #101544 - Introduce PHP attribute to autoconfigure event listeners
  Documentation/ApiOverview/Events/EventDispatcher/Index.rst
  Documentation/ApiOverview/Events/EventDispatcher/_NullMailer.php
  Documentation/ApiOverview/Events/EventDispatcher/_ServicesWithMethod.yaml
  Documentation/ApiOverview/Events/EventDispatcher/_ServicesWithoutMethod.yaml
Labels: changelog

#3381 [TASK] #101291 - Introduce capabilities bit set
  Documentation/ApiOverview/Fal/UsingFal/ExamplesFileSearch.rst
Labels: changelog

#3383 [TASK] Fix CGL after update of php-cs-fixer to v3.23.0
  Documentation/ApiOverview/CachingFramework/FrontendsBackends/_redis.php
  Documentation/CodeSnippets/Config/Tutorials/ContextMenu.php
  Documentation/CodeSnippets/Config/Tutorials/Tea.php
Labels: backport 11.5, backport 12.4

#3384 [TASK] Add an example for registering same class for different events
  Documentation/ApiOverview/Events/EventDispatcher/Index.rst
  Documentation/ApiOverview/Events/EventDispatcher/_NullMailerRepeatable.php
Labels: changelog

#3388 [BUGFIX] Correct include of example for SlugRedirectChangeItemCreatedEvent
  Documentation/ApiOverview/Events/Events/Redirects/SlugRedirectChangeItemCreatedEvent.rst
Labels: backport 12.4

#3391 [TASK] Revise TSFE chapter
  Documentation/ApiOverview/TSFE/Index.rst
  Documentation/ApiOverview/TSFE/_MyClass.php
Labels: backport 12.4

#3390 [FEATURE] #100662 - Add currentContentObject to list of request attributes
  Documentation/ApiOverview/RequestLifeCycle/RequestAttributes/CurrentContentObject.rst
  Documentation/ApiOverview/RequestLifeCycle/Typo3Request.rst
Labels: changelog, backport 12.4
