Repository TYPO3-Documentation/TYPO3CMS-Reference-CoreApi, pull requests merged in 2023-02, with the labels that each got.

#2647 Add info about newly added TYPO3 system extensions and how to activat…
  Documentation/ApiOverview/Localization/TranslationServer/Crowdin/Faq.rst
Labels: backport 11.5

#2651 [TASK] Use captions for code snippets in Localization/PHP chapter
  Documentation/ExtensionArchitecture/HowTo/Localization/Php.rst
  Documentation/ExtensionArchitecture/HowTo/Localization/_php/MyBackendClass.php
  Documentation/ExtensionArchitecture/HowTo/Localization/_php/MyUserFunction.php
  Documentation/ExtensionArchitecture/HowTo/Localization/_php/MyUtility.php
Labels: backport 11.5

#2656 [TASK] Add tip about ignoring ENABLE_INSTALL_TOOL file
  Documentation/Security/GuidelinesIntegrators/InstallTool.rst
Labels: backport 11.5

#2665 Add missing view.defaultPid option declaration
  Documentation/ExtensionArchitecture/Extbase/Reference/TypoScriptConfiguration.rst
Labels: backport-required

#2664 [IMPORTANT] #95297 - Strict cHash validation feature flag
  Documentation/ApiOverview/CachingFramework/Index.rst
  Documentation/Configuration/Typo3ConfVars/FE.rst
Labels: backport 11.5, backport 10.4

#2668 Add note about NULL values in CSV fixtures
  Documentation/Testing/WritingFunctional.rst
Labels: backport 11.5

#2667 Add strict comparison operators to fluid documentation
  Documentation/ApiOverview/Fluid/Syntax.rst
Labels: backport 11.5, backport 10.4

#2671 Remove "for backend" in the chapter title
  Documentation/ApiOverview/Localization/ManagingTranslations.rst
Labels: backport 11.5

#2660 [TASK] Link "XLIFF format" in localization introduction chapter
  Documentation/ApiOverview/Localization/Introduction.rst
Labels: backport 11.5

#2678 [TASK] Streamline extension manager events
  Documentation/ApiOverview/Events/Events/ExtensionManager/AfterExtensionDatabaseContentHasImportedEvent.rst
  Documentation/ApiOverview/Events/Events/ExtensionManager/AfterExtensionFilesHaveBeenImportedEvent.rst
  Documentation/ApiOverview/Events/Events/ExtensionManager/AfterExtensionStaticDatabaseContentHasBeenImportedEvent.rst
  Documentation/ApiOverview/Events/Events/ExtensionManager/AvailableActionsForExtensionEvent.rst
Labels: backport 11.5

#2682 [TASK] Streamline seo events
  Documentation/ApiOverview/Events/Events/SEO/ModifyUrlForCanonicalTagEvent.rst
Labels: backport 11.5

#2681 [TASK] Streamline import/export events
  Documentation/ApiOverview/Events/Events/Impexp/BeforeImportEvent.rst
Labels: backport 11.5

#2679 [TASK] Move file list events code snippets into separate files
  Documentation/ApiOverview/Events/Events/Filelist/ModifyEditFileFormDataEvent.rst
  Documentation/ApiOverview/Events/Events/Filelist/ProcessFileListActionsEvent.rst
  Documentation/ApiOverview/Events/Events/Filelist/_Snippets/_ModifyEditFileFormDataEvent.yaml
  Documentation/ApiOverview/Events/Events/Filelist/_Snippets/_ModifyEditFileFormDataEventListener.php
  Documentation/ApiOverview/Events/Events/Filelist/_Snippets/_ProcessFileListActionsEvent.yaml
  Documentation/ApiOverview/Events/Events/Filelist/_Snippets/_ProcessFileListActionsEventListener.php
Labels: backport 11.5

#2675 [TASK] Streamline configuration files chapter
  Documentation/ExtensionArchitecture/BestPractises/ConfigurationFiles.rst
Labels: backport 11.5

#2685 [TASK] Revise "Site handling" > "Adding languages" chapter
  Documentation/ApiOverview/SiteHandling/AddLanguages.rst
  Documentation/ApiOverview/SiteHandling/_language-example.yaml
Labels: backport 11.5

#2700 [TASK] Streamline "Site handling" > "Using site config in conditions" chapter
  Documentation/ApiOverview/SiteHandling/UseSiteInConditions.rst
  Documentation/ApiOverview/SiteHandling/_form-condition.yaml
Labels: backport 11.5

#2703 [TASK] Streamline "Site handling" > "Extending site config" chapter
  Documentation/ApiOverview/SiteHandling/AccessingSiteConfiguration.rst
  Documentation/ApiOverview/SiteHandling/ExtendingSiteConfig.rst
  Documentation/ApiOverview/SiteHandling/_extending-site-config.php
  Documentation/ApiOverview/SiteHandling/_extending-site-config.yaml
Labels: backport 11.5

#2699 [TASK] Streamline "Site handling" > "Using env variables" chapter
  Documentation/ApiOverview/SiteHandling/UsingEnvVars.rst
Labels: backport 11.5

#2696 [TASK] Streamline "Site handling" > "Base variants" chapter
  Documentation/ApiOverview/SiteHandling/BaseVariants.rst
  Documentation/ApiOverview/SiteHandling/_base-variants.yaml
Labels: backport 11.5

#2710 [TASK] Write all special TypoScript Conditions in UPPERCASE
  Documentation/ApiOverview/SiteHandling/UseSiteInConditions.rst
  Documentation/ExtensionArchitecture/HowTo/Localization/TypoScript.rst
Labels: backport 11.5

#2698 [TASK] Streamline "Site handling" > "Static routes" chapter
  Documentation/ApiOverview/SiteHandling/StaticRoutes.rst
  Documentation/ApiOverview/SiteHandling/_static-routes-static-text.yaml
  Documentation/ApiOverview/SiteHandling/_static-routes-uri.yaml
Labels: backport 11.5

#2714 Use the ResponseFactory to create the response
  Documentation/ApiOverview/Backend/Ajax.rst
Labels: backport 11.5

#2718 [TASK] Streamline log writers chapter
  Documentation/ApiOverview/Logging/Writers/Index.rst
  Documentation/ApiOverview/Logging/Writers/_MyClassWithConstructorInjection.php
  Documentation/ApiOverview/Logging/Writers/_MyClassWithLoggerAwareInterface.php
Labels: backport 11.5

#2702 [TASK] Streamline "Site handling" > "Site settings" chapter
  Documentation/ApiOverview/SiteHandling/SiteSettings.rst
  Documentation/ApiOverview/SiteHandling/_site-settings.yaml
Labels: backport 11.5

#2697 [TASK] Streamline "Site handling" > "Error handling" chapter
  Documentation/ApiOverview/SiteHandling/ErrorHandling/FluidErrorHandler.rst
  Documentation/ApiOverview/SiteHandling/ErrorHandling/Index.rst
  Documentation/ApiOverview/SiteHandling/ErrorHandling/PageErrorHandler.rst
  Documentation/ApiOverview/SiteHandling/ErrorHandling/WriteCustomErrorHandler.rst
  Documentation/ApiOverview/SiteHandling/ErrorHandling/_MyErrorHandler.php
  Documentation/ApiOverview/SiteHandling/ErrorHandling/_custom-error-handler.yaml
  Documentation/ApiOverview/SiteHandling/ErrorHandling/_fluid-error-handler.yaml
  Documentation/ApiOverview/SiteHandling/ErrorHandling/_page-error-handler-external.yaml
  Documentation/ApiOverview/SiteHandling/ErrorHandling/_page-error-handler-internal.yaml
Labels: backport 11.5

#2721 small addition to events
  Documentation/ApiOverview/Events/EventDispatcher/Index.rst
Labels: backport 11.5

#2729 Add note for non-default PreviewRenderers
  Documentation/ApiOverview/ContentElements/CustomBackendPreview.rst
Labels: backport 11.5

#2732 [TASK] Add example for applicationType request attribute
  Documentation/ApiOverview/RequestLifeCycle/RequestAttributes/ApplicationType.rst
Labels: backport 11.5

#2738 [TASK] Reference ext:container instead of ext:gridelements
  Documentation/ApiOverview/Backend/BackendLayout.rst
Labels: backport 11.5

#2740 Update README for target-language usage
  Documentation/ApiOverview/Localization/XliffFormat.rst
Labels: backport 11.5

#2577 [TASK] Add example for page title providers
  .editorconfig
  Documentation/ApiOverview/Seo/PageTitleApi.rst
  Documentation/ApiOverview/Seo/_ExampleSetInController/_MyOwnPageTitleProvider.php
  Documentation/ApiOverview/Seo/_ExampleSetInController/_SomeController.php
  Documentation/ApiOverview/Seo/_ExampleSetInController/_setup.typoscript
  Documentation/ApiOverview/Seo/_ExampleWebsiteTitle/_Services.yaml
  Documentation/ApiOverview/Seo/_ExampleWebsiteTitle/_WebsiteTitleProvider.php
  Documentation/ApiOverview/Seo/_ExampleWebsiteTitle/_setup.typoscript
Labels: backport 11.5
