Repository TYPO3-Documentation/TYPO3CMS-Reference-CoreApi, pull requests merged in 2023-04, with the labels that each got.

#2816 Explain how to generate a safe Encryption key
  Documentation/Security/GuidelinesIntegrators/InstallTool.rst
Labels: backport 11.5

#2826 [BUGFIX] Fixes variable call
  Documentation/ApiOverview/Seo/_ExampleWebsiteTitle/_WebsiteTitleProvider.php
Labels: backport 11.5

#2828 Mention composer package
  Documentation/Configuration/UserSettingsConfiguration/Index.rst
Labels: backport-required

#2845 [TASK] Remove the reference to the SOAP interface for publishing extensions
  Documentation/ExtensionArchitecture/HowTo/PublishExtension/PublishToTER/Index.rst
Labels: backport 11.5

#2850 [TASK] Clarify type of repository
  Documentation/ExtensionArchitecture/Extbase/Reference/Domain/Repository.rst
Labels: backport 11.5

#2853 [TASK] Discourage usage of Extbase in middlewares
  Documentation/ApiOverview/RequestLifeCycle/Middlewares.rst
  Documentation/ExtensionArchitecture/Extbase/Index.rst
Labels: backport 11.5

#2855 Update links on composer.json page
  Documentation/ExtensionArchitecture/FileStructure/ComposerJson.rst
Labels: backport 11.5, backport 10.4

#2862 [TASK] Remove mention of manual calculation of TS in middleware
  Documentation/ApiOverview/RequestLifeCycle/Middlewares.rst
Labels: backport 11.5

#2866 [TASK] Add note about using IDN domains as base in site configuration
  Documentation/ApiOverview/SiteHandling/Basics.rst
Labels: backport 11.5, backport 10.4

#2878 [TASK] Remove line numbers in code snippets
  Documentation/ApiOverview/CommandControllers/Tutorial.rst
  Documentation/ApiOverview/Events/Hooks/Index.rst
  Documentation/ApiOverview/Fluid/Introduction.rst
  Documentation/ApiOverview/Routing/Examples.rst
  Documentation/ApiOverview/Routing/ExtendingRouting.rst
  Documentation/ApiOverview/Rte/Transformations/Introduction.rst
  Documentation/ApiOverview/Typo3CoreEngine/UsingDataHandler/Index.rst
  Documentation/ExtensionArchitecture/FileStructure/ComposerJson.rst
Labels: backport 11.5

#2880 Fix typo
  Documentation/ApiOverview/RequestLifeCycle/RequestAttributes/FrontendController.rst
Labels: backport-required

#2886 TypoScript Condition without parameter Example
  Documentation/ApiOverview/SymfonyExpressionLanguage/Index.rst
Labels: backport 11.5, backport 12.4

#2888 [TASK] Update code snippets for v12.4
  Documentation/CodeSnippets/Events/Backend/BeforeSearchInDatabaseRecordProviderEvent.rst.txt
  Documentation/CodeSnippets/Events/Core/ModifyLoadedPageTsConfigEvent.rst.txt
  Documentation/CodeSnippets/Events/Frontend/ModifyPageLinkConfigurationEvent.rst.txt
  Documentation/CodeSnippets/Extbase/Api/Repository.rst.txt
  Documentation/CodeSnippets/Extbase/UriBuilder.rst.txt
Labels: backport 12.4

#2882 [BUGFIX] #100744 - Use correct configuration example for message routing
  Documentation/ApiOverview/MessageBus/Index.rst
  Documentation/Configuration/Typo3ConfVars/SYS.rst
Labels: backport 12.4

#2881 Fix typo in snippet of TypoScriptFrontendController->rootLine (#2880)
  Documentation/ApiOverview/RequestLifeCycle/RequestAttributes/FrontendController.rst
Labels: backport 12.4

#2895 Update Fluid/Introduction.rst
  Documentation/ApiOverview/Fluid/Introduction.rst
Labels: backport 11.5, backport 12.4
