Repository TYPO3-Documentation/TYPO3CMS-Reference-CoreApi, pull requests merged in 2023-11, with the labels that each got.

#3640 [TASK] Revise FAL Architecture main page
  Documentation/ApiOverview/Fal/Architecture/Index.rst
Labels: backport 11.5, backport 12.4

#3645 [TASK] Revise FAL Architecture Overview page
  Documentation/ApiOverview/Fal/Architecture/Overview.rst
Labels: backport 11.5, backport 12.4

#3641 [TASK] Revise FAL Architecture Components page
  Documentation/ApiOverview/Fal/Architecture/Components.rst
Labels: backport 11.5, backport 12.4

#3642 [TASK] Revise FAL Architecture Database page
  Documentation/ApiOverview/Fal/Architecture/Database.rst
Labels: backport 11.5, backport 12.4

#3644 [TASK] Revise FAL Architecture Folders page
  Documentation/ApiOverview/Fal/Architecture/Folders.rst
Labels: backport 11.5, backport 12.4

#3643 [TASK] Revise FAL Architecture Events page
  Documentation/ApiOverview/Events/Events/Core/Resource/Index.rst
  Documentation/ApiOverview/Fal/Architecture/Events.rst
Labels: backport 11.5, backport 12.4

#3657 Fix CreateModule.rst code examples
  Documentation/ExtensionArchitecture/HowTo/BackendModule/CreateModule.rst
Labels: backport 11.5, backport 12.4

#3639 [TASK] Revise FAL Concepts chapter
  Documentation/ApiOverview/Fal/Concepts/Index.rst
Labels: backport 11.5, backport 12.4

#3646 [TASK] Revise FAL Collections page
  Documentation/ApiOverview/Fal/Collections/Index.rst
  Documentation/ApiOverview/Fal/Collections/_List.html
  Documentation/ApiOverview/Fal/Collections/_MyController.php
Labels: backport 11.5, backport 12.4

#3638 [TASK] Move FAL introduction to main page
  Documentation/ApiOverview/Fal/Index.rst
  Documentation/ApiOverview/Fal/Introduction/Index.rst
Labels: content structure, backport 11.5, backport 12.4

#3668 [TASK] Add FAL event introduced with TYPO3 v11
  Documentation/ApiOverview/Fal/Architecture/Events.rst
Labels: backport 11.5, backport 12.4

#3669 [TASK] Add FAL events introduced with TYPO3 v12
  Documentation/ApiOverview/Fal/Architecture/Events.rst
Labels: backport 12.4

#3675 [TASK] Indent directives on FAL Administration index page
  Documentation/ApiOverview/Fal/Administration/Index.rst
Labels: reST formatting, backport 11.5, backport 12.4

#3676 [TASK] Revise FAL Administration Maintenance page
  Documentation/ApiOverview/Fal/Administration/Maintenance.rst
Labels: backport 11.5, backport 12.4

#3677 [TASK] Revise FAL Administration Permissions page
  Documentation/ApiOverview/Fal/Administration/Permissions.rst
Labels: backport 11.5, backport 12.4

#3678 [TASK] Revise FAL Administration Storages page
  Documentation/ApiOverview/Fal/Administration/Storages.rst
  Documentation/ApiOverview/Fal/Architecture/Components.rst
Labels: backport 11.5, backport 12.4

#3679 [TASK] Indent directives on FAL / Using FAL index page
  Documentation/ApiOverview/Fal/UsingFal/Index.rst
Labels: backport 11.5, backport 12.4

#3682 [TASK] Revise FAL / Using Fal / The StorageRepository class chapter
  Documentation/ApiOverview/Fal/UsingFal/ExamplesStorageRepository.rst
  Documentation/ApiOverview/Fal/UsingFal/_ExamplesStorageRepository/_GetDefaultStorageExample.php
  Documentation/ApiOverview/Fal/UsingFal/_ExamplesStorageRepository/_GetStorageObjectExample.php
  Documentation/ApiOverview/Fal/UsingFal/_GetDefaultStorageExample.php
Labels: backport 11.5, backport 12.4

#3681 [TASK] Revise FAL / Using Fal / Using FAL in the frontend chapter
  Documentation/ApiOverview/Fal/UsingFal/Frontend.rst
Labels: backport 11.5, backport 12.4

#3683 [TASK] Revise FAL / Using Fal / Working with files, folders and file references chapter
  Documentation/ApiOverview/Fal/UsingFal/ExamplesFileFolder.rst
Labels: backport 11.5, backport 12.4

#3696 [BUGFIX] Correct path to classes in FAL's StorageRepository chapter
  Documentation/ApiOverview/Fal/UsingFal/ExamplesStorageRepository.rst
Labels: backport 11.5, backport 12.4

#3705 Update XliffFormat.rst
  Documentation/ApiOverview/Localization/XliffFormat.rst
Labels: backport 12.4

#3704 Use the default Redis port in example
  Documentation/ApiOverview/CachingFramework/FrontendsBackends/_redis.php
Labels: backport 11.5, backport 12.4

#3701 [TASK] Move code snippets into separate files for "FAL / Working with files, folders ..." chapter
  .php-cs-fixer.dist.php
  Documentation/ApiOverview/Fal/UsingFal/ExamplesFileFolder.rst
  Documentation/ApiOverview/Fal/UsingFal/_ExamplesFileFolder/_AddingFile.php
  Documentation/ApiOverview/Fal/UsingFal/_ExamplesFileFolder/_AddingFileToSubFolder.php
  Documentation/ApiOverview/Fal/UsingFal/_ExamplesFileFolder/_CopyingFile.php
  Documentation/ApiOverview/Fal/UsingFal/_ExamplesFileFolder/_CreatingFileReference.php
  Documentation/ApiOverview/Fal/UsingFal/_ExamplesFileFolder/_DeletingFile.php
  Documentation/ApiOverview/Fal/UsingFal/_ExamplesFileFolder/_GetFileByCombinedIdentifier.php
  Documentation/ApiOverview/Fal/UsingFal/_ExamplesFileFolder/_GetFileByFilenameFromItsFolder.php
  Documentation/ApiOverview/Fal/UsingFal/_ExamplesFileFolder/_GetFileByItsFilenameFromTheFolderObject.php
  Documentation/ApiOverview/Fal/UsingFal/_ExamplesFileFolder/_GetFileByUid.php
  Documentation/ApiOverview/Fal/UsingFal/_ExamplesFileFolder/_GetFilesInFolder.php
  Documentation/ApiOverview/Fal/UsingFal/_ExamplesFileFolder/_GetReferencedFile.php
Labels: backport 11.5, backport 12.4

#3620 [TASK] #101567 - Introduce Symfony attribute based registration of CLI commands
  Documentation/ApiOverview/CommandControllers/Tutorial.rst
  Documentation/ApiOverview/CommandControllers/_Tutorial/_DoSomethingCommandViaAttribute.php
Labels: changelog, backport 12.4

#3680 [TASK] Revise FAL / Using Fal / TCA definition chapter
  Documentation/ApiOverview/Fal/UsingFal/Tca.rst
  Documentation/ApiOverview/Fal/UsingFal/_Tca/_ext_tables.sql
  Documentation/ApiOverview/Fal/UsingFal/_Tca/_my_table.php
  Documentation/ApiOverview/Fal/UsingFal/_Tca/_overrides_my_table.php
Labels: backport 11.5, backport 12.4

#3717 [TASK] Revise "FAL / Working with collections" chapter
  Documentation/ApiOverview/Fal/UsingFal/ExamplesCollection.rst
  Documentation/ApiOverview/Fal/UsingFal/_ExamplesCollection/_CollectionExample.php
  Documentation/ApiOverview/Fal/UsingFal/_ExamplesCollection/_Iteration.html
Labels: backport 11.5, backport 12.4

#3715 [TASK] Remove ext_tables.sql definition for type "file" on FAL / TCA page
  Documentation/ApiOverview/Fal/UsingFal/Tca.rst
  Documentation/ApiOverview/Fal/UsingFal/_Tca/_ext_tables.sql
Labels: changelog

#3716 [TASK] Revise "FAL / Searching for files" chapter
  Documentation/ApiOverview/Fal/UsingFal/ExamplesFileSearch.rst
  Documentation/ApiOverview/Fal/UsingFal/_ExamplesFileSearch/_SearchInFolder.php
  Documentation/ApiOverview/Fal/UsingFal/_ExamplesFileSearch/_SearchInStorage.php
  Documentation/ApiOverview/Fal/UsingFal/_ExamplesFileSearch/_SearchInStorageWithRestrictions.php
  Documentation/CodeSnippets/Config/Api/All.php
  Documentation/CodeSnippets/Config/Api/Resource.php
  Documentation/CodeSnippets/Resource/FileSearchDemand.rst.txt
Labels: backport 11.5, backport 12.4

#3722 [BUGFIX] Use variable in method of FAL example
  Documentation/ApiOverview/Fal/UsingFal/_ExamplesFileSearch/_SearchInFolder.php
Labels: backport 12.4

#3723 [TASK] Update list of supported languages
  Documentation/ApiOverview/Localization/Languages.rst
Labels: backport 12.4

#3726 [TASK] Overhaul deprecation chapter
  Documentation/ApiOverview/Deprecation/Index.rst
  Documentation/ApiOverview/Deprecation/_additional.php
  Documentation/ApiOverview/Deprecation/_settings.php
  Documentation/Images/ManualScreenshots/Backend/EnablingDebugPreset.png
Labels: backport 11.5, backport 12.4

#3729 Fix broken navigationComponent example
  Documentation/ExtensionArchitecture/HowTo/BackendModule/ToplevelModules.rst
Labels: backport-required

#3619 [TASK] #101797 - Replace CSP mutation mode extend by inherit & append
  Documentation/ApiOverview/ContentSecurityPolicy/_ContentSecurityPolicies.php
Labels: changelog, backport 12.4

#3733 [TASK] #102293 - Allow creation of lossless webp images
  Documentation/Configuration/Typo3ConfVars/GFX.rst
Labels: changelog

#3735 [FEATURE] #101553 - Auto-create DB fields from TCA columns for type "inline"/"number"
  Documentation/ExtensionArchitecture/FileStructure/ExtTablesSql.rst
Labels: changelog

#3736 Explain term extkeyprefix
  Documentation/ExtensionArchitecture/BestPractises/NamingConventions.rst
Labels: backport 11.5, backport 12.4

#3740 Update OnlineTranslation.rst
  Documentation/ApiOverview/Localization/TranslationServer/Crowdin/OnlineTranslation.rst
Labels: backport 11.5, backport 12.4

#3744 [TASK] Replace line blocks with code block
  Documentation/ApiOverview/ContentElements/AddingYourOwnContentElements.rst
Labels: backport 11.5, backport 12.4

#3743 Change sitemap example to include actually valid doktypes in exclusion
  Documentation/ApiOverview/Seo/XmlSitemap.rst
Labels: backport 11.5, backport 12.4

#3749 [TASK] #102471 - Extend note of BeforeTcaOverridesEvent
  Documentation/ApiOverview/Events/Events/Core/Configuration/BeforeTcaOverridesEvent.rst
Labels: changelog
