Repository TYPO3-Documentation/TYPO3CMS-Reference-CoreApi, pull requests merged in 2023-06, with the labels that each got.

#3039 [TASK] Move code snippets into separate files for setup events
  Documentation/ApiOverview/Events/Events/Setup/AddJavaScriptModulesEvent.rst
  Documentation/ApiOverview/Events/Events/Setup/Index.rst
  Documentation/ApiOverview/Events/Events/Setup/_AddJavaScriptModulesEvent/_MyEventListener.php
  Documentation/ApiOverview/Events/Events/Setup/_AddJavaScriptModulesEvent/_Services.yaml
Labels: backport 12.4

#3040 [TASK] Move code snippets into separate files for workspace events
  Documentation/ApiOverview/Events/Events/Workspaces/AfterCompiledCacheableDataForWorkspaceEvent.rst
  Documentation/ApiOverview/Events/Events/Workspaces/AfterDataGeneratedForWorkspaceEvent.rst
  Documentation/ApiOverview/Events/Events/Workspaces/AfterRecordPublishedEvent.rst
  Documentation/ApiOverview/Events/Events/Workspaces/GetVersionedDataEvent.rst
  Documentation/ApiOverview/Events/Events/Workspaces/Index.rst
  Documentation/ApiOverview/Events/Events/Workspaces/ModifyVersionDifferencesEvent.rst
  Documentation/ApiOverview/Events/Events/Workspaces/SortVersionedDataEvent.rst
  Documentation/ApiOverview/Events/Events/Workspaces/_AfterRecordPublishedEvent/_MyEventListener.php
  Documentation/ApiOverview/Events/Events/Workspaces/_AfterRecordPublishedEvent/_Services.yaml
  Documentation/ApiOverview/Events/Events/Workspaces/_ModifyVersionDifferencesEvent/_MyEventListener.php
  Documentation/ApiOverview/Events/Events/Workspaces/_ModifyVersionDifferencesEvent/_Services.yaml
Labels: backport 12.4

#3047 [TASK] Move code snippets from DI chapter into separate files
  Documentation/ApiOverview/DependencyInjection/Index.rst
  Documentation/ApiOverview/DependencyInjection/_ConstructorInjection.php
  Documentation/ApiOverview/DependencyInjection/_InterfaceInjection.php
  Documentation/ApiOverview/DependencyInjection/_MethodInjection.php
  Documentation/ApiOverview/DependencyInjection/_MethodInjectionWithAbstract.php
  Documentation/ApiOverview/DependencyInjection/_MyClass.php
  Documentation/ApiOverview/DependencyInjection/_Services.yaml
  Documentation/ApiOverview/DependencyInjection/_ServicesWithConnection.yaml
  Documentation/ApiOverview/DependencyInjection/_ServicesWithPublic.yaml
  Documentation/ApiOverview/DependencyInjection/_ServicesWithoutAutowire.yaml
  Documentation/ApiOverview/DependencyInjection/_servicesInstallationWide.php
Labels: backport 12.4

#3053 [TASK] Adjust indentation of directives in "Events and hooks" chapter
  Documentation/ApiOverview/Events/Events/Backend/Index.rst
  Documentation/ApiOverview/Events/Events/Core/Authentication/Index.rst
  Documentation/ApiOverview/Events/Events/Core/Configuration/Index.rst
  Documentation/ApiOverview/Events/Events/Core/Core/Index.rst
  Documentation/ApiOverview/Events/Events/Core/DataHandling/Index.rst
  Documentation/ApiOverview/Events/Events/Core/Database/Index.rst
  Documentation/ApiOverview/Events/Events/Core/Domain/Index.rst
  Documentation/ApiOverview/Events/Events/Core/Html/Index.rst
  Documentation/ApiOverview/Events/Events/Core/Index.rst
  Documentation/ApiOverview/Events/Events/Core/Mail/Index.rst
  Documentation/ApiOverview/Events/Events/Core/Package/Index.rst
  Documentation/ApiOverview/Events/Events/Core/Page/Index.rst
  Documentation/ApiOverview/Events/Events/Core/PasswordPolicy/Index.rst
  Documentation/ApiOverview/Events/Events/Core/Resource/Index.rst
  Documentation/ApiOverview/Events/Events/Core/Security/Index.rst
  Documentation/ApiOverview/Events/Events/Core/Tree/Index.rst
  Documentation/ApiOverview/Events/Events/Core/TypoScript/Index.rst
  Documentation/ApiOverview/Events/Events/Extbase/Index.rst
  Documentation/ApiOverview/Events/Events/ExtensionManager/Index.rst
  Documentation/ApiOverview/Events/Events/Frontend/Index.rst
  Documentation/ApiOverview/Events/Events/FrontendLogin/Index.rst
  Documentation/ApiOverview/Events/Events/Impexp/Index.rst
  Documentation/ApiOverview/Events/Events/Index.rst
  Documentation/ApiOverview/Events/Events/Info/Index.rst
  Documentation/ApiOverview/Events/Events/Redirects/Index.rst
  Documentation/ApiOverview/Events/Events/SEO/Index.rst
  Documentation/ApiOverview/Events/Hooks/Index.rst
  Documentation/ApiOverview/Events/Index.rst
  Documentation/ApiOverview/Events/JavaScript/DebounceEvent/Index.rst
  Documentation/ApiOverview/Events/JavaScript/Index.rst
  Documentation/ApiOverview/Events/JavaScript/RegularEvent/Index.rst
  Documentation/ApiOverview/Events/JavaScript/RequestAnimationFrameEvent/Index.rst
  Documentation/ApiOverview/Events/JavaScript/ThrottleEvent/Index.rst
  Documentation/ApiOverview/Events/SignalsSlots/Index.rst
Labels: backport 12.4

#2801 [FEATURE] #97390 - Use password policy for password reset in ext:felogin
  Documentation/ApiOverview/PasswordPolicies/Index.rst
  Documentation/Configuration/Typo3ConfVars/SYS.rst
Labels: backport 12.4

#3052 [TASK] Streamline extension manager events
  Documentation/ApiOverview/Events/Events/ExtensionManager/AfterExtensionDatabaseContentHasImportedEvent.rst
  Documentation/ApiOverview/Events/Events/ExtensionManager/AfterExtensionFilesHaveBeenImportedEvent.rst
  Documentation/ApiOverview/Events/Events/ExtensionManager/AfterExtensionStaticDatabaseContentHasBeenImportedEvent.rst
  Documentation/ApiOverview/Events/Events/ExtensionManager/AvailableActionsForExtensionEvent.rst
Labels: backport 12.4

#3051 Fix 'The configuration key "tag" is unsupported for definition' (#3050)
  Documentation/ExtensionArchitecture/Extbase/Reference/Controller/TypeConverter.rst
Labels: backport 11.5

#3058 [BUGFIX] Correct wrong link syntax in $GLOBALS['TYPO3_CONF_VARS']['HTTP']
  Documentation/Configuration/Typo3ConfVars/HTTP.rst
Labels: backport 11.5, backport 12.4

#3060 [BUGFIX] Include correct snippets for ModifyFileDumpEvent
  Documentation/ApiOverview/Events/Events/Core/Resource/ModifyFileDumpEvent.rst
Labels: backport 12.4

#3062 Small typo
  Documentation/Security/GuidelinesExtensionDevelopment/Index.rst
Labels: backport 11.5, backport 12.4

#3069 [TASK] Synchronise available caches for TYPO3 v12.4
  Documentation/ApiOverview/CachingFramework/Architecture/Index.rst
Labels: backport 12.4

#3068 [TASK] Remove historical information from caching configuration section
  Documentation/ApiOverview/CachingFramework/Configuration/Index.rst
Labels: backport 11.5, backport 12.4

#3072 [BUGFIX] Correct language for console command
  Documentation/ApiOverview/Authentication/Index.rst
Labels: backport 11.5, backport 12.4

#3077 [TASK] #100925 - Use dedicated cache for database schema information
  Documentation/ApiOverview/CachingFramework/Architecture/Index.rst
Labels: changelog, backport 12.4

#3078 [TASK] Revise caching introduction chapter
  Documentation/ApiOverview/CachingFramework/Index.rst
  Documentation/_includes/CliCacheWarmup.rst.txt
Labels: backport 12.4

#3083 [TASK] Revise caching developer chapter
  Documentation/ApiOverview/CachingFramework/Developer/Index.rst
  Documentation/ApiOverview/CachingFramework/Developer/_MyClass.php
  Documentation/ApiOverview/CachingFramework/Developer/_Services.yaml
  Documentation/ApiOverview/CachingFramework/Developer/_Services_autowiring.yaml
Labels: backport 12.4

#3082 [TASK] Revise caching configuration chapter
  Documentation/ApiOverview/CachingFramework/Configuration/Index.rst
Labels: backport 12.4

#3084 [TASK] Remove Wincache cache backend
  Documentation/ApiOverview/CachingFramework/FrontendsBackends/Index.rst
Labels: backport 12.4

#3079 [FEATURE] Add cache flush and cache warmup events
  Documentation/ApiOverview/Events/Events/Core/Cache/CacheFlushEvent.rst
  Documentation/ApiOverview/Events/Events/Core/Cache/CacheWarmupEvent.rst
  Documentation/ApiOverview/Events/Events/Core/Cache/Index.rst
  Documentation/CodeSnippets/Config/Api/Events/EventsCore.php
  Documentation/CodeSnippets/Events/Core/Cache/CacheFlushEvent.rst.txt
  Documentation/CodeSnippets/Events/Core/Cache/CacheWarmupEvent.rst.txt
Labels: changelog, backport 11.5, backport 12.4

#3081 [TASK] Adjust ModifyVersionDifferencesEvent
  Documentation/ApiOverview/Events/Events/Workspaces/ModifyVersionDifferencesEvent.rst
  Documentation/CodeSnippets/Events/Workspaces/ModifyVersionDifferencesEvent.rst.txt
Labels: backport 12.4

#3080 [TASK] #101000 - Remove deprecated restriction classes
  Documentation/ApiOverview/Database/RestrictionBuilder/Index.rst
  Documentation/ApiOverview/Workspaces/Index.rst
Labels: changelog

#3096 [BUGFIX] Fix core log Classes links
  Documentation/ApiOverview/Logging/Writers/Index.rst
Labels: backport 11.5, backport 12.4

#3102 [TASK] #101028 - Removed deprecated modifyBlindedConfigurationOptions hook
  Documentation/Configuration/ConfigurationModule/Index.rst
Labels: changelog

#3109 [TASK] #101036 - Remove deprecation createVersionNumberedFilename accepting a string
  Documentation/Configuration/Typo3ConfVars/FE.rst
Labels: changelog

#3111 [TASK] #101049 - Remove deprecated code in UserSessionManager
  Documentation/ApiOverview/SessionStorageFramework/_UserSessionManager.rst.txt
Labels: changelog

#3112 [TASK] Streamline chapter about TCA file structure
  Documentation/ExtensionArchitecture/FileStructure/Configuration/TCA/Index.rst
Labels: backport 11.5, backport 12.4

#3105 [BUGFIX] Update backend controller actions code example (#3070)
  Documentation/ApiOverview/FormEngine/Rendering/_ImportDataController.php
Labels: backport 12.4

#2977 Remove nimut framework from composer.json
  Documentation/ExtensionArchitecture/FileStructure/ComposerJson.rst
Labels: backport 12.4

#3129 [TASK] Clarify escapeChildren for ViewHelpers
  Documentation/ApiOverview/Fluid/DevelopCustomViewhelper.rst
Labels: backport 11.5, backport 12.4

#3128 [TASK] #101037 - Remove deprecated LanguageService-related settings
  Documentation/ApiOverview/Localization/LocalizationApi/_LanguageService.rst.txt
  Documentation/Configuration/Typo3ConfVars/BE.rst
Labels: changelog

#3126 [TASK] #101074 - Remove deprecated binding of this for selected context menu items
  Documentation/ApiOverview/Backend/ContextualMenu.rst
  Documentation/ApiOverview/Backend/_ContextMenu/_dataset-version-11.js
  Documentation/ApiOverview/Backend/_ContextMenu/_dataset.js
Labels: changelog

#3127 [TASK] #101079 - Remove SiteLanguageAwareTrait check from AspectFactory
  Documentation/ApiOverview/Routing/ExtendingRouting.rst
Labels: changelog

#3107 [TASK] Revise caching quick start chapter
  Documentation/ApiOverview/CachingFramework/QuickStart/Index.rst
Labels: backport 12.4

#3125 [TASK] #101068 - Remove deprecated code Typo3QuerySettings
  Documentation/ExtensionArchitecture/Extbase/Reference/Domain/Repository.rst
Labels: changelog

#3106 [TASK] Revise caching architecture chapter
  Documentation/ApiOverview/CachingFramework/Architecture/Index.rst
Labels: backport 12.4

#3134 [TASK] Remove references to ExtensionUtility::registerModule()
  Documentation/ExtensionArchitecture/BestPractises/NamingConventions.rst
  Documentation/ExtensionArchitecture/HowTo/BackendModule/BackendGUI.rst
Labels: backport 12.4

#3133 [TASK] #101091 #101093 - Remove deprecations in FormDataCompiler
  Documentation/ApiOverview/FormEngine/DataCompiling/Index.rst
Labels: changelog

#3124 [TASK] #101065 - Remove obsolete method QueryBuilder->execute()
  Documentation/ApiOverview/Database/QueryBuilder/Index.rst
  Documentation/ApiOverview/Database/Statement/Index.rst
Labels: changelog

#3122 [TASK] Remove mentioning of $GLOBALS['TBE_MODULES']
  Documentation/ExtensionArchitecture/BestPractises/NamingConventions.rst
Labels: backport 12.4

#3123 [TASK] #101064 - Remove deprecated methods from ExpressionBuilder
  Documentation/ApiOverview/Database/ExpressionBuilder/Index.rst
Labels: changelog

#3121 [TASK] Use ContextualFeedbackSeverity instead of deprecated FlashMessage constant
  Documentation/ApiOverview/FlashMessages/FlashMessagesApi.rst
Labels: backport 12.4

#3119 [TASK] #101058 - Remove context sensitive help (CSH)
  Documentation/ApiOverview/ContextSensitiveHelp/Index.rst
Labels: changelog

#3110 [TASK] #101047 - Remove registration of upgrade wizards via $GLOBALS
  Documentation/ExtensionArchitecture/HowTo/UpdateExtensions/UpdateWizards/Creation.rst
Labels: changelog

#3136 [TASK] #101087 - Always enable "security.backend.enforceContentSecurityPolicy" feature
  Documentation/ApiOverview/ContentSecurityPolicy/Index.rst
  Documentation/Configuration/Typo3ConfVars/SYS.rst
Labels: changelog

#3141 [TASK] #101099 - Remove deprecated code in LocalizationUtility
  Documentation/ApiOverview/Localization/LocalizationApi/_LocalizationUtilityApi.rst.txt
Labels: changelog

#3142 [TASK] Re-render code snippets with fix for array shapes
  Documentation/CodeSnippets/Events/Backend/BeforeSearchInDatabaseRecordProviderEvent.rst.txt
  Documentation/CodeSnippets/Events/Backend/ModifyAllowedItemsEvent.rst.txt
  Documentation/CodeSnippets/Events/Backend/ModifyEditFormUserAccessEvent.rst.txt
  Documentation/CodeSnippets/Events/Backend/ModifyFileReferenceControlsEvent.rst.txt
  Documentation/CodeSnippets/Events/Backend/ModifyFileReferenceEnabledControlsEvent.rst.txt
  Documentation/CodeSnippets/Events/Backend/ModifyInlineElementControlsEvent.rst.txt
  Documentation/CodeSnippets/Events/Backend/ModifyInlineElementEnabledControlsEvent.rst.txt
  Documentation/CodeSnippets/Events/Backend/ModifyLinkHandlersEvent.rst.txt
  Documentation/CodeSnippets/Events/Backend/ModifyRecordListHeaderColumnsEvent.rst.txt
  Documentation/CodeSnippets/Events/Backend/ModifyRecordListRecordActionsEvent.rst.txt
  Documentation/CodeSnippets/Events/Backend/ModifyRecordListTableActionsEvent.rst.txt
  Documentation/CodeSnippets/Events/Core/AfterGroupsResolvedEvent.rst.txt
  Documentation/CodeSnippets/Events/Core/Resource/AfterFileCommandProcessedEvent.rst.txt
  Documentation/CodeSnippets/Events/Core/Security/PolicyMutatedEvent.rst.txt
  Documentation/CodeSnippets/Events/FrontendLogin/SendRecoveryEmailEvent.rst.txt
  Documentation/CodeSnippets/Events/Redirects/BeforeRedirectMatchDomainEvent.rst.txt
  Documentation/CodeSnippets/Events/Setup/AddJavaScriptModulesEvent.rst.txt
  Documentation/CodeSnippets/Events/Workspaces/AfterCompiledCacheableDataForWorkspaceEvent.rst.txt
  Documentation/CodeSnippets/Events/Workspaces/ModifyVersionDifferencesEvent.rst.txt
  Documentation/CodeSnippets/Extbase/Api/Repository.rst.txt
  Documentation/CodeSnippets/Extbase/FrontendPlugins/TypoScriptPluginRss.rst.txt
  Documentation/CodeSnippets/Extbase/UriBuilder.rst.txt
  Documentation/CodeSnippets/Manual/Backend/ModuleInterface.rst.txt
  Documentation/CodeSnippets/Manual/Backend/ModuleProvider.rst.txt
  Documentation/CodeSnippets/Manual/Core/SiteFinder.rst.txt
  Documentation/CodeSnippets/Manual/Country/CountryProvider.rst.txt
  Documentation/CodeSnippets/Manual/Entity/Module.rst.txt
  Documentation/CodeSnippets/Manual/Entity/ModuleData.rst.txt
  Documentation/CodeSnippets/Manual/Entity/NormalizedParams.rst.txt
  Documentation/CodeSnippets/Manual/Entity/PageArguments.rst.txt
  Documentation/CodeSnippets/Manual/Entity/Route.rst.txt
Labels: backport 12.4

#3143 [TASK] Add deprecation note for $GLOBALS['BE_USER']->modAccess()
  Documentation/ApiOverview/Backend/BackendUserObject.rst
Labels: changelog, backport 12.4

#3156 [TASK] #101096 - Remove deprecated code in PasswordChangeEvent
  Documentation/ApiOverview/Events/Events/FrontendLogin/PasswordChangeEvent.rst
  Documentation/CodeSnippets/Events/FrontendLogin/PasswordChangeEvent.rst.txt
  Documentation/ExtensionArchitecture/HowTo/Events/Index.rst
Labels: changelog

#3157 [FEATURE] #99084 - Make context menu trigger configurable
  Documentation/ApiOverview/Backend/ContextualMenu.rst
Labels: changelog, backport 12.4

#2838 [TASK] Enhance description of "_assets" folder
  Documentation/ApiOverview/DirectoryStructure/Index.rst
Labels: backport 12.4

#3158 [TASK] #101097 - Remove deprecated TS in ext:felogin
  Documentation/ApiOverview/PasswordPolicies/Index.rst
  Documentation/Configuration/Typo3ConfVars/SYS.rst
Labels: changelog

#3135 [TASK] Add note for security.backend.enforceContentSecurityPolicy
  Documentation/Configuration/Typo3ConfVars/SYS.rst
Labels: changelog

#3153 [TASK] #101115 - Remove deprecated code related to TCEforms
  Documentation/ApiOverview/FlexForms/Index.rst
Labels: changelog

#3150 [TASK] Adjust section about backend module access in workspaces
  Documentation/ApiOverview/Workspaces/Index.rst
Labels: changelog, backport 12.4

#3144 [TASK] #101043 - Remove deprecated constants from FlashMessage class
  Documentation/ApiOverview/FlashMessages/FlashMessagesApi.rst
Labels: changelog

#3154 [BUGFIX] Remove the deprecated TCEforms tag in FlexForms definition
  Documentation/CodeSnippets/Events/Core/FlexFormParsingModifyEventListener/FlexFormParsingModifyEventListener.rst.txt
Labels: backport 12.4

#3101 [TASK] #101032 - Remove deprecated constant TYPO3_mainDir
  Documentation/ApiOverview/GlobalValues/Constants/Index.rst
Labels: changelog

#3104 [TASK] #101003 - Remove deprecated AbstractPlugin
  Documentation/ExtensionArchitecture/HowTo/FrontendPlugin/AbstractPlugin.rst
Labels: changelog

#3120 [TASK] #101057 - Remove deprecated code from Extbase type converters
  Documentation/ExtensionArchitecture/Extbase/Reference/Controller/TypeConverter.rst
Labels: changelog

#3148 [TASK] #101007 - Remove deprecated TBE_MODULES related functionality
  Documentation/ApiOverview/Backend/BackendUserObject.rst
  Documentation/Configuration/GlobalVariables.rst
  Documentation/ExtensionArchitecture/HowTo/BackendModule/ThirdlevelModules.rst
Labels: changelog

#3151 [TASK] #101056 - Remove deprecated code from ExtensionManagementUtility
  Documentation/ExtensionArchitecture/FileStructure/ExtTables.rst
Labels: changelog

#3168 [DOCS] Add note regarding data processor service sharing
  Documentation/ApiOverview/ContentElements/CustomDataProcessing.rst
Labels: backport 12.4

#3170 [TASK] Correct some leftovers regarding context menu changes
  Documentation/ApiOverview/Backend/ContextualMenu.rst
Labels: backport 12.4

#3152 [TASK] Move code snippets into separate files in caching chapter
  Documentation/ApiOverview/CachingFramework/Configuration/Index.rst
  Documentation/ApiOverview/CachingFramework/Configuration/_default.php
  Documentation/ApiOverview/CachingFramework/Configuration/_null.php
  Documentation/ApiOverview/CachingFramework/Configuration/_redis.php
  Documentation/ApiOverview/CachingFramework/Developer/Index.rst
  Documentation/ApiOverview/CachingFramework/Developer/_init.php
  Documentation/ApiOverview/CachingFramework/Developer/_transient.php
  Documentation/ApiOverview/CachingFramework/FrontendsBackends/Index.rst
  Documentation/ApiOverview/CachingFramework/FrontendsBackends/_redis.php
  Documentation/ApiOverview/CachingFramework/QuickStart/Index.rst
  Documentation/ApiOverview/CachingFramework/QuickStart/_settings.php
Labels: backport 12.4

#3172 [TASK] #101066 - Remove deprecated context menu configuration handling
  Documentation/ApiOverview/Backend/ContextualMenu.rst
Labels: changelog

#3173 [TASK] #101094 - Remove extbase ExtensionUtility::registerModule
  Documentation/ExtensionArchitecture/FileStructure/ExtTables.rst
  Documentation/ExtensionArchitecture/FileStructure/_ext_tables_registerModule.php
Labels: changelog

#3176 Introduce headlines and anchors for table naming conventions
  Documentation/ExtensionArchitecture/BestPractises/NamingConventions.rst
Labels: backport 11.5, backport 12.4

#3180 Update Repository.rst
  Documentation/ExtensionArchitecture/Extbase/Reference/Domain/Repository.rst
Labels: backport-required
