Repository TYPO3-Documentation/TYPO3CMS-Reference-CoreApi, pull requests merged in 2023-05, with the labels that each got.

#2892 Corrected typo in "Caching Framework Architecture"
  Documentation/ApiOverview/CachingFramework/Architecture/Index.rst
Labels: backport 11.5, backport 12.4

#2902 Overhaul the Extbase Frontend Plugin section
  Documentation/ExtensionArchitecture/Extbase/Reference/FrontendPlugins.rst
  Documentation/ExtensionArchitecture/Extbase/Reference/_FrontendPlugin/_ext_localconf.php
  Documentation/ExtensionArchitecture/Extbase/Reference/_FrontendPlugin/_ext_localconf_rss.php
  Documentation/ExtensionArchitecture/Extbase/Reference/_FrontendPlugin/_page.tsconfig
  Documentation/ExtensionArchitecture/Extbase/Reference/_FrontendPlugin/_setup.typoscript
  Documentation/ExtensionArchitecture/Extbase/Reference/_FrontendPlugin/_tt_content.php
Labels: backport 11.5, backport 12.4

#2899 Overhaul the hooks chapter
  Documentation/ApiOverview/Events/Hooks/Index.rst
  Documentation/ApiOverview/Events/Hooks/_DataHandler.php
  Documentation/ApiOverview/Events/Hooks/_SomeClass.php
  Documentation/ApiOverview/Events/Hooks/_SomeClassPostProc.php
  Documentation/ApiOverview/Events/Hooks/_ext_localconf_addhook.php
  Documentation/ApiOverview/Events/Hooks/_ext_localconf_schema.php
  Documentation/ApiOverview/Events/Hooks/_ext_localconf_schema_core.php
Labels: backport 12.4

#2912 [TASK] Move code snippets into separate files for info events
  Documentation/ApiOverview/Events/Events/Info/ModifyInfoModuleContentEvent.rst
  Documentation/ApiOverview/Events/Events/Info/_ModifyInfoModuleContentEvent/_MyEventListener.php
  Documentation/ApiOverview/Events/Events/Info/_ModifyInfoModuleContentEvent/_Services.yaml
Labels: backport 12.4

#2911 [TASK] Streamline frontend login events
  Documentation/ApiOverview/Events/Events/FrontendLogin/BeforeRedirectEvent.rst
  Documentation/ApiOverview/Events/Events/FrontendLogin/LoginConfirmedEvent.rst
  Documentation/ApiOverview/Events/Events/FrontendLogin/LoginErrorOccurredEvent.rst
  Documentation/ApiOverview/Events/Events/FrontendLogin/LogoutConfirmedEvent.rst
  Documentation/ApiOverview/Events/Events/FrontendLogin/ModifyLoginFormViewEvent.rst
  Documentation/ApiOverview/Events/Events/FrontendLogin/SendRecoveryEmailEvent.rst
Labels: backport 12.4

#2910 [TASK] Move code snippets into separate files for frontend events
  Documentation/ApiOverview/Events/Events/Frontend/AfterCacheableContentIsGeneratedEvent.rst
  Documentation/ApiOverview/Events/Events/Frontend/AfterCachedPageIsPersistedEvent.rst
  Documentation/ApiOverview/Events/Events/Frontend/AfterLinkIsGeneratedEvent.rst
  Documentation/ApiOverview/Events/Events/Frontend/AfterPageAndLanguageIsResolvedEvent.rst
  Documentation/ApiOverview/Events/Events/Frontend/AfterPageWithRootLineIsResolvedEvent.rst
  Documentation/ApiOverview/Events/Events/Frontend/BeforePageIsResolvedEvent.rst
  Documentation/ApiOverview/Events/Events/Frontend/FilterMenuItemsEvent.rst
  Documentation/ApiOverview/Events/Events/Frontend/ModifyCacheLifetimeForPageEvent.rst
  Documentation/ApiOverview/Events/Events/Frontend/ModifyHrefLangTagsEvent.rst
  Documentation/ApiOverview/Events/Events/Frontend/ModifyPageLinkConfigurationEvent.rst
  Documentation/ApiOverview/Events/Events/Frontend/ModifyResolvedFrontendGroupsEvent.rst
  Documentation/ApiOverview/Events/Events/Frontend/ShouldUseCachedPageDataIfAvailableEvent.rst
  Documentation/ApiOverview/Events/Events/Frontend/_AfterCacheableContentIsGeneratedEvent/_MyEventListener.php
  Documentation/ApiOverview/Events/Events/Frontend/_AfterCacheableContentIsGeneratedEvent/_Services.yaml
  Documentation/ApiOverview/Events/Events/Frontend/_AfterCachedPageIsPersistedEvent/_MyEventListener.php
  Documentation/ApiOverview/Events/Events/Frontend/_AfterCachedPageIsPersistedEvent/_Services.yaml
  Documentation/ApiOverview/Events/Events/Frontend/_AfterLinkIsGeneratedEvent/_MyEventListener.php
  Documentation/ApiOverview/Events/Events/Frontend/_AfterLinkIsGeneratedEvent/_Services.yaml
  Documentation/ApiOverview/Events/Events/Frontend/_ModifyCacheLifetimeForPageEvent/_MyEventListener.php
  Documentation/ApiOverview/Events/Events/Frontend/_ModifyCacheLifetimeForPageEvent/_Services.yaml
  Documentation/ApiOverview/Events/Events/Frontend/_ModifyHrefLangTagsEvent/_MyEventListener.php
  Documentation/ApiOverview/Events/Events/Frontend/_ModifyHrefLangTagsEvent/_Services.yaml
  Documentation/ApiOverview/Events/Events/Frontend/_ModifyPageLinkConfigurationEvent/_MyEventListener.php
  Documentation/ApiOverview/Events/Events/Frontend/_ModifyPageLinkConfigurationEvent/_Services.yaml
  Documentation/ApiOverview/Events/Events/Frontend/_ShouldUseCachedPageDataIfAvailableEvent/_MyEventListener.php
  Documentation/ApiOverview/Events/Events/Frontend/_ShouldUseCachedPageDataIfAvailableEvent/_Services.yaml
Labels: backport 12.4

#2909 [TASK] Add missing language information to literalinclude directive for events
  Documentation/ApiOverview/Events/Events/Backend/AfterBackendPageRenderEvent.rst
  Documentation/ApiOverview/Events/Events/Backend/AfterPagePreviewUriGeneratedEvent.rst
  Documentation/ApiOverview/Events/Events/Backend/AfterPageTreeItemsPreparedEvent.rst
  Documentation/ApiOverview/Events/Events/Backend/AfterRecordSummaryForLocalizationEvent.rst
  Documentation/ApiOverview/Events/Events/Backend/BeforeModuleCreationEvent.rst
  Documentation/ApiOverview/Events/Events/Backend/BeforePagePreviewUriGeneratedEvent.rst
  Documentation/ApiOverview/Events/Events/Backend/BeforeSearchInDatabaseRecordProviderEvent.rst
  Documentation/ApiOverview/Events/Events/Backend/IsFileSelectableEvent.rst
  Documentation/ApiOverview/Events/Events/Backend/ModifyAllowedItemsEvent.rst
  Documentation/ApiOverview/Events/Events/Backend/ModifyClearCacheActionsEvent.rst
  Documentation/ApiOverview/Events/Events/Backend/ModifyDatabaseQueryForRecordListingEvent.rst
  Documentation/ApiOverview/Events/Events/Backend/ModifyEditFormUserAccessEvent.rst
  Documentation/ApiOverview/Events/Events/Backend/ModifyGenericBackendMessagesEvent.rst
  Documentation/ApiOverview/Events/Events/Backend/ModifyImageManipulationPreviewUrlEvent.rst
  Documentation/ApiOverview/Events/Events/Backend/ModifyInlineElementControlsEvent.rst
  Documentation/ApiOverview/Events/Events/Backend/ModifyLinkExplanationEvent.rst
  Documentation/ApiOverview/Events/Events/Backend/ModifyLinkHandlersEvent.rst
  Documentation/ApiOverview/Events/Events/Backend/ModifyNewContentElementWizardItemsEvent.rst
  Documentation/ApiOverview/Events/Events/Backend/ModifyPageLayoutContentEvent.rst
  Documentation/ApiOverview/Events/Events/Backend/ModifyQueryForLiveSearchEvent.rst
  Documentation/ApiOverview/Events/Events/Backend/ModifyRecordListTableActionsEvent.rst
  Documentation/ApiOverview/Events/Events/Backend/ModifyResultItemInLiveSearchEvent.rst
  Documentation/ApiOverview/Events/Events/Backend/PageContentPreviewRenderingEvent.rst
  Documentation/ApiOverview/Events/Events/Core/Authentication/AfterUserLoggedInEvent.rst
  Documentation/ApiOverview/Events/Events/Core/Authentication/BeforeRequestTokenProcessedEvent.rst
  Documentation/ApiOverview/Events/Events/Core/Authentication/LoginAttemptFailedEvent.rst
  Documentation/ApiOverview/Events/Events/Core/PasswordPolicy/EnrichPasswordValidationContextDataEvent.rst
  Documentation/ApiOverview/Events/Events/Core/Resource/AfterDefaultUploadFolderWasResolvedEvent.rst
  Documentation/ApiOverview/Events/Events/Extbase/Configuration/BeforeFlexFormConfigurationOverrideEvent.rst
  Documentation/ApiOverview/Events/Events/Filelist/ModifyEditFileFormDataEvent.rst
  Documentation/ApiOverview/Events/Events/Filelist/ProcessFileListActionsEvent.rst
  Documentation/ApiOverview/Events/Events/Redirects/AfterAutoCreateRedirectHasBeenPersistedEvent.rst
  Documentation/ApiOverview/Events/Events/Redirects/BeforeRedirectMatchDomainEvent.rst
  Documentation/ApiOverview/Events/Events/Redirects/ModifyAutoCreateRedirectRecordBeforePersistingEvent.rst
  Documentation/ApiOverview/Events/Events/Redirects/ModifyRedirectManagementControllerViewDataEvent.rst
  Documentation/ApiOverview/Events/Events/Redirects/RedirectWasHitEvent.rst
  Documentation/ApiOverview/Events/Events/Redirects/SlugRedirectChangeItemCreatedEvent.rst
Labels: backport 12.4

#2900 Move Cache development code snippets to lintable files
  Documentation/ApiOverview/CachingFramework/Developer/Index.rst
  Documentation/ApiOverview/CachingFramework/Developer/_MyClass.php
  Documentation/ApiOverview/CachingFramework/Developer/_Services.yaml
  Documentation/ApiOverview/CachingFramework/Developer/_Services_autowiring.yaml
  Documentation/ApiOverview/CachingFramework/Developer/_ext_localconf.php
  Documentation/CodeSnippets/Extbase/FrontendPlugins/TypoScriptPluginRss.rst.txt
Labels: backport 11.5, backport 12.4

#2904 Unify the ext_localconf.php structure
  Documentation/ApiOverview/Database/Middleware/Index.rst
  Documentation/ApiOverview/Database/Middleware/_ext_localconf.php
  Documentation/ApiOverview/Database/RestrictionBuilder/Index.rst
  Documentation/ApiOverview/Database/RestrictionBuilder/_ext_localconf.php
  Documentation/ApiOverview/Database/RestrictionBuilder/_ext_localconf_remove.php
  Documentation/ApiOverview/Fluid/Syntax.rst
  Documentation/ApiOverview/Fluid/_Syntax/_ext_localconf.php
  Documentation/ApiOverview/LinkHandling/LinkBuilder.rst
  Documentation/ApiOverview/LinkHandling/_ext_localconf.php
  Documentation/ApiOverview/Localization/ManagingTranslations.rst
  Documentation/ApiOverview/Localization/_de.locallang_modadministration.xlf
  Documentation/ApiOverview/Localization/_ext_localconf.php
  Documentation/ApiOverview/Logging/Writers/Index.rst
  Documentation/ApiOverview/Logging/Writers/_ext_localconf.php
  Documentation/ApiOverview/Logging/Writers/_ext_localconf_FileWriter.php
  Documentation/ApiOverview/Logging/Writers/_ext_localconf_FileWriter_config.php
  Documentation/ApiOverview/Logging/Writers/_ext_tables.sql
  Documentation/ApiOverview/Routing/AdvancedRoutingConfiguration.rst
  Documentation/ApiOverview/Routing/ExtendingRouting.rst
  Documentation/ApiOverview/Routing/_AdvancedRoutingConfiguration/_ext_localconf.php
  Documentation/ApiOverview/Routing/_ExtendingRouting/_ext_localconf.php
  Documentation/ApiOverview/Routing/_ExtendingRouting/_ext_localconf_custom_enhancer.php
  Documentation/ApiOverview/Rte/InTheBackend/PlugRte.rst
  Documentation/ApiOverview/Rte/InTheBackend/_RichTextNodeResolver.php
  Documentation/ApiOverview/Rte/InTheBackend/_ext_localconf.php
  Documentation/ApiOverview/Seo/MetaTagApi.rst
  Documentation/ApiOverview/Seo/_MetaTagApi/_ext_localconf_register_manager.php
  Documentation/ApiOverview/Seo/_MetaTagApi/_ext_localconf_register_manager_open_graph.php
  Documentation/ApiOverview/Services/Configuration/RegistrationChanges.rst
  Documentation/ApiOverview/Services/Configuration/_RegistrationChanges/_ext_localconf.php
  Documentation/ApiOverview/Services/Developer/Implementing.rst
  Documentation/ApiOverview/Services/Developer/_Implementing/_ext_localconf.php
  Documentation/ApiOverview/Typo3CoreEngine/Database/Index.rst
  Documentation/ApiOverview/Typo3CoreEngine/Database/_ext_localconf.php
  Documentation/ApiOverview/Xclasses/Index.rst
  Documentation/ApiOverview/Xclasses/_ext_localconf.php
  Documentation/CodingGuidelines/CglPhp/CodingBestPractices/HookNaming.rst
  Documentation/ExtensionArchitecture/BestPractises/ConfigurationFiles.rst
  Documentation/ExtensionArchitecture/BestPractises/_ext_localconf.php
  Documentation/ExtensionArchitecture/FileStructure/ExtLocalconf.rst
  Documentation/ExtensionArchitecture/FileStructure/_ext_localconf.php
  Documentation/ExtensionArchitecture/FileStructure/_ext_localconf_user_tsconfig.php
Labels: backport 12.4

#2920 Unify the ext_tables.php
  Documentation/ApiOverview/Backend/CustomPermissions.rst
  Documentation/ApiOverview/Backend/_CustomPermissions/_ext_tables.php
  Documentation/ApiOverview/Namespaces/Index.rst
  Documentation/ApiOverview/Namespaces/_Modules.php
  Documentation/ApiOverview/Namespaces/_ext_localconf.php
  Documentation/Configuration/UserSettingsConfiguration/Extending.rst
  Documentation/Configuration/UserSettingsConfiguration/_event.js
  Documentation/Configuration/UserSettingsConfiguration/_ext_tables.php
  Documentation/Configuration/UserSettingsConfiguration/_ext_tables_settings.php
  Documentation/ExtensionArchitecture/FileStructure/Configuration/Backend/Index.rst
  Documentation/ExtensionArchitecture/FileStructure/ExtTables.rst
  Documentation/ExtensionArchitecture/FileStructure/_ext_tables.php
  Documentation/ExtensionArchitecture/FileStructure/_ext_tables_allowonstandardpages.php
  Documentation/ExtensionArchitecture/FileStructure/_ext_tables_registerModule.php
  Documentation/ExtensionArchitecture/FileStructure/_ext_tables_scheduler.php
  Documentation/ExtensionArchitecture/HowTo/ExtendingTca/StoringChanges/Index.rst
Labels: backport 12.4

#2934 [TASK] Streamline Events/Core/Html chapter
  Documentation/ApiOverview/Events/Events/Core/Html/BrokenLinkAnalysisEvent.rst
Labels: backport 12.4

#2935 [TASK] Move code snippets into separate files for mail events
  Documentation/ApiOverview/Events/Events/Core/Mail/AfterMailerInitializationEvent.rst
  Documentation/ApiOverview/Events/Events/Core/Mail/AfterMailerSentMessageEvent.rst
  Documentation/ApiOverview/Events/Events/Core/Mail/BeforeMailerSentMessageEvent.rst
  Documentation/ApiOverview/Events/Events/Core/Mail/_AfterMailerInitializationEvent/_MyEventListener.php
  Documentation/ApiOverview/Events/Events/Core/Mail/_AfterMailerInitializationEvent/_Services.yaml
  Documentation/ApiOverview/Events/Events/Core/Mail/_AfterMailerSentMessageEvent/_MyEventListener.php
  Documentation/ApiOverview/Events/Events/Core/Mail/_AfterMailerSentMessageEvent/_Services.yaml
  Documentation/ApiOverview/Events/Events/Core/Mail/_BeforeMailerSentMessageEvent/_MyEventListener.php
  Documentation/ApiOverview/Events/Events/Core/Mail/_BeforeMailerSentMessageEvent/_Services.yaml
Labels: backport 12.4

#2930 [TASK] Streamline Events/Core/DataHandling chapter
  Documentation/ApiOverview/Events/Events/Core/DataHandling/AppendLinkHandlerElementsEvent.rst
  Documentation/ApiOverview/Events/Events/Core/DataHandling/IsTableExcludedFromReferenceIndexEvent.rst
Labels: backport 12.4

#2937 [TASK] Streamline Events/Core/Package chapter
  Documentation/ApiOverview/Events/Events/Core/Package/AfterPackageActivationEvent.rst
  Documentation/ApiOverview/Events/Events/Core/Package/AfterPackageDeactivationEvent.rst
  Documentation/ApiOverview/Events/Events/Core/Package/BeforePackageActivationEvent.rst
  Documentation/ApiOverview/Events/Events/Core/Package/PackagesMayHaveChangedEvent.rst
Labels: backport 12.4

#2928 [TASK] Move code snippets into separate files for bootstrap events
  Documentation/ApiOverview/Events/Events/Core/Core/BootCompletedEvent.rst
  Documentation/ApiOverview/Events/Events/Core/Core/_BootCompletedEvent/_MyEventListener.php
  Documentation/ApiOverview/Events/Events/Core/Core/_BootCompletedEvent/_Services.yaml
Labels: backport 12.4

#2927 [TASK] Revise Events/Core/Configuration chapter
  Documentation/ApiOverview/Events/Events/Core/Configuration/AfterFlexFormDataStructureIdentifierInitializedEvent.rst
  Documentation/ApiOverview/Events/Events/Core/Configuration/AfterFlexFormDataStructureParsedEvent.rst
  Documentation/ApiOverview/Events/Events/Core/Configuration/AfterTcaCompilationEvent.rst
  Documentation/ApiOverview/Events/Events/Core/Configuration/BeforeFlexFormDataStructureIdentifierInitializedEvent.rst
  Documentation/ApiOverview/Events/Events/Core/Configuration/BeforeFlexFormDataStructureParsedEvent.rst
  Documentation/ApiOverview/Events/Events/Core/Configuration/SiteConfigurationBeforeWriteEvent.rst
  Documentation/ApiOverview/Events/Events/Core/Configuration/SiteConfigurationLoadedEvent.rst
  Documentation/ApiOverview/Events/Events/Core/Configuration/_AfterFlexFormDataStructureIdentifierInitializedEvent/_Services.yaml
  Documentation/ApiOverview/Events/Events/Core/Configuration/_SiteConfigurationBeforeWriteEvent/_Services.yaml
  Documentation/ApiOverview/Events/Events/Core/Configuration/_SiteConfigurationLoadedEvent/_Services.yaml
Labels: backport 12.4

#2903 FormEngine chapter Cleanup
  Documentation/ApiOverview/FormEngine/DataCompiling/Index.rst
  Documentation/ApiOverview/FormEngine/DataCompiling/_ext_localconf.php
  Documentation/ApiOverview/FormEngine/DataCompiling/_ext_localconf_disable.php
  Documentation/ApiOverview/FormEngine/Introduction/Index.rst
  Documentation/ApiOverview/FormEngine/Overview/Index.rst
  Documentation/ApiOverview/FormEngine/Overview/_SomeClass.php
  Documentation/ApiOverview/FormEngine/Rendering/Index.rst
  Documentation/ApiOverview/FormEngine/Rendering/_AjaxRoutes.php
  Documentation/ApiOverview/FormEngine/Rendering/_ImportData.js
  Documentation/ApiOverview/FormEngine/Rendering/_ImportDataControl.php
  Documentation/ApiOverview/FormEngine/Rendering/_ImportDataController.php
  Documentation/ApiOverview/FormEngine/Rendering/_InputTextElement.php
  Documentation/ApiOverview/FormEngine/Rendering/_SomeContainer.php
  Documentation/ApiOverview/FormEngine/Rendering/_SomeContainerJavaScript.php
  Documentation/ApiOverview/FormEngine/Rendering/_SomeController.php
  Documentation/ApiOverview/FormEngine/Rendering/_ext_localconf.php
  Documentation/ApiOverview/FormEngine/Rendering/_ext_localconf_fieldcontrol.php
  Documentation/ApiOverview/FormEngine/Rendering/_ext_localconf_flex.php
  Documentation/ApiOverview/FormEngine/Rendering/_ext_localconf_rte.php
  Documentation/ApiOverview/FormEngine/Rendering/_pages.php
  Documentation/ApiOverview/FormEngine/Rendering/_tx_cooltagcloud.php
Labels: backport 11.5, backport 12.4

#2938 [TASK] Fix file name typo
  Documentation/ApiOverview/CachingFramework/Developer/Index.rst
Labels: backport 11.5, backport 12.4

#2929 [TASK] Streamline Events/Core/Database chapter
  Documentation/ApiOverview/Events/Events/Core/Database/AlterTableDefinitionStatementsEvent.rst
Labels: backport 12.4

#2947 [TASK] Streamline Events/Core/Page chapter
  Documentation/ApiOverview/Events/Events/Core/Page/BeforeJavaScriptsRenderingEvent.rst
  Documentation/ApiOverview/Events/Events/Core/Page/BeforeStylesheetsRenderingEvent.rst
Labels: backport 12.4

#2949 [TASK] Streamline Events/Core/Tree chapter
  Documentation/ApiOverview/Events/Events/Core/Tree/ModifyTreeDataEvent.rst
Labels: backport 12.4

#2957 Link connection::lastInsertId() from querybuilder::insert()
  Documentation/ApiOverview/Database/QueryBuilder/Index.rst
Labels: backport 11.5, backport 12.4

#2961 [BUGFIX] Fix typo in namespace
  Documentation/ApiOverview/Events/Events/Setup/AddJavaScriptModulesEvent.rst
Labels: backport 11.5, backport 10.4, backport 12.4

#2967 [TASK] Reference PSR-14 events in Extbase chapter
  Documentation/ExtensionArchitecture/Extbase/Reference/Controller/ActionController.rst
  Documentation/ExtensionArchitecture/Extbase/Reference/Domain/Model.rst
  Documentation/ExtensionArchitecture/Extbase/Reference/Domain/Persistence.rst
Labels: backport 11.5, backport 12.4

#2966 [TASK] Streamline Events/Extbase chapter
  Documentation/ApiOverview/Events/Events/Extbase/Configuration/BeforeFlexFormConfigurationOverrideEvent.rst
  Documentation/ApiOverview/Events/Events/Extbase/Configuration/Index.rst
  Documentation/ApiOverview/Events/Events/Extbase/Index.rst
  Documentation/ApiOverview/Events/Events/Extbase/Mvc/AfterRequestDispatchedEvent.rst
  Documentation/ApiOverview/Events/Events/Extbase/Mvc/BeforeActionCallEvent.rst
  Documentation/ApiOverview/Events/Events/Extbase/Mvc/Index.rst
  Documentation/ApiOverview/Events/Events/Extbase/Persistence/AfterObjectThawedEvent.rst
  Documentation/ApiOverview/Events/Events/Extbase/Persistence/EntityAddedToPersistenceEvent.rst
  Documentation/ApiOverview/Events/Events/Extbase/Persistence/EntityPersistedEvent.rst
  Documentation/ApiOverview/Events/Events/Extbase/Persistence/EntityRemovedFromPersistenceEvent.rst
  Documentation/ApiOverview/Events/Events/Extbase/Persistence/EntityUpdatedInPersistenceEvent.rst
  Documentation/ApiOverview/Events/Events/Extbase/Persistence/Index.rst
  Documentation/ApiOverview/Events/Events/Extbase/Persistence/ModifyQueryBeforeFetchingObjectDataEvent.rst
  Documentation/ApiOverview/Events/Events/Extbase/Persistence/ModifyResultAfterFetchingObjectDataEvent.rst
Labels: backport 12.4

#2965 [FEATURE] Add information about slot replacements and examples
  Documentation/ApiOverview/Events/Events/Core/Package/AfterPackageActivationEvent.rst
  Documentation/ApiOverview/Events/Events/Core/Package/AfterPackageDeactivationEvent.rst
  Documentation/ApiOverview/Events/Events/Core/Package/BeforePackageActivationEvent.rst
  Documentation/ApiOverview/Events/Events/Core/Package/PackagesMayHaveChangedEvent.rst
  Documentation/ApiOverview/Events/Events/Core/Package/_AfterPackageActivationEvent/_MyEventListener.php
  Documentation/ApiOverview/Events/Events/Core/Package/_AfterPackageActivationEvent/_Services.yaml
  Documentation/ApiOverview/Events/Events/ExtensionManager/AfterExtensionDatabaseContentHasImportedEvent.rst
  Documentation/ApiOverview/Events/Events/ExtensionManager/AfterExtensionFilesHaveBeenImportedEvent.rst
  Documentation/ApiOverview/Events/Events/ExtensionManager/AfterExtensionStaticDatabaseContentHasBeenImportedEvent.rst
  Documentation/ApiOverview/Events/Events/ExtensionManager/AvailableActionsForExtensionEvent.rst
Labels: backport 11.5, backport 12.4

#2980 [BUGFIX] Fix rendering warnings
  Documentation/ApiOverview/Events/Hooks/Index.rst
  Documentation/ApiOverview/FormEngine/Rendering/Index.rst
  Documentation/ApiOverview/LinkHandling/LinkBuilder.rst
  Documentation/ApiOverview/Logging/Writers/Index.rst
  Documentation/ApiOverview/Routing/Examples.rst
  Documentation/ApiOverview/Routing/ExtendingRouting.rst
  Documentation/ExtensionArchitecture/Extbase/Reference/FrontendPlugins.rst
Labels: backport 12.4

#2992 [TASK] Avoid calling ModifyLoadedPageTsConfigEvent listeners twice
  Documentation/ApiOverview/Events/Events/Core/Configuration/ModifyLoadedPageTsConfigEvent.rst
  Documentation/ApiOverview/Events/Events/Core/Configuration/_ModifyLoadedPageTsConfigEvent/_Loader.php
  Documentation/ApiOverview/Events/Events/Core/Configuration/_ModifyLoadedPageTsConfigEvent/_Services.yaml
Labels: backport 12.4

#2983 Important: #96332 - Extbase Validators can use dependency injection
  Documentation/ExtensionArchitecture/Extbase/Reference/Domain/Validator.rst
  Documentation/ExtensionArchitecture/Extbase/Reference/Domain/_Validator/_MyCustomValidator.php
  Documentation/ExtensionArchitecture/Extbase/Reference/Domain/_Validator/_MyCustomValidatorv11v12.php
  Documentation/ExtensionArchitecture/Extbase/Reference/Domain/_Validator/_Services.yaml
Labels: backport 11.5, backport 12.4

#2988 [FEATURE] Allow static backdrops for modals
  Documentation/ApiOverview/Backend/JavaScript/Modules/Modals.rst
  Documentation/ApiOverview/Backend/JavaScript/Modules/_Modals/_StaticBackdrop.html
  Documentation/ApiOverview/Backend/JavaScript/Modules/_Modals/_static_backdrop.js
Labels: backport 12.4

#2996 [TASK] Streamline Events/FileList chapter
  Documentation/ApiOverview/Events/Events/Filelist/Index.rst
  Documentation/ApiOverview/Events/Events/Filelist/ModifyEditFileFormDataEvent.rst
  Documentation/ApiOverview/Events/Events/Filelist/ProcessFileListActionsEvent.rst
  Documentation/ApiOverview/Events/Events/Filelist/_ModifyEditFileFormDataEvent/_MyEventListener.php
  Documentation/ApiOverview/Events/Events/Filelist/_ModifyEditFileFormDataEvent/_Services.yaml
  Documentation/ApiOverview/Events/Events/Filelist/_ProcessFileListActionsEvent/_MyEventListener.php
  Documentation/ApiOverview/Events/Events/Filelist/_ProcessFileListActionsEvent/_Services.yaml
  Documentation/ApiOverview/Events/Events/Filelist/_Snippets/_ModifyEditFileFormDataEvent.yaml
  Documentation/ApiOverview/Events/Events/Filelist/_Snippets/_ProcessFileListActionsEvent.yaml
Labels: backport 12.4

#2997 [TASK] Streamline Events/Install chapter
  Documentation/ApiOverview/Events/Events/Install/Index.rst
  Documentation/ApiOverview/Events/Events/Install/ModifyLanguagePackRemoteBaseUrlEvent.rst
  Documentation/ApiOverview/Events/Events/Install/ModifyLanguagePacksEvent.rst
  Documentation/ApiOverview/Events/Events/Install/_ModifyLanguagePacksEvent/_MyEventListener.php
  Documentation/ApiOverview/Events/Events/Install/_ModifyLanguagePacksEvent/_Services.yaml
Labels: backport 12.4

#2999 [TASK] Streamline Events/Linkvalidator chapter
  Documentation/ApiOverview/Events/Events/Linkvalidator/BeforeRecordIsAnalyzedEvent.rst
  Documentation/ApiOverview/Events/Events/Linkvalidator/Index.rst
  Documentation/ApiOverview/Events/Events/Linkvalidator/ModifyValidatorTaskEmailEvent.rst
  Documentation/ApiOverview/Events/Events/Linkvalidator/_BeforeRecordIsAnalyzedEvent/_Services.yaml
  Documentation/ApiOverview/Events/Events/Linkvalidator/_ModifyValidatorTaskEmailEvent/_MyEventListener.php
  Documentation/ApiOverview/Events/Events/Linkvalidator/_ModifyValidatorTaskEmailEvent/_Services.yaml
Labels: backport 12.4

#2998 [TASK] Update typo3/coding-standards to 0.7.1
  Documentation/ApiOverview/Events/Events/Redirects/_SlugRedirectChangeItemCreatedEvent/_PageTypeSource/_MyEventListener.php
  Documentation/ApiOverview/FormEngine/Rendering/_InputTextElement.php
  Documentation/ApiOverview/FormEngine/Rendering/_SomeContainerJavaScript.php
  Documentation/ApiOverview/FormEngine/Rendering/_SomeController.php
  Documentation/Configuration/Yaml/_ExamplePlaceholderProcessor.php
  Documentation/ExtensionArchitecture/Extbase/Reference/_Annotations/_Cascade.php
  Documentation/ExtensionArchitecture/Extbase/Reference/_Annotations/_IgnoreValidation.php
  Documentation/ExtensionArchitecture/Extbase/Reference/_Annotations/_Lazy.php
  Documentation/ExtensionArchitecture/Extbase/Reference/_Annotations/_Multiple.php
  Documentation/ExtensionArchitecture/Extbase/Reference/_Annotations/_Transient.php
  Documentation/ExtensionArchitecture/Extbase/Reference/_Annotations/_Validate.php
  composer.json
Labels: backport 12.4

#2991 [BUGFIX] Provide tag to add JavaScript Modules to importmap in Backen…
  Documentation/ApiOverview/Backend/JavaScript/ES6/Index.rst
  Documentation/ApiOverview/Backend/JavaScript/ES6/_JavaScriptModulesBackendForm.php
Labels: backport 12.4

#2987 [FEATURE] Allow Palettes in 5th parameter of addToAllTCAtypes
  Documentation/ExtensionArchitecture/HowTo/ExtendingTca/Examples/Index.rst
  Documentation/ExtensionArchitecture/HowTo/ExtendingTca/Examples/_fe_users.php
Labels: backport 12.4

#2986 [FEATURE] Get multiple items by common key prefix from local storages
  Documentation/ApiOverview/Backend/JavaScript/Modules/SessionStorageWrapper.rst
  Documentation/ApiOverview/Backend/JavaScript/_SessionStorageWrapper/_storage.js
Labels: backport 12.4

#2984 [!!!][FEATURE] Use LanguageAspect in QuerySettings for Extbase
  Documentation/ExtensionArchitecture/Extbase/Reference/Domain/Repository.rst
  Documentation/ExtensionArchitecture/Extbase/Reference/Domain/_Repository/_LanguageAspect.php
Labels: backport 12.4

#2990 [FEATURE] Introduce native JSON database field type support
  Documentation/ApiOverview/Database/Connection/Index.rst
  Documentation/ApiOverview/Database/Connection/_MyCacheRepository_truncate.php
  Documentation/ApiOverview/Database/Connection/_MyTableRepository_bulkinsert.php
  Documentation/ApiOverview/Database/Connection/_MyTableRepository_count.php
  Documentation/ApiOverview/Database/Connection/_MyTableRepository_delete.php
  Documentation/ApiOverview/Database/Connection/_MyTableRepository_insert.php
  Documentation/ApiOverview/Database/Connection/_MyTableRepository_insert_types.php
  Documentation/ApiOverview/Database/Connection/_MyTableRepository_lastinsertId.php
  Documentation/ApiOverview/Database/Connection/_MyTableRepository_queryBuilder.php
  Documentation/ApiOverview/Database/Connection/_MyTableRepository_select.php
  Documentation/ApiOverview/Database/Connection/_MyTableRepository_update.php
  Documentation/ApiOverview/Database/Connection/_Services.yaml
  Documentation/ApiOverview/Database/Connection/_ext_tables.sql
Labels: backport 12.4

#3008 Fix rendering warnings
  Documentation/ExtensionArchitecture/Extbase/Reference/Domain/Validator.rst
Labels: backport 12.4

#2985 [FEATURE] Support javaScriptModules in FormEngine resultArray
  Documentation/ApiOverview/Backend/ContextualMenu.rst
  Documentation/ApiOverview/Backend/_ContextualMenu/_IncludeJS.html
  Documentation/ApiOverview/FormEngine/Rendering/_ImportDataControl.php
Labels: backport 12.4

#3018 [BUGFIX] Use correct array key in redis example configuration
  Documentation/ApiOverview/CachingFramework/FrontendsBackends/Index.rst
Labels: backport 11.5, backport 12.4

#3017 [BUGFIX] Move code snippet for SessionStorage wrapper
  Documentation/ApiOverview/Backend/JavaScript/Modules/_SessionStorageWrapper/_storage.js
Labels: backport 12.4

#3016 [TASK] Move code snippets for lowlevel events to separate files
  Documentation/ApiOverview/Events/Events/Lowlevel/Index.rst
  Documentation/ApiOverview/Events/Events/Lowlevel/ModifyBlindedConfigurationOptionsEvent.rst
  Documentation/ApiOverview/Events/Events/Lowlevel/_ModifyBlindedConfigurationOptionsEvent/_MyEventListener.php
  Documentation/ApiOverview/Events/Events/Lowlevel/_ModifyBlindedConfigurationOptionsEvent/_Services.yaml
Labels: backport 12.4

#3023 [BUGFIX] Fix typo inside GeneratePublicUrlForResourceEvent.rst
  Documentation/ApiOverview/Events/Events/Core/Resource/GeneratePublicUrlForResourceEvent.rst
Labels: backport 12.4

#3025 [BUGFIX] Remove superfluous character in routing chapter
  Documentation/ApiOverview/Routing/AdvancedRoutingConfiguration.rst
Labels: backport 11.5, backport 12.4

#3028 change wording
  Documentation/ExtensionArchitecture/HowTo/BackendModule/ModuleTypoScript.rst
Labels: backport 11.5, backport 12.4

#3030 [BUGFIX] Corrected IgnoreValidation attribute declaration
  Documentation/ExtensionArchitecture/Extbase/Reference/_Annotations/_IgnoreValidation.php
Labels: backport 12.4

#3032 use the folder Event as in TYPO3 Core
  Documentation/ApiOverview/Events/EventDispatcher/Index.rst
Labels: backport 11.5, backport 12.4

#3035 Remove superfluous word in event listener section
  Documentation/ApiOverview/Events/EventDispatcher/Index.rst
Labels: backport 11.5, backport 12.4
