Repository TYPO3-Documentation/TYPO3CMS-Reference-CoreApi, pull requests merged in 2023-07, with the labels that each got.

#3184 information about DI in scheduler tasks
  Documentation/ApiOverview/DependencyInjection/Index.rst
Labels: backport 11.5, backport 12.4

#3181 Remove default value for sitemap url config
  Documentation/ApiOverview/Seo/XmlSitemap.rst
Labels: backport 11.5, backport 12.4

#3190 Fix path to AjaxRoutes.php in caption
  Documentation/CodeSnippets/Manual/Extension/Configuration/BackendAjaxRoutes.rst.txt
Labels: backport 11.5, backport 12.4

#3193 [TASK] Create multiple file references
  Documentation/ApiOverview/Fal/UsingFal/ExamplesFileFolder.rst
Labels: backport 12.4

#3198 Update ExtensionTesting.rst
  Documentation/Testing/ExtensionTesting.rst
Labels: backport 11.5, backport 12.4

#3197 Add migration section to Icon API
  Documentation/ApiOverview/Icon/Index.rst
Labels: backport 11.5, backport 12.4

#3213 [TASK] Revise the logging processors chapter
  Documentation/ApiOverview/Logging/Processors/Index.rst
Labels: backport 11.5, backport 12.4

#3212 [TASK] Revise the logging model chapter
  Documentation/ApiOverview/Logging/Model/Index.rst
Labels: backport 11.5, backport 12.4

#3211 [TASK] Add page about TYPO3_CONF_VARS|LOG in configuration chapter
  Documentation/Configuration/Typo3ConfVars/LOG.rst
Labels: backport 11.5, backport 12.4

#3207 [BUGFIX] #100162 - Ensure deprecated settings in config.yaml are not changed
  Documentation/ApiOverview/SiteHandling/SiteSettings.rst
Labels: changelog, backport 12.4

#3210 [TASK] Extract code snippets in logger chapter
  Documentation/ApiOverview/Logging/Logger/Index.rst
  Documentation/ApiOverview/Logging/Logger/_MyClassChannel.php
  Documentation/ApiOverview/Logging/Logger/_MyClassChannel2.php
  Documentation/ApiOverview/Logging/Logger/_MyClassLoggerInjection.php
Labels: backport 11.5, backport 12.4

#3225 [FIX] Correct cache flush/warm up includes
  Documentation/ApiOverview/CachingFramework/Index.rst
Labels: backport 12.4

#3214 [TASK] Revise the logging quickstart chapter
  Documentation/ApiOverview/Logging/Quickstart/Index.rst
  Documentation/ApiOverview/Logging/Quickstart/_MyClass.php
Labels: backport 11.5, backport 12.4

#3209 [TASK] Revise the logging configuration
  Documentation/ApiOverview/Logging/Configuration/Index.rst
Labels: backport 11.5, backport 12.4

#3208 [TASK] Revise the logging introduction
  Documentation/ApiOverview/Logging/Index.rst
Labels: backport 11.5, backport 12.4

#3232 [TASK] Link FAL events to the detail page
  Documentation/ApiOverview/Fal/Architecture/Events.rst
Labels: backport 11.5, backport 12.4

#3236 [TASK] Add more invitations to contribute to event examples
  Documentation/ApiOverview/Events/Events/Core/Html/BrokenLinkAnalysisEvent.rst
  Documentation/ApiOverview/Events/Events/Core/Package/AfterPackageDeactivationEvent.rst
  Documentation/ApiOverview/Events/Events/Core/Package/BeforePackageActivationEvent.rst
  Documentation/ApiOverview/Events/Events/Core/Package/PackagesMayHaveChangedEvent.rst
  Documentation/ApiOverview/Events/Events/Core/Page/BeforeJavaScriptsRenderingEvent.rst
  Documentation/ApiOverview/Events/Events/Core/Page/BeforeStylesheetsRenderingEvent.rst
  Documentation/ApiOverview/Events/Events/Core/Resource/AfterFileAddedEvent.rst
  Documentation/ApiOverview/Events/Events/Core/Resource/AfterFileAddedToIndexEvent.rst
  Documentation/ApiOverview/Events/Events/Core/Resource/AfterFileContentsSetEvent.rst
  Documentation/ApiOverview/Events/Events/Core/Resource/AfterFileCopiedEvent.rst
  Documentation/ApiOverview/Events/Events/Core/Resource/AfterFileCreatedEvent.rst
  Documentation/ApiOverview/Events/Events/Core/Resource/AfterFileDeletedEvent.rst
  Documentation/ApiOverview/Events/Events/Core/Resource/AfterFileMarkedAsMissingEvent.rst
  Documentation/ApiOverview/Events/Events/Core/Resource/AfterFileMetaDataCreatedEvent.rst
  Documentation/ApiOverview/Events/Events/Core/Resource/AfterFileMetaDataDeletedEvent.rst
  Documentation/ApiOverview/Events/Events/Core/Resource/AfterFileMetaDataUpdatedEvent.rst
  Documentation/ApiOverview/Events/Events/Core/Resource/AfterFileMovedEvent.rst
  Documentation/ApiOverview/Events/Events/Core/Resource/AfterFileProcessingEvent.rst
  Documentation/ApiOverview/Events/Events/Core/Resource/AfterFileRemovedFromIndexEvent.rst
  Documentation/ApiOverview/Events/Events/Core/Resource/AfterFileRenamedEvent.rst
  Documentation/ApiOverview/Events/Events/Core/Resource/AfterFileReplacedEvent.rst
  Documentation/ApiOverview/Events/Events/Core/Resource/AfterFileUpdatedInIndexEvent.rst
  Documentation/ApiOverview/Events/Events/Core/Resource/AfterFolderAddedEvent.rst
  Documentation/ApiOverview/Events/Events/Core/Resource/AfterFolderCopiedEvent.rst
  Documentation/ApiOverview/Events/Events/Core/Resource/AfterFolderDeletedEvent.rst
  Documentation/ApiOverview/Events/Events/Core/Resource/AfterFolderMovedEvent.rst
  Documentation/ApiOverview/Events/Events/Core/Resource/AfterFolderRenamedEvent.rst
  Documentation/ApiOverview/Events/Events/Core/Resource/AfterResourceStorageInitializationEvent.rst
  Documentation/ApiOverview/Events/Events/Core/Resource/BeforeFileAddedEvent.rst
  Documentation/ApiOverview/Events/Events/Core/Resource/BeforeFileContentsSetEvent.rst
  Documentation/ApiOverview/Events/Events/Core/Resource/BeforeFileCopiedEvent.rst
  Documentation/ApiOverview/Events/Events/Core/Resource/BeforeFileCreatedEvent.rst
  Documentation/ApiOverview/Events/Events/Core/Resource/BeforeFileDeletedEvent.rst
  Documentation/ApiOverview/Events/Events/Core/Resource/BeforeFileMovedEvent.rst
  Documentation/ApiOverview/Events/Events/Core/Resource/BeforeFileProcessingEvent.rst
  Documentation/ApiOverview/Events/Events/Core/Resource/BeforeFileRenamedEvent.rst
  Documentation/ApiOverview/Events/Events/Core/Resource/BeforeFileReplacedEvent.rst
  Documentation/ApiOverview/Events/Events/Core/Resource/BeforeFolderAddedEvent.rst
  Documentation/ApiOverview/Events/Events/Core/Resource/BeforeFolderCopiedEvent.rst
  Documentation/ApiOverview/Events/Events/Core/Resource/BeforeFolderDeletedEvent.rst
  Documentation/ApiOverview/Events/Events/Core/Resource/BeforeFolderMovedEvent.rst
  Documentation/ApiOverview/Events/Events/Core/Resource/BeforeFolderRenamedEvent.rst
  Documentation/ApiOverview/Events/Events/Core/Resource/BeforeResourceStorageInitializationEvent.rst
  Documentation/ApiOverview/Events/Events/Core/Resource/EnrichFileMetaDataEvent.rst
  Documentation/ApiOverview/Events/Events/Core/Resource/GeneratePublicUrlForResourceEvent.rst
  Documentation/ApiOverview/Events/Events/Core/Resource/ModifyIconForResourcePropertiesEvent.rst
  Documentation/ApiOverview/Events/Events/Core/Resource/SanitizeFileNameEvent.rst
  Documentation/ApiOverview/Events/Events/Core/Security/PolicyMutatedEvent.rst
  Documentation/ApiOverview/Events/Events/Core/Tree/ModifyTreeDataEvent.rst
Labels: backport 12.4

#3239 [FEATURE] #100926 - Implement simple log rotation
  Documentation/ApiOverview/Logging/Writers/Index.rst
  Documentation/ApiOverview/Logging/Writers/_additionalRotationFileWriter.php
  Documentation/ApiOverview/Logging/Writers/_additionalRotationFileWriterForDeprecations.php
Labels: changelog

#3233 [TASK] Add hint to UnableToLinkException in AfterLinkIsGeneratedEvent
  Documentation/ApiOverview/Events/Events/Frontend/AfterLinkIsGeneratedEvent.rst
Labels: backport 12.4

#3238 [TASK] Rename header "Logging Framework" to "Logging"
  Documentation/ApiOverview/Logging/Index.rst
Labels: backport 11.5, backport 12.4

#3224 [TASK] Revise the logging logger chapter
  Documentation/ApiOverview/Logging/Logger/Index.rst
Labels: backport 11.5, backport 12.4

#3247 [TASK] change Initialization to Initialisation as in ImportUtility
  Documentation/ExtensionArchitecture/HowTo/CreateNewDistribution.rst
Labels: backport 11.5, backport 12.4

#3252 [TASK] Remove unexplained reference to Wordpress documentation
  Documentation/CodeSnippets/Manual/Core/AssetCollector.rst.txt
Labels: backport 11.5, backport 12.4

#3251 [TASK] Move log() method section before describing the shorthand methods
  Documentation/ApiOverview/Logging/Logger/Index.rst
Labels: backport 11.5, backport 12.4

#3253 [TASK] Revise "Searching for files" chapter
  Documentation/ApiOverview/Fal/UsingFal/ExamplesFileSearch.rst
Labels: backport 11.5, backport 12.4

#3260 [TASK] Remove hint to changelog in logging chapter
  Documentation/ApiOverview/Logging/Logger/Index.rst
  Documentation/ApiOverview/Logging/Quickstart/Index.rst
Labels: backport 12.4

#3254 [TASK] Introduce EXT:add_pwd_policy for additional password policy validators
  Documentation/ApiOverview/PasswordPolicies/Index.rst
Labels: backport 12.4

#3265 [TASK] Use PSR-3 LogLevel
  Documentation/ApiOverview/Deprecation/Index.rst
  Documentation/ApiOverview/Logging/Configuration/Index.rst
  Documentation/ApiOverview/Logging/Logger/Index.rst
  Documentation/ApiOverview/Logging/Model/Index.rst
  Documentation/ApiOverview/Logging/Quickstart/Index.rst
  Documentation/Security/GuidelinesAdministrators/FurtherActions.rst
Labels: backport 12.4

#3268 [TASK] Add Stringable as type for log message
  Documentation/ApiOverview/Logging/Logger/Index.rst
Labels: backport 12.4

#3269 [BUGFIX] Adjust migration section of Icon API
  Documentation/ApiOverview/Icon/Index.rst
Labels: backport 11.5, backport 12.4

#3274 [TASK] Use FQCN for icon providers
  Documentation/ApiOverview/Icon/Index.rst
Labels: backport 12.4

#3276 [TASK] List PHP icon size constants in Icon API chapter
  Documentation/ApiOverview/Icon/Index.rst
Labels: backport 12.4

#3266 [TASK] Revise "Enumerations & bitsets" introduction page
  Documentation/ApiOverview/Enumerations/Index.rst
Labels: backport 11.5, backport 12.4
