Repository TYPO3-Documentation/TYPO3CMS-Reference-CoreApi, pull requests merged in 2023-12, with the labels that each got.

#3751 [FEATURE] #101507 - Add hotkey API to TYPO3 backend
  Documentation/ApiOverview/Backend/JavaScript/HotkeyApi/Index.rst
  Documentation/ApiOverview/Backend/JavaScript/HotkeyApi/_example.js
  Documentation/ApiOverview/Backend/JavaScript/Index.rst
Labels: changelog

#3755 [TASK] Add "abstract classes" as not working with XCLASS
  Documentation/ApiOverview/Xclasses/Index.rst
Labels: backport-required

#3754 [DOCS] Add Services.yaml example for interface injection
  Documentation/ApiOverview/DependencyInjection/Index.rst
  Documentation/ApiOverview/DependencyInjection/_MyController.php
  Documentation/ApiOverview/DependencyInjection/_MySecondController.php
  Documentation/ApiOverview/DependencyInjection/_MyThirdController.php
  Documentation/ApiOverview/DependencyInjection/_ServicesWithInterfaceInjection.yaml
Labels: backport 11.5, backport 12.4

#3760 [BUGFIX] #102607 - Use "da" instead of "dk" for Danish language locale
  Documentation/ApiOverview/SiteHandling/_basics-config.yaml
Labels: changelog, backport 11.5, backport 12.4

#3759 [TASK] Add TypoScript configuration for exception handling
  Documentation/ApiOverview/ErrorAndExceptionHandling/Configuration/Index.rst
Labels: backport 11.5, backport 12.4

#3752 [TASK] #102440 - Merge EXT:t3editor into backend
  Documentation/ApiOverview/CodeEditor/Index.rst
  Documentation/ApiOverview/CodeEditor/_register_addon.php
  Documentation/ApiOverview/CodeEditor/_register_mode.php
  Documentation/Images/ManualScreenshots/CodeEditor/CodeEditor.png
  Documentation/Settings.cfg
Labels: changelog

#3758 [TASK] Add "abstract classes" as not working with XCLASS (#3755)
  Documentation/ApiOverview/Xclasses/Index.rst
Labels: backport 12.4

#3769 [TASK] #102001 - Add request object to canonical tag generation link
  Documentation/ApiOverview/Events/Events/SEO/ModifyUrlForCanonicalTagEvent.rst
  Documentation/CodeSnippets/Events/Seo/ModifyUrlForCanonicalTagEvent.rst.txt
Labels: backport 12.4

#3761 [TASK] #102605 - TSFE->fe_user removed
  Documentation/ApiOverview/TSFE/Index.rst
Labels: changelog

#3768 [FEATURE] #102628 - FE cache information request attribute
  Documentation/ApiOverview/RequestLifeCycle/RequestAttributes/FrontendCacheInstruction.rst
  Documentation/ApiOverview/RequestLifeCycle/RequestAttributes/_FrontendCacheInstruction/_MyEarlyMiddleware.php
  Documentation/ApiOverview/RequestLifeCycle/RequestAttributes/_FrontendCacheInstruction/_MyLaterMiddleware.php
  Documentation/ApiOverview/RequestLifeCycle/Typo3Request.rst
  Documentation/CodeSnippets/Config/Api/Entity.php
  Documentation/CodeSnippets/Manual/Entity/CacheInstruction.rst.txt
Labels: changelog

#3773 [TASK] #101163 - Deprecate class Enumeration
  Documentation/ApiOverview/Enumerations/Enumeration.rst
  Documentation/ApiOverview/Enumerations/_Enumerations/_StateBackedEnum.php
  Documentation/ApiOverview/Enumerations/_Enumerations/_StateExtendingEnumeration.php
Labels: changelog

#3774 [FEATURE] #102631 - Introduce AsController attribute to autoconfigure backend controllers
  Documentation/ExtensionArchitecture/HowTo/BackendModule/CreateModule.rst
  Documentation/ExtensionArchitecture/HowTo/BackendModule/CreateModuleWithExtbase.rst
Labels: changelog, backport 12.4

#3776 [TASK] Clarification of the synchronization cycle
  Documentation/ApiOverview/Localization/TranslationServer/Crowdin/OnlineTranslation.rst
Labels: backport 11.5

#3784 [TASK] Revise "Context API and aspects" chapter
  Documentation/ApiOverview/Context/Index.rst
  Documentation/ApiOverview/Context/_MyController.php
  Documentation/ApiOverview/Context/_MyControllerUsingDateAspect.php
  Documentation/ApiOverview/Context/_MyControllerUsingLanguageAspect.php
  Documentation/ApiOverview/Context/_MyControllerUsingUserAspect.php
  Documentation/ApiOverview/Context/_MyControllerUsingVisibilityAspect.php
  Documentation/ApiOverview/Context/_MyControllerUsingWorkspaceAspect.php
Labels: backport 11.5, backport 12.4

#3788 [TASK] Remove archaeological information from Context API
  Documentation/ApiOverview/Context/Index.rst
Labels: backport 12.4

#3791 [TASK] Add missing "alias" to command
  Documentation/ApiOverview/CommandControllers/Tutorial.rst
Labels: backport 11.5, backport 12.4

#3792 [FEATURE] #100268 - Provide full userdata in password recovery email
  Documentation/ApiOverview/Backend/AccessControl/PasswordReset/Index.rst
  Documentation/ApiOverview/Events/Events/FrontendLogin/SendRecoveryEmailEvent.rst
Labels: changelog

#3793 [FEATURE] #88537 - WebP image format support for Image Processing
  Documentation/Configuration/Typo3ConfVars/GFX.rst
Labels: changelog

#3797 [BUGFIX] Double "->" within code example
  Documentation/ApiOverview/Database/RestrictionBuilder/Index.rst
Labels: backport 11.5, backport 12.4

#3800 [TASK] #87193 - Remove TSFE->sys_language_uid
  Documentation/ApiOverview/TSFE/Index.rst
Labels: changelog, backport 11.5, backport 12.4

#3790 [TASK] #102583 - Remove TypoScriptAspect
  Documentation/ApiOverview/Context/Index.rst
Labels: changelog

#3801 [BUGFIX] #102406 - Properly handle aliases with the AsCommand registration
  Documentation/ApiOverview/CommandControllers/Tutorial.rst
  Documentation/ApiOverview/CommandControllers/_Tutorial/_DoSomethingCommandViaAttribute.php
Labels: changelog, backport 12.4

#3804 [BUGFIX] #102657 - Expose import file in BeforeImportEvent
  Documentation/ApiOverview/Events/Events/Impexp/BeforeImportEvent.rst
  Documentation/CodeSnippets/Events/Impexp/BeforeImportEvent.rst.txt
Labels: backport 12.4

#3803 [TASK] #100885 - Update API reference of UserSession class
  Documentation/ApiOverview/SessionStorageFramework/UserSessionManagement.rst
  Documentation/ApiOverview/SessionStorageFramework/_UserSession.rst.txt
Labels: backport 12.4

#3802 [FEATURE] #102614 - PSR-14 event for modifying GetData result
  Documentation/ApiOverview/Events/Events/Frontend/AfterGetDataResolvedEvent.rst
  Documentation/ApiOverview/Events/Events/Frontend/_AfterGetDataResolvedEvent/_MyEventListener.php
  Documentation/CodeSnippets/Config/Api/Events/EventsFrontend.php
  Documentation/CodeSnippets/Events/Frontend/AfterGetDataResolvedEvent.rst.txt
Labels: changelog

#3794 [TASK] Revise composer.json chapter
  Documentation/ExtensionArchitecture/FileStructure/ComposerJson.rst
  Documentation/ExtensionArchitecture/FileStructure/_ComposerJson/_ExtendedComposer.json
  Documentation/ExtensionArchitecture/FileStructure/_ComposerJson/_ExtensionKey.json
  Documentation/ExtensionArchitecture/FileStructure/_ComposerJson/_MinimalComposer.json
  Documentation/ExtensionArchitecture/FileStructure/_ComposerJson/_ReplaceExtKey.json
  Documentation/ExtensionArchitecture/FileStructure/_ComposerJson/_ReplaceTypo3Ter.json
Labels: backport 11.5, backport 12.4

#3810 [TASK] #102621 - Most TSFE members marked internal or read only
  Documentation/ApiOverview/Assets/Index.rst
  Documentation/ApiOverview/Events/Events/Frontend/AfterCacheableContentIsGeneratedEvent.rst
  Documentation/ApiOverview/TSFE/Index.rst
Labels: changelog

#3814 [TASK] Add hint about automatic publishing of Packagist packages in TER
  Documentation/ExtensionArchitecture/FileStructure/ComposerJson.rst
Labels: backport 11.5, backport 12.4

#3815 [FEATURE] #102279 - Auto create DB fields from TCA for type "select"
  Documentation/ExtensionArchitecture/FileStructure/ExtTablesSql.rst
Labels: changelog

#3819 [TASK] Extensions are installed in vendor folder since v12
  Documentation/ExtensionArchitecture/FileStructure/ComposerJson.rst
Labels: backport 12.4

#3821 [TASK] Link to PageAccessFailureReasons to failure reasons
  Documentation/ApiOverview/SiteHandling/ErrorHandling/WriteCustomErrorHandler.rst
Labels: backport 11.5, backport 12.4

#3822 [BUGFIX] Fix typo in code example for backend module registration
  Documentation/ExtensionArchitecture/HowTo/BackendModule/ModuleConfiguration.rst
Labels: changelog

#3823 [FEATURE] #102624 - Add PSR-14 event for modifying image source collection
  Documentation/ApiOverview/Events/Events/Frontend/ModifyImageSourceCollectionEvent.rst
  Documentation/ApiOverview/Events/Events/Frontend/_ModifyImageSourceCollectionEvent/_MyEventListener.php
  Documentation/CodeSnippets/Config/Api/Events/EventsFrontend.php
  Documentation/CodeSnippets/Events/Frontend/ModifyImageSourceCollectionEvent.rst.txt
Labels: changelog

#3824 [FEATURE] #101396 - Let Extbase handle native enums
  Documentation/ApiOverview/Enumerations/Enumeration.rst
  Documentation/ExtensionArchitecture/Extbase/Reference/Domain/Model.rst
  Documentation/ExtensionArchitecture/Extbase/Reference/Domain/_Model/_Level.php
  Documentation/ExtensionArchitecture/Extbase/Reference/Domain/_Model/_LogEntry.php
Labels: changelog

#3829 [FEATURE] #96806 - PSR-14 event for modifying button bar
  Documentation/ApiOverview/Backend/ButtonComponents.rst
  Documentation/ApiOverview/Events/Events/Backend/ModifyButtonBarEvent.rst
  Documentation/ApiOverview/Events/Events/Backend/_ModifyButtonBarEvent/_MyEventListener.php
  Documentation/ApiOverview/Events/Events/Backend/_ModifyButtonBarEvent/_Services.yaml
  Documentation/CodeSnippets/Config/Api/Events/EventsBackend.php
  Documentation/CodeSnippets/Events/Backend/ModifyButtonBarEvent.rst.txt
Labels: changelog, backport 12.4

#3830 [TASK] Remove references to changelogs in dependency injection chapter
  Documentation/ApiOverview/DependencyInjection/Index.rst
Labels: backport 12.4

#3831 [TASK] Add link to API/CSP from the Security/CSP chapter
  Documentation/Security/GuidelinesAdministrators/ContentSecurityPolicy.rst
Labels: backport 12.4

#3832 [FEATURE] #102715 - New frontend.page.information request attribute
  Documentation/ApiOverview/RequestLifeCycle/RequestAttributes/FrontendPageInformation.rst
  Documentation/ApiOverview/RequestLifeCycle/Typo3Request.rst
  Documentation/ApiOverview/TSFE/Index.rst
Labels: changelog

#3828 [TASK] Streamline "Backend module configuration" chapter
  Documentation/ExtensionArchitecture/HowTo/BackendModule/ModuleConfiguration.rst
  Documentation/ExtensionArchitecture/HowTo/BackendModule/_ModuleConfiguration/_AliasIdentifier.php
  Documentation/ExtensionArchitecture/HowTo/BackendModule/_ModuleConfiguration/_AliasModule.php
  Documentation/ExtensionArchitecture/HowTo/BackendModule/_ModuleConfiguration/_ControllerActions.php
  Documentation/ExtensionArchitecture/HowTo/BackendModule/_ModuleConfiguration/_ModuleData.php
  Documentation/ExtensionArchitecture/HowTo/BackendModule/_ModuleConfiguration/_Registration.php
  Documentation/ExtensionArchitecture/HowTo/BackendModule/_ModuleConfiguration/_Routes.php
  Documentation/Images/ManualScreenshots/Backend/BackendModulesConfiguration.png
Labels: backport 12.4

#3837 [BUGFIX] #102688 - Display inherited module workspace access restriction
  Documentation/ExtensionArchitecture/HowTo/BackendModule/ModuleConfiguration.rst
Labels: changelog, backport 12.4

#3839 [TASK] Streamline TSFE events
  Documentation/ApiOverview/Events/Events/Frontend/AfterPageAndLanguageIsResolvedEvent.rst
  Documentation/ApiOverview/Events/Events/Frontend/AfterPageWithRootLineIsResolvedEvent.rst
  Documentation/ApiOverview/Events/Events/Frontend/BeforePageIsResolvedEvent.rst
Labels: backport 12.4

#3843 Fix backend module registration for a plain (non-extbase) controller
  Documentation/ExtensionArchitecture/HowTo/BackendModule/_ModuleConfiguration/_Registration.php
Labels: backport 12.4

#3844 [BUGFIX] Correct TypoScript example in "Advanced routing configuration"
  Documentation/ApiOverview/Routing/AdvancedRoutingConfiguration.rst
Labels: backport 11.5, backport 12.4
