Repository TYPO3-Documentation/TYPO3CMS-Reference-CoreApi, pull requests merged in 2024-09, with the labels that each got.

#4707 Turn on linenumbers for code snippets
  Documentation/ExtensionArchitecture/Extbase/Reference/FrontendPlugins.rst
Labels: backport 12.4

#4704 Overhaul "What to make public" DI section
  Documentation/ApiOverview/DependencyInjection/Index.rst
Labels: backport 11.5, backport 12.4

#4714 [DOC] Document nested parameters in _arguments
  Documentation/ApiOverview/Routing/AdvancedRoutingConfiguration.rst
Labels: backport 12.4

#4717 [BUGFIX] Add a missing word in custom permissions chapter
  Documentation/ApiOverview/Backend/CustomPermissions.rst
Labels: backport 11.5, backport 12.4

#4723 [TASK] Move content element introduction into main page.
  Documentation/ApiOverview/ContentElements/Index.rst
  Documentation/ApiOverview/ContentElements/Introduction.rst
Labels: backport 12.4

#4729 [TASK] Fix whitespace and codeblocks in Fluid chapter
  Documentation/ApiOverview/Fluid/AdditionalAttributes.rst
  Documentation/ApiOverview/Fluid/DevelopCustomViewhelper.rst
  Documentation/ApiOverview/Fluid/Index.rst
  Documentation/ApiOverview/Fluid/Introduction.rst
  Documentation/ApiOverview/Fluid/Syntax.rst
  Documentation/ApiOverview/Fluid/UsingFluidInTypo3.rst
  Documentation/ApiOverview/Fluid/UsingTypoScriptCObjectViewHelper.rst
  Documentation/ApiOverview/Fluid/_CustomViewHelper/_AbstractTagBasedViewHelper.php
  Documentation/ApiOverview/Fluid/_CustomViewHelper/_GravatarViewHelper13.diff
  Documentation/ApiOverview/Fluid/_CustomViewHelper/_GravatarViewHelper_Initialize.diff
  Documentation/ApiOverview/Fluid/_CustomViewHelper/_GravatarViewHelper_Render.php
  Documentation/ApiOverview/Fluid/_CustomViewHelper/_SomeTemplate.html
  Documentation/ApiOverview/Fluid/_Introduction/_Default.html
  Documentation/ApiOverview/Fluid/_Introduction/_ExtensionDefault.html
  Documentation/ApiOverview/Fluid/_Introduction/_Jumbotron.html
  Documentation/ApiOverview/Fluid/_Introduction/_LayoutExtensionDefault.html
  Documentation/ApiOverview/Fluid/_Introduction/_SomeTemplate.html
  Documentation/ApiOverview/Fluid/_Introduction/_Tags.html
  Documentation/ApiOverview/Fluid/_Introduction/_ThreeColumn.html
  Documentation/ApiOverview/Fluid/_Introduction/_lib.dynamicContent.typoscript
Labels: backport 12.4

#4730 [TASK] Document Reserved variables in Fluid
  Documentation/ApiOverview/Fluid/Syntax.rst
  Documentation/ApiOverview/Fluid/_Syntax/_MyController.diff
  Documentation/ApiOverview/Fluid/_Syntax/_MyTemplate.diff
Labels: backport 12.4

#4725 [TASK] Improve introduction into content elements and plugins
  Documentation/ApiOverview/ContentElements/Index.rst
  Documentation/Images/ManualScreenshots/Backend/content_element_example.png
  Documentation/Images/ManualScreenshots/Backend/plugin_example.png
Labels: backport 12.4

#4726 [TASK] Improve introduction of content elements
  Documentation/ApiOverview/ContentElements/Index.rst
  Documentation/Images/ManualScreenshots/Backend/content_element_on_page.png
Labels: backport 12.4

#4727 [TASK] Improve introduction of plugins
  Documentation/ApiOverview/ContentElements/Index.rst
  Documentation/ApiOverview/ContentElements/_Plugins/_ext_localconf_extbase_plugin.php
  Documentation/ApiOverview/ContentElements/_Plugins/_plugin.typoscript
  Documentation/ApiOverview/ContentElements/_Plugins/_tt_content_extbase_plugin.php
  Documentation/ApiOverview/ContentElements/_Plugins/_tt_content_plugin.php
Labels: backport 12.4

#4736 [BUGFIX] Fix path to include
  Documentation/ApiOverview/ContentElements/Index.rst
Labels: backport 12.4

#4738 [TASK] Add fix and other common aliases to makefile
  Makefile
Labels: backport 12.4

#4746 [TASK] Move linkhandler code snippets to own files.
  Documentation/ApiOverview/LinkHandling/Linkhandler/CustomLinkHandlers.rst
  Documentation/ApiOverview/LinkHandling/Linkhandler/_CustomLinkHandlers/_GitHubLinkHandler.js
  Documentation/ApiOverview/LinkHandling/Linkhandler/_CustomLinkHandlers/_GitHubLinkHandler.php
  Documentation/ApiOverview/LinkHandling/Linkhandler/_CustomLinkHandlers/_page.tsconfig
Labels: backport failed, backport 12.4

#4710 [TASK] Explain Content Security Policy modes
  Documentation/ApiOverview/ContentSecurityPolicy/Index.rst
  Documentation/ApiOverview/ContentSecurityPolicy/_ContentSecurityPolicies_mode_append.php
  Documentation/ApiOverview/ContentSecurityPolicy/_ContentSecurityPolicies_mode_extend.php
  Documentation/ApiOverview/ContentSecurityPolicy/_ContentSecurityPolicies_mode_inherit_again.php
  Documentation/ApiOverview/ContentSecurityPolicy/_ContentSecurityPolicies_mode_inherit_once.php
  Documentation/ApiOverview/ContentSecurityPolicy/_ContentSecurityPolicies_mode_reduce.php
  Documentation/ApiOverview/ContentSecurityPolicy/_ContentSecurityPolicies_mode_remove.php
  Documentation/ApiOverview/ContentSecurityPolicy/_ContentSecurityPolicies_mode_set.php
  Documentation/ApiOverview/ContentSecurityPolicy/_csp_mode_append.yaml
  Documentation/ApiOverview/ContentSecurityPolicy/_csp_mode_extend.yaml
  Documentation/ApiOverview/ContentSecurityPolicy/_csp_mode_inherit_again.yaml
  Documentation/ApiOverview/ContentSecurityPolicy/_csp_mode_inherit_once.yaml
  Documentation/ApiOverview/ContentSecurityPolicy/_csp_mode_reduce.yaml
  Documentation/ApiOverview/ContentSecurityPolicy/_csp_mode_remove.yaml
  Documentation/ApiOverview/ContentSecurityPolicy/_csp_mode_set.yaml
Labels: backport 12.4

#4750 Update _flash-message-immediate-action-demo.js
  Documentation/ApiOverview/FlashMessages/_ES6/_flash-message-immediate-action-demo.js
Labels: backport-required

#4735 [Deprecation] renderStatic() for Fluid ViewHelpers
  Documentation/ApiOverview/Fluid/DevelopCustomViewhelper.rst
  Documentation/ApiOverview/Fluid/_CustomViewHelper/MigrateRenderStatic.diff
  Documentation/ApiOverview/Fluid/_CustomViewHelper/_AbstractTagBasedViewHelper.php
  Documentation/ApiOverview/Fluid/_CustomViewHelper/_GravatarTagBasedViewHelper.php
  Documentation/ApiOverview/Fluid/_CustomViewHelper/_GravatarTagBasedViewHelper2.php
  Documentation/ApiOverview/Fluid/_CustomViewHelper/_GravatarTagBasedViewHelperInvocation.php
  Documentation/ApiOverview/Fluid/_CustomViewHelper/_GravatarTagBasedViewHelper_getContentArgumentName.php
  Documentation/ApiOverview/Fluid/_CustomViewHelper/_GravatarViewHelper.php
  Documentation/ApiOverview/Fluid/_CustomViewHelper/_GravatarViewHelper_Render.php
  Documentation/ApiOverview/Fluid/_CustomViewHelper/_GravatarWithContentElementsViewHelper.php
  Documentation/ApiOverview/Fluid/_CustomViewHelper/_MigrateCompileWithContentArgumentAndRender.diff
  Documentation/ApiOverview/Fluid/_CustomViewHelper/_MigrateRenderStaticInvocation.diff
  Documentation/ApiOverview/Fluid/_CustomViewHelper/_SomeTemplate.html
  Documentation/ApiOverview/Fluid/_CustomViewHelper/_StrtolowerViewHelper.php
Labels: backport 12.4

#4762 [TASK] Remove all .. highlights:: directives
  Documentation/ApiOverview/Fluid/Index.rst
  Documentation/ApiOverview/Fluid/Introduction.rst
  Documentation/ApiOverview/LinkHandling/LinkBrowserApi/Index.rst
  Documentation/ApiOverview/LinkHandling/Linkhandler/Events.rst
  Documentation/ApiOverview/LinkHandling/Linkhandler/Index.rst
  Documentation/ApiOverview/LinkHandling/Linkhandler/PageLinkHandler.rst
  Documentation/ApiOverview/LinkHandling/Linkhandler/RecordLinkHandler.rst
  Documentation/ApiOverview/LockingApi/Index.rst
  Documentation/ApiOverview/RequestLifeCycle/Middlewares.rst
  Documentation/ApiOverview/Seo/CanonicalApi.rst
  Documentation/Security/GuidelinesAdministrators/FileExtensionHandling.rst
Labels: backport 12.4

#4765 Remove unnecessary call_user_func wrapping in TCA override example
  Documentation/ApiOverview/ContentElements/AddingYourOwnContentElements.rst
  Documentation/ApiOverview/ContentElements/_AddingYourOwnContentElements/_tt_content.php
Labels: backport 12.4

#4766 Update CSRFlikeRequestTokenHandling.rst
  Documentation/ApiOverview/Authentication/CSRFlikeRequestTokenHandling.rst
Labels: backport 12.4

#4769 Update CreateNewPageType.rst
  Documentation/ApiOverview/PageTypes/CreateNewPageType.rst
Labels: backport 12.4

#4773 Fix list items for RootlineUtility under "Bad examples" section of utilty classes CGL
  Documentation/CodingGuidelines/PhpArchitecture/StaticMethods.rst
Labels: backport 11.5, backport 12.4

#4775 [FEATURE] #101580 - Introduce Content-Security-Policy-Report-Only handling
  Documentation/ApiOverview/ContentSecurityPolicy/Index.rst
  Documentation/Configuration/Typo3ConfVars/SYS.rst
Labels: backport 12.4

#4777 [CI] Speed up documentation check
  .github/workflows/test-documentation.yml
Labels: backport 11.5, backport 12.4

#4776 [CI] Lint code with PHP 8.4
  .github/workflows/tests.yml
  Build/Scripts/runTests.sh
Labels: backport 12.4

#4787 [TASK] Update link to blog article "Migration to typo3/composer-cms-installers version 4+"
  Documentation/ApiOverview/DirectoryStructure/Index.rst
Labels: backport 11.5, backport 12.4
