Repository TYPO3-Documentation/TYPO3CMS-Reference-CoreApi, pull requests merged in 2024-10, with the labels that each got.

#4797 [TASK] Unify YAML in Content Security Policy examples
  Documentation/ApiOverview/ContentSecurityPolicy/_csp.yaml
  Documentation/ApiOverview/ContentSecurityPolicy/_csp_mode_append.yaml
  Documentation/ApiOverview/ContentSecurityPolicy/_csp_mode_extend.yaml
  Documentation/ApiOverview/ContentSecurityPolicy/_csp_mode_reduce.yaml
  Documentation/ApiOverview/ContentSecurityPolicy/_csp_mode_remove.yaml
  Documentation/ApiOverview/ContentSecurityPolicy/_csp_mode_set.yaml
Labels: backport 12.4

#4796 [FEATURE] #104549 - Disable Content Security Policy for a site
  Documentation/ApiOverview/ContentSecurityPolicy/Index.rst
  Documentation/ApiOverview/ContentSecurityPolicy/_csp_active.yaml
Labels: changelog, backport 12.4

#4802 [TASK] Remove outdated note about removal of Fluid widgets
  Documentation/ApiOverview/Pagination/Index.rst
Labels: content

#4803 [TASK] Extract code snippets into dedicated files
  Documentation/ApiOverview/Pagination/Index.rst
  Documentation/ApiOverview/Pagination/_ArrayPaginatorExampleController.php
  Documentation/ApiOverview/Pagination/_ArrayPaginatorExamplePagination.html
  Documentation/ApiOverview/Pagination/_SlidingWindowExampleController.php
Labels: backport 12.4

#4806 Remove misleading word
  Documentation/ExtensionArchitecture/HowTo/ExtendExtbaseModel/Index.rst
Labels: backport 12.4

#4807 [FEATURE] Create a page about site packages
  Documentation/ApiOverview/ContentElements/ContentElementsWizard.rst
  Documentation/ApiOverview/ContentElements/Index.rst
  Documentation/ApiOverview/Fluid/Introduction.rst
  Documentation/ExtensionArchitecture/HowTo/ExtendExtbaseModel/Index.rst
  Documentation/ExtensionArchitecture/Index.rst
  Documentation/ExtensionArchitecture/SitePackage/Index.rst
  Documentation/ExtensionArchitecture/SitePackage/Introduction.rst
  Documentation/ExtensionArchitecture/Tutorials/Kickstart/Index.rst
  Documentation/ExtensionArchitecture/Tutorials/Kickstart/SitepackageBuilder/Index.rst
Labels: backport 12.4

#4814 Fix non blocking locking example
  Documentation/ApiOverview/LockingApi/Index.rst
Labels: backport-required

#4817 Add anchor to @import syntax
  Documentation/Configuration/TypoScript/Syntax/FileImports/Index.rst
Labels: backport 11.5, backport 12.4

#4816 [TASK] Differnciate from TYPO3 Middelwares
  Documentation/ApiOverview/Database/Middleware/Index.rst
Labels: backport 12.4

#4823 [TASK] Create stub for DTO explanation
  Documentation/ExtensionArchitecture/BestPractises/SoftwareDesignPrinciples.rst
  Documentation/ExtensionArchitecture/BestPractises/_dto.php
Labels: backport 12.4

#4829 Use more common term "quotes"
  Documentation/ApiOverview/SiteHandling/SiteSets.rst
Labels: backport 13.4

#4831 Use FQCN for SetRegistry/SetCollector
  Documentation/ApiOverview/SiteHandling/SiteSets.rst
Labels: backport 13.4

#4830 Remove paragraph from site set TypoScript note
  Documentation/ApiOverview/SiteHandling/SiteSets.rst
Labels: backport 13.4

#4827 [TASK] Deprecate INCLUDE_TYPOSCRIPT syntax
  Documentation/Configuration/TypoScript/Syntax/CodeBlocks/Index.rst
  Documentation/Configuration/TypoScript/Syntax/Conditions/Index.rst
  Documentation/Configuration/TypoScript/Syntax/FileImports/Index.rst
  Documentation/Security/GuidelinesIntegrators/Typoscript.rst
Labels: backport 13.4

#4836 fe_user > fe_users
  Documentation/ApiOverview/ContentElements/Index.rst
Labels: backport 12.4, backport 13.4

#4835 Update Index.rst
  Documentation/ApiOverview/ContentElements/Index.rst
Labels: backport-required, backport 13.4

#4839 Update AddingYourOwnContentElements.rst
  Documentation/ApiOverview/ContentElements/AddingYourOwnContentElements.rst
Labels: backport-required

#4837 Update Index.rst
  Documentation/ApiOverview/ContentElements/Index.rst
Labels: backport-required, backport 13.4

#4859 [BUGFIX] Use internal links for permissions
  Documentation/ApiOverview/Backend/AccessControl/AccessControlOptions/Index.rst
  Documentation/ApiOverview/Backend/AccessControl/OtherOptions/Index.rst
  Documentation/ApiOverview/Categories/Index.rst
  Documentation/ApiOverview/Fal/Administration/Permissions.rst
  Documentation/ApiOverview/Fal/Architecture/Components.rst
Labels: backport 12.4, backport 13.4

#4852 [BUGFIX] Respect string enum specifier in site settings editor
  Documentation/ApiOverview/SiteHandling/SiteSettingDefinitions.rst
  Documentation/ApiOverview/SiteHandling/_Settings/_enum_settings.definitions.yaml
Labels: backport 13.4

#4864 [TASK] Move advanced installation chapters from Getting started
  Documentation/Administration/Index.rst
  Documentation/Administration/Installation/DeployTYPO3.rst
  Documentation/Administration/Installation/Deployer/Index.rst
  Documentation/Administration/Installation/Deployer/_deploy.php
  Documentation/Administration/Installation/EnvironmentConfiguration.rst
  Documentation/Administration/Installation/Environments/_additional-context.php
  Documentation/Administration/Installation/Environments/_additional-native.php
  Documentation/Administration/Installation/Environments/_additional.php
  Documentation/Administration/Installation/Environments/_dotenv-symfony.php
  Documentation/Administration/Installation/Environments/_dotenv-vlucas.php
  Documentation/Administration/Installation/Environments/_environment.php
  Documentation/Administration/Installation/Environments/_example.env
  Documentation/Administration/Installation/Index.rst
  Documentation/Administration/Installation/Install.rst
  Documentation/Administration/Installation/LegacyInstallation.rst
  Documentation/Administration/Installation/Magallanes/Index.rst
  Documentation/Administration/Installation/Magallanes/_mage.yml
  Documentation/Administration/Installation/ProductionSettings.rst
  Documentation/Administration/Installation/ReleaseIntegrity.rst
  Documentation/Administration/Installation/Surf/Index.rst
  Documentation/Administration/Installation/Surf/_MyDeployment.php
  Documentation/Administration/Installation/SystemRequirements/Apache.rst.txt
  Documentation/Administration/Installation/SystemRequirements/Database.rst.txt
  Documentation/Administration/Installation/SystemRequirements/IIS.rst.txt
  Documentation/Administration/Installation/SystemRequirements/Index.rst
  Documentation/Administration/Installation/SystemRequirements/NGINX.rst.txt
  Documentation/Administration/Installation/SystemRequirements/PHP.rst.txt
  Documentation/Administration/Installation/TuneTYPO3.rst
  Documentation/Images/AutomaticScreenshots/QuickInstall/EnableFirstInstall.png
  Documentation/Images/AutomaticScreenshots/QuickInstall/EnableFirstInstall.rst.txt
  Documentation/Images/AutomaticScreenshots/QuickInstall/Step1SystemEnvironment.png
  Documentation/Images/AutomaticScreenshots/QuickInstall/Step1SystemEnvironment.rst.txt
  Documentation/Images/AutomaticScreenshots/QuickInstall/Step2DatabaseConnection.png
  Documentation/Images/AutomaticScreenshots/QuickInstall/Step2DatabaseConnection.rst.txt
  Documentation/Images/AutomaticScreenshots/QuickInstall/Step3ChooseDb.png
  Documentation/Images/AutomaticScreenshots/QuickInstall/Step3ChooseDb.rst.txt
  Documentation/Images/AutomaticScreenshots/QuickInstall/Step4AdminUserSitename.png
  Documentation/Images/AutomaticScreenshots/QuickInstall/Step4AdminUserSitename.rst.txt
  Documentation/Images/AutomaticScreenshots/QuickInstall/Step5LastStep.png
  Documentation/Images/AutomaticScreenshots/QuickInstall/Step5LastStep.rst.txt
  Documentation/Introduction/Index.rst
  Documentation/guides.xml
Labels: backport 12.4, backport 13.4

#4868 [TASK] Drop styleguide for icon search
  Documentation/ApiOverview/Icon/Index.rst
  Documentation/Images/AutomaticScreenshots/Icon/IconProviders.png
  Documentation/Images/AutomaticScreenshots/Icon/IconProviders.rst.txt
Labels: backport 13.4

#4867 [TASK] Set removal version for icon size constants
  Documentation/ApiOverview/Icon/Index.rst
Labels: backport 13.4

#4871 [TASK] #105378 - Remove deprecated icon size handling
  Documentation/ApiOverview/Icon/Index.rst
Labels: changelog

#4872 [BUGFIX] Use IconSize enums instead of deprecated Icon constants
  Documentation/ApiOverview/Events/Events/Backend/_ModifyInlineElementControlsEvent/_MyEventListener.php
  Documentation/ApiOverview/Events/Events/Backend/_ModifyLinkExplanationEvent/_MyEventListener.php
  Documentation/ApiOverview/Events/Events/Backend/_ModifyResultItemInLiveSearchEvent/_MyEventListener.php
Labels: backport 13.4

#4873 [TASK] Replace deprecated AbstractFile constants by FileType enum
  Documentation/ApiOverview/Fal/Architecture/Database.rst
Labels: changelog, backport 13.4

#4877 [TASK] Remove typo3/cms-t3editor from composer.json
  composer.json
Labels: backport 13.4

#4883 [TASK] #105444 - Remove deprecated fluid view related code
  Documentation/ApiOverview/Authentication/CSRFlikeRequestTokenHandling.rst
  Documentation/ApiOverview/Backend/_LoginProvider/_MyLoginProvider.php
  Documentation/ApiOverview/Fluid/UsingFluidInTypo3.rst
  Documentation/ApiOverview/LinkHandling/Linkhandler/CustomLinkHandlers.rst
  Documentation/ApiOverview/SiteHandling/UseSiteInTypoScript.rst
  Documentation/CodeSnippets/Backend/LoginProviderInterface.rst.txt
  Documentation/CodeSnippets/Events/Backend/ModifyPageLayoutOnLoginProviderSelectionEvent.rst.txt
Labels: changelog

#4884 [TASK] #105447 - Remove deprecated GeneralUtility::hmac()
  Documentation/ApiOverview/Fal/UsingFal/ExamplesFileFolder.rst
Labels: changelog

#4874 [TASK] #105384 - Remove deprecated AbstractFile::FILETYPE_* constants
  Documentation/ApiOverview/GlobalValues/Constants/Index.rst
Labels: changelog

#4890 [TASK] Move troubleshooting for administrators chapters from Getting …
  Documentation/Administration/Troubleshooting/Database.rst
  Documentation/Administration/Troubleshooting/Index.rst
  Documentation/Administration/Troubleshooting/PHP.rst
  Documentation/Administration/Troubleshooting/SystemModules.rst
  Documentation/Administration/Troubleshooting/TYPO3.rst
  Documentation/Administration/Troubleshooting/WebServer.rst
  Documentation/Images/AutomaticScreenshots/DebugSettings/ConfigurationPresets.png
  Documentation/Images/AutomaticScreenshots/DebugSettings/ConfigurationPresets.rst.txt
  Documentation/Images/AutomaticScreenshots/DebugSettings/DebugSettings.png
  Documentation/Images/AutomaticScreenshots/DebugSettings/DebugSettings.rst.txt
  Documentation/Images/AutomaticScreenshots/InstallTool/InstallToolPassword.png
  Documentation/Images/AutomaticScreenshots/InstallTool/InstallToolPassword.rst.txt
Labels: backport 13.4

#4887 [BUGFIX] Adjust migration of icons
  Documentation/ApiOverview/Icon/Index.rst
Labels: backport 12.4, backport 13.4

#4878 [TASK] Update ergebnis/composer-normalize to 2.44.0
  composer.json
Labels: backport 12.4, backport 13.4

#4896 [TASK] Add anchors to deployment page
  Documentation/Administration/Installation/DeployTYPO3.rst
Labels: backport 12.4, backport 13.4

#4900 Fix usage of code highlighting
  Documentation/ApiOverview/Fal/Architecture/Database.rst
Labels: backport 12.4, backport 13.4

#4903 [TASK] Added note about mixed setups
  Documentation/ApiOverview/SiteHandling/SiteSets.rst
Labels: backport 13.4

#4885 [TASK] #105445 - Remove deprecated smooth migration for renamed navigation ID
  Documentation/ApiOverview/Backend/BackendModules/ModuleConfiguration/Index.rst
Labels: changelog

#4821 [TASK] Deprecate plugin content element and plugin subtypes (list_type)
  Documentation/ApiOverview/ContentElements/ContentElementsWizard.rst
  Documentation/ApiOverview/ContentElements/CustomBackendPreview.rst
  Documentation/ApiOverview/ContentElements/Index.rst
  Documentation/ApiOverview/ContentElements/MigrationListType.rst
  Documentation/ApiOverview/ContentElements/_Migration/PluginListTypeToCTypeUpdate.php
  Documentation/ApiOverview/ContentElements/_Migration/_ext_localconf.php.diff
  Documentation/ApiOverview/ContentElements/_Migration/_non_extbase_tca.diff
  Documentation/ApiOverview/ContentElements/_Migration/_tca_registration.php.diff
  Documentation/ApiOverview/ContentElements/_Migration/_typoscript.diff
  Documentation/ApiOverview/Database/ExpressionBuilder/_RepositoryWithJunctions.php
  Documentation/ApiOverview/FlexForms/Index.rst
  Documentation/CodeSnippets/Config/ExtensionDevelopment/Extbase.php
  Documentation/CodeSnippets/Extbase/FrontendPlugins/NewContentElementWizard.rst.txt
  Documentation/CodeSnippets/Extbase/Upgrades/ExtbasePluginListTypeToCTypeUpdate.rst.txt
  Documentation/CodeSnippets/FlexForms/Examples/PluginHaikuListRegistration.rst.txt
  Documentation/ExtensionArchitecture/BestPractises/NamingConventions.rst
  Documentation/ExtensionArchitecture/Extbase/Reference/FrontendPlugins.rst
  Documentation/ExtensionArchitecture/Extbase/Reference/_FrontendPlugin/_ext_localconf.php
  Documentation/ExtensionArchitecture/Extbase/Reference/_FrontendPlugin/_ext_localconf_rss.php
  Documentation/ExtensionArchitecture/Extbase/Reference/_FrontendPlugin/_setup.typoscript
  Documentation/ExtensionArchitecture/Extbase/Reference/_FrontendPlugin/_tt_content.php
  Documentation/ExtensionArchitecture/HowTo/FrontendPlugin/Index.rst
  Documentation/Images/ManualScreenshots/Extbase/ListType.png
Labels: backport 13.4

#4909 [TASK] Add anchors to Extbase repository
  Documentation/ExtensionArchitecture/Extbase/Reference/Domain/Repository.rst
Labels: backport 12.4, backport 13.4

#4919 [BUGFIX] Use internal links for Upgrade chapters
  Documentation/ApiOverview/Database/DatabaseUpgrade/Index.rst
  Documentation/ExtensionArchitecture/FileStructure/ComposerJson.rst
  Documentation/ExtensionArchitecture/HowTo/UpdateExtensions/UpdateWizards/Creation.rst
  Documentation/Security/GeneralGuidelines/Index.rst
  Documentation/Security/GuidelinesAdministrators/FileDirectoryPermissions.rst
Labels: backport 12.4, backport 13.4

#4927 [BUGFIX] Adjust links to the new location of TypoScript Guide
  Documentation/Configuration/ConfigurationOverview.rst
  Documentation/Configuration/TypoScript/FrontendTypoScript/Index.rst
  Documentation/Configuration/TypoScript/Index.rst
Labels: backport 12.4, backport 13.4

#4930 [TASK] Use request attribute instead of TSFE in page title API example
  Documentation/ApiOverview/Seo/PageTitleApi.rst
  Documentation/ApiOverview/Seo/_ExampleWebsiteTitle/_WebsiteTitleProvider.php
Labels: backport 13.4

#4925 [BUGFIX] Correct FQCN in page title API example
  Documentation/ApiOverview/Seo/_ExampleWebsiteTitle/_Services.yaml
Labels: backport 12.4, backport 13.4

#4924 Rename "Enumerations" folder to "BitSets"
  Documentation/ApiOverview/BitSets/BitSet.rst
  Documentation/ApiOverview/BitSets/Enumeration.rst
  Documentation/ApiOverview/BitSets/Index.rst
  Documentation/ApiOverview/BitSets/_BitSet/_Permissions.php
  Documentation/ApiOverview/BitSets/_BitSet/_PlainExample.php
  Documentation/ApiOverview/BitSets/_BitSet/_PlainExample2.php
  Documentation/ApiOverview/BitSets/_Enumerations/_LikeWildcard.php
  Documentation/ApiOverview/BitSets/_Enumerations/_SomeClass.php
  Documentation/ApiOverview/BitSets/_Enumerations/_SomeClass2.php
  Documentation/ApiOverview/BitSets/_Enumerations/_SomeClass3.php
  Documentation/ApiOverview/BitSets/_Enumerations/_StateBackedEnum.php
  Documentation/ApiOverview/BitSets/_Enumerations/_StateExtendingEnumeration.php
  Documentation/ApiOverview/BitSets/_Enumerations/_VersionState.php
Labels: backport 12.4, backport 13.4

#4933 [TASK] Remove mentions of TSFE in Bootstrapping and Middlewares chapters
  Documentation/ApiOverview/RequestLifeCycle/Bootstrapping.rst
  Documentation/ApiOverview/RequestLifeCycle/Middlewares.rst
Labels: backport 13.4

#4932 [TASK] Use past for Extbase in middleware mitigation hack
  Documentation/ApiOverview/RequestLifeCycle/Middlewares.rst
Labels: backport 13.4

#4923 Remove unknown `type` in configuration array
  Documentation/ApiOverview/PageTypes/_ext_tables.php
Labels: backport 12.4, backport 13.4

#4913 [!!!][TASK] Remove deprecated EMU addPageTSConfig & addUserTSConfig
  Documentation/Configuration/Typo3ConfVars/BE.rst
  Documentation/ExtensionArchitecture/FileStructure/ExtLocalconf.rst
  Documentation/ExtensionArchitecture/FileStructure/_ext_localconf_user_tsconfig.php
Labels: changelog

#4912 [!!!][TASK] Remove extbase repository magic methods
  Documentation/ExtensionArchitecture/Extbase/Reference/Domain/Repository.rst
Labels: changelog

#4908 [!!!][TASK] Remove fallback of comma-separated list for columnsOnly
  Documentation/ApiOverview/Backend/UriBuilder.rst
Labels: changelog

#4942 [TASK] Prefer "Autoconfigure" attribute over the Services.yaml configuration
  Documentation/ApiOverview/Seo/PageTitleApi.rst
  Documentation/ApiOverview/Seo/_ExampleWebsiteTitle/_Services.yaml
  Documentation/ApiOverview/Seo/_ExampleWebsiteTitle/_WebsiteTitleProvider.php
Labels: backport 13.4

#4907 [!!!][TASK] Remove deprecated <INCLUDE_TYPOSCRIPT:
  Documentation/Configuration/TypoScript/Syntax/FileImports/Index.rst
  Documentation/Security/GuidelinesIntegrators/Typoscript.rst
Labels: changelog

#4915 [!!!][TASK] Remove deprecated DataHandler checkStoredRecords properties
  Documentation/Configuration/Typo3ConfVars/BE.rst
Labels: changelog

#4955 [BUGFIX] fix small typo
  Documentation/ExtensionArchitecture/HowTo/UpdateExtensions/UpdateWizards/Creation.rst
Labels: backport 12.4, backport 13.4

#4953 [BUGFIX] Fix curly brace indentation
  Documentation/CodingGuidelines/CglPhp/PhpSyntaxFormatting.rst
Labels: backport 12.4, backport 13.4

#4947 [TASK] Introduce cards on startpage
  Documentation/ApiOverview/Index.rst
  Documentation/Configuration/TypoScript/Index.rst
  Documentation/Index.rst
Labels: backport 12.4, backport 13.4
