Repository TYPO3-Documentation/TYPO3CMS-Reference-CoreApi, pull requests merged in 2024-07, with the labels that each got.

#4581 [SECURITY] Protect frame GET parameter in tx_cms_showpic eID
  Documentation/Configuration/Typo3ConfVars/SYS.rst
Labels: backport 11.5, backport 12.4

#4587 [TASK] Add example on domain model object type convertion
  Documentation/ExtensionArchitecture/Extbase/Reference/Controller/TypeConverter.rst
Labels: backport 12.4

#4591 [BUGFIX] Adjust link to viewhelper reference
  Documentation/ExtensionArchitecture/HowTo/Localization/Fluid.rst
Labels: backport 12.4

#4595 [TASK] Add tutorial video about Crowdin translation
  Documentation/ApiOverview/Localization/TranslationServer/Crowdin/OnlineTranslation.rst
Labels: backport 11.5, backport 12.4

#4594 explain simple enhancer example
  Documentation/ApiOverview/Routing/AdvancedRoutingConfiguration.rst
Labels: backport 12.4, Follow Up

#4600 [TASK] Improve simple enhancer section
  Documentation/ApiOverview/Routing/AdvancedRoutingConfiguration.rst
  Documentation/ApiOverview/Routing/_AdvancedRoutingConfiguration/_routeEnhancers.yaml
Labels: backport 12.4

#4601 [TASK] Move advanced routing codesnippets to files
  Documentation/ApiOverview/Routing/AdvancedRoutingConfiguration.rst
  Documentation/ApiOverview/Routing/_AdvancedRoutingConfiguration/_AspectPrecedence.yaml
  Documentation/ApiOverview/Routing/_AdvancedRoutingConfiguration/_LocaleModifier.yaml
  Documentation/ApiOverview/Routing/_AdvancedRoutingConfiguration/_MyController.php
  Documentation/ApiOverview/Routing/_AdvancedRoutingConfiguration/_MyCustomEnhancer.php
  Documentation/ApiOverview/Routing/_AdvancedRoutingConfiguration/_NewsPlugin.yaml
  Documentation/ApiOverview/Routing/_AdvancedRoutingConfiguration/_PersistedAliasMapper.yaml
  Documentation/ApiOverview/Routing/_AdvancedRoutingConfiguration/_PersistedPatternMapper.yaml
  Documentation/ApiOverview/Routing/_AdvancedRoutingConfiguration/_StaticRangeMapper.yaml
  Documentation/ApiOverview/Routing/_AdvancedRoutingConfiguration/_StaticValueMapper.yaml
  Documentation/ApiOverview/Routing/_AdvancedRoutingConfiguration/_localeMap.yaml
Labels: backport 12.4

#4606 Use HTML-variant to declare custom viewhelper namespace
  Documentation/ApiOverview/Fluid/DevelopCustomViewhelper.rst
Labels: backport 11.5, backport 12.4

#4598 Improve definition of "frontend plugins"
  Documentation/ExtensionArchitecture/Extbase/Reference/FrontendPlugins.rst
  Documentation/ExtensionArchitecture/HowTo/FrontendPlugin/Index.rst
Labels: backport 11.5, backport 12.4

#4618 Update example for "Reuse prepared statement"
  Documentation/ApiOverview/Database/Statement/Index.rst
Labels: backport 11.5, backport 12.4

#4623 Explain `executeUpdate()` return value
  Documentation/ExtensionArchitecture/HowTo/UpdateExtensions/UpdateWizards/Creation.rst
  Documentation/ExtensionArchitecture/HowTo/UpdateExtensions/UpdateWizards/_ExampleUpgradeWizard.php
Labels: backport 11.5, backport 12.4

#4621 [BUGFIX] Document CreateModule - include some code snippets from EXT:example, setDocHeader corrected
  Documentation/CodeSnippets/Config/Api/BackendApi.php
  Documentation/CodeSnippets/Extbase/Configuration/PluginSettings.rst.txt
  Documentation/CodeSnippets/Extbase/Controllers/ForwardAction.rst.txt
  Documentation/ExtensionArchitecture/HowTo/BackendModule/CreateModule.rst
  Documentation/ExtensionArchitecture/HowTo/BackendModule/_ModuleConfiguration/_AdminModuleControllerConstruct.rst.txt
  Documentation/ExtensionArchitecture/HowTo/BackendModule/_ModuleConfiguration/_AdminModuleControllerDebugAction.rst.txt
  Documentation/ExtensionArchitecture/HowTo/BackendModule/_ModuleConfiguration/_AdminModuleControllerHandleRequest.rst.txt
  Documentation/ExtensionArchitecture/HowTo/BackendModule/_ModuleConfiguration/_AdminModuleControllerSetUpDocHeader.rst.txt
  Documentation/ExtensionArchitecture/HowTo/BackendModule/_ModuleConfiguration/_DebugHtml.rst.txt
Labels: backport 12.4

#4627 [DOC] Clarify dynamic variable example
  Documentation/ApiOverview/Fluid/Syntax.rst
Labels: backport 11.5, backport 12.4

#4636 Update _CreatingFileReference.php
  Documentation/ApiOverview/Fal/UsingFal/_ExamplesFileFolder/_CreatingFileReference.php
Labels: backport 12.4

#4642 [BUGFIX] correct namespace of Connection
  Documentation/ApiOverview/Database/Configuration/Index.rst
Labels: backport 11.5, backport 12.4

#4637 Use php-short for Interface
  Documentation/CodingGuidelines/CodingBestPractices/Singletons.rst
Labels: backport 11.5, backport 12.4
