Repository TYPO3-Documentation/TYPO3CMS-Reference-CoreApi, pull requests merged in 2024-11, with the labels that each got.

#4966 Fix CSP `remove` mutation example result
  Documentation/ApiOverview/ContentSecurityPolicy/Index.rst
Labels: backport 12.4, backport 13.4

#4952 [TASK] Avoid TSFE in Extbase chapter
  Documentation/ExtensionArchitecture/Extbase/Index.rst
Labels: backport 13.4

#4951 [TASK] Avoid TSFE in Workspaces chapter
  Documentation/ApiOverview/Workspaces/Index.rst
Labels: backport 13.4

#4950 [TASK] Avoid TSFE in Context chapter
  Documentation/ApiOverview/Context/Index.rst
Labels: backport 13.4

#4949 [TASK] #105426 - Remove deprecated class Enumeration
  Documentation/ApiOverview/BitSets/BitSet.rst
  Documentation/ApiOverview/BitSets/Enumeration.rst
  Documentation/ApiOverview/BitSets/Index.rst
  Documentation/ApiOverview/BitSets/_Enumerations/_LikeWildcard.php
  Documentation/ApiOverview/BitSets/_Enumerations/_SomeClass.php
  Documentation/ApiOverview/BitSets/_Enumerations/_SomeClass2.php
  Documentation/ApiOverview/BitSets/_Enumerations/_SomeClass3.php
  Documentation/ApiOverview/BitSets/_Enumerations/_VersionState.php
Labels: changelog

#4948 [TASK] Overhaul migrate to Composer documentation
  Documentation/Administration/Upgrade/MigrateToComposer/MigrationSteps.rst
Labels: backport 12.4, backport 13.4

#4963 [FEATURE] #102422 - Introduce CacheDataCollector API
  Documentation/ApiOverview/CachingFramework/Architecture/Index.rst
  Documentation/ApiOverview/CachingFramework/Developer/Index.rst
  Documentation/ApiOverview/RequestLifeCycle/RequestAttributes/FrontendCacheCollector.rst
  Documentation/ApiOverview/RequestLifeCycle/Typo3Request.rst
  Documentation/CodeSnippets/Config/Api/All.php
  Documentation/CodeSnippets/Config/Api/Cache.php
  Documentation/CodeSnippets/Manual/Cache/CacheDataCollector.rst.txt
Labels: changelog, backport 13.4

#4914 [!!!][TASK] Activate setRequest() in PageTitleProviderInterface
  Documentation/ApiOverview/Seo/_ExampleWebsiteTitle/_WebsiteTitleProvider.php
Labels: changelog, backport 13.4

#4980 add ConfigTree to the example
  Documentation/ApiOverview/Events/Events/Frontend/ModifyTypoScriptConfigEvent.rst
Labels: backport 13.4

#4978 no suffix EventListener but Listener
  Documentation/ApiOverview/Events/EventDispatcher/Index.rst
Labels: backport 12.4, backport 13.4

#4985 Add anchors to headlines
  Documentation/Security/GuidelinesIntegrators/Typoscript.rst
Labels: backport 12.4, backport 13.4

#4984 [TASK] Explain UriBuilder usage in Extbase ViewHelpers
  Documentation/ExtensionArchitecture/Extbase/Reference/UriBuilder.rst
  Documentation/ExtensionArchitecture/Extbase/Reference/_UriBuilder/_MyLinkViewHelper.php
Labels: enhancement, backport 12.4, backport 13.4

#4990 Fix missing reference to Table properties (ctrl) in "Model" chapter of the Extbase "Tea" extension tutorial
  Documentation/ExtensionArchitecture/Tutorials/Tea/Model.rst
Labels: backport 12.4, backport 13.4

#4994 [TASK] Move legacy Extension installation chapter from Getting started
  Documentation/Administration/Installation/Index.rst
  Documentation/Administration/Installation/LegacyExtensionInstallation.rst
  Documentation/ExtensionArchitecture/HowTo/ExtensionManagement.rst
  Documentation/Images/AutomaticScreenshots/ExtensionManager/UninstallExtension.png
  Documentation/Images/AutomaticScreenshots/ExtensionManager/UninstallExtension.rst.txt
Labels: backport 12.4, backport 13.4

#5000 Fix inline html markup in Context-sensitive menus
  Documentation/ApiOverview/Backend/ContextualMenu.rst
Labels: backport 13.4

#4977 Implement documentation about ApplicationContext #4906
  Documentation/ApiOverview/Environment/Index.rst
  Documentation/ApiOverview/RequestLifeCycle/Bootstrapping.rst
  Documentation/Configuration/ApplicationContext.rst
  Documentation/Configuration/Index.rst
  Documentation/Configuration/_CodeSnippets/ApplicationContext/SunnyProducts.php
Labels: backport 13.4

#5006 [TASK] Add link to felogin error redirect handler
  Documentation/ApiOverview/SiteHandling/ErrorHandling/WriteCustomErrorHandler.rst
Labels: backport 12.4, backport 13.4

#5007 [TASK] Mention FQN of TYPO3\CMS\Core\Page\PageRenderer
  Documentation/ApiOverview/Seo/MetaTagApi.rst
Labels: backport 12.4, backport 13.4

#5004 [TASK] Adjust sentence in TYPO3_CONF_VARS['SYS']['phpTimeZone']
  Documentation/Configuration/Typo3ConfVars/SYS.rst
Labels: backport 12.4, backport 13.4

#4991 Drop the extraneous "Product" namespace from the model in the Extbase "Tea" extension tutorial
  Documentation/CodeSnippets/Tutorials/Tea/Classes/Domain/Model/TeaImage.rst.txt
  Documentation/CodeSnippets/Tutorials/Tea/Classes/Domain/Model/TeaProperties.rst.txt
  Documentation/CodeSnippets/Tutorials/Tea/Classes/Domain/Model/TeaTitle.rst.txt
  Documentation/CodeSnippets/Tutorials/Tea/Configuration/TCA/TeaColumnImage.rst.txt
  Documentation/CodeSnippets/Tutorials/Tea/Configuration/TCA/TeaColumnTitle.rst.txt
  Documentation/CodeSnippets/Tutorials/Tea/Configuration/TCA/TeaCtrl.rst.txt
  Documentation/CodeSnippets/Tutorials/Tea/Configuration/TCA/TeaTypes.rst.txt
  Documentation/CodeSnippets/Tutorials/Tea/ExtTablesSql.rst.txt
  Documentation/ExtensionArchitecture/Tutorials/Tea/Model.rst
Labels: backport 13.4

#4999 Fix typo in configuation of DataHandler/Database.rst #4998
  Documentation/ApiOverview/DataHandler/Database/Index.rst
Labels: backport 12.4, backport 13.4

#5020 [TASK] Mention how to target extbase controller actions
  Documentation/ApiOverview/Backend/BackendRouting.rst
Labels: backport 12.4, backport 13.4

#5018 Replace references to removed add() method
  Documentation/ApiOverview/Database/QueryBuilder/Index.rst
Labels: backport 13.4

#5019 [TASK] Update nginx webserver configuration for TYPO3 13
  Documentation/Administration/Installation/SystemRequirements/NGINX.rst.txt
Labels: backport 13.4

#5030 Set core requirement to 13.4
  Documentation/ExtensionArchitecture/FileStructure/_ComposerJson/_MinimalComposer.json
Labels: backport 13.4

#5033 Correction of version numbers in ext_emconf
  Documentation/ExtensionArchitecture/FileStructure/ExtEmconf.rst
Labels: backport 13.4

#5032 [BUGFIX] Use the same variable name across the example
  Documentation/ApiOverview/DatabaseRecords/_CodeSnippets/_FluidUsage.html
Labels: backport 13.4

#5039 [!!!][TASK] Remove deprecated class DuplicationBehavior
  Documentation/ExtensionArchitecture/Extbase/Reference/_FileUpload/_ApiUpload.php
Labels: changelog, backport 13.4

#5036 [!!!][TASK] Remove legacy BE entry point handling #1147
  Documentation/ApiOverview/Autoloading/Index.rst
  Documentation/ApiOverview/DirectoryStructure/Index.rst
  Documentation/ApiOverview/DirectoryStructure/LegacyInstallations.rst
  Documentation/ApiOverview/RequestLifeCycle/Bootstrapping.rst
  Documentation/CodingGuidelines/CodingBestPractices/NamedArguments.rst
  Documentation/Configuration/BackendEntryPoint/Index.rst
Labels: changelog

#5037 [!!!][TASK] Remove deprecated fluid RenderingContext request get&set
  Documentation/ApiOverview/RequestLifeCycle/Typo3Request.rst
  Documentation/ApiOverview/RequestLifeCycle/_CodeSnippets/_ViewHelperV12.php
  Documentation/ExtensionArchitecture/Extbase/Reference/_UriBuilder/_MyLinkViewHelper.php
Labels: changelog

#5044 [BUGFIX] Add plugin to default Plugins group
  Documentation/ApiOverview/ContentElements/_AddingYourOwnContentElements/_tt_content_register_plugin.php
Labels: backport 13.4

#5046 [TASK] Correct removed class alias (Controller vs. AsController)
  Documentation/ExtensionArchitecture/HowTo/BackendModule/CreateModuleWithExtbase.rst
Labels: changelog

#5052 [TASK] Clarify usage of typo3/coding-standards
  Documentation/Testing/ProjectTesting.rst
Labels: backport 13.4

#5034 [!!!][TASK] Remove deprecated plugin and sub types functionality
  Documentation/ApiOverview/ContentElements/ContentElementsWizard.rst
  Documentation/ApiOverview/ContentElements/Index.rst
  Documentation/ApiOverview/ContentElements/_AddingYourOwnContentElements/_tt_content_content_element_group.php
  Documentation/ApiOverview/ContentElements/_AddingYourOwnContentElements/_tt_content_plugin.php
  Documentation/ApiOverview/ContentElements/_Migration/_non_extbase_tca.diff
  Documentation/ExtensionArchitecture/BestPractises/NamingConventions.rst
  Documentation/ExtensionArchitecture/BestPractises/_snippets/_tt_content_plugin_register.php
  Documentation/ExtensionArchitecture/Extbase/Reference/Controller/ActionController.rst
  Documentation/ExtensionArchitecture/Extbase/Reference/FrontendPlugins.rst
Labels: changelog

#5057 [TASK] Update name of Slack channel for the TYPO3 localization team
  Documentation/ApiOverview/Localization/TranslationServer/Crowdin/ExtensionIntegration.rst
  Documentation/ApiOverview/Localization/TranslationServer/Crowdin/Faq.rst
Labels: backport 12.4, backport 13.4

#5062 [TASK] Hint using multiple join conditions
  Documentation/ApiOverview/Database/QueryBuilder/Index.rst
Labels: backport 12.4, backport 13.4

#5059 Update ExtensionIntegration.rst
  Documentation/ApiOverview/Localization/TranslationServer/Crowdin/ExtensionIntegration.rst
Labels: backport 12.4, backport 13.4

#5067 [TASK] Replace deprecated card syntax
  Documentation/Administration/Upgrade/Major/Index.rst
Labels: backport 12.4, backport 13.4

#5074 [TASK] Replace links to tsconfig reference
  Documentation/ApiOverview/Authentication/MultiFactorAuthentication.rst
  Documentation/ApiOverview/Backend/AccessControl/AccessControlOptions/Index.rst
  Documentation/ApiOverview/Backend/AccessControl/MoreAboutFileMounts/Index.rst
  Documentation/ApiOverview/Backend/BackendLayout.rst
  Documentation/ApiOverview/Backend/BackendModules/Index.rst
  Documentation/ApiOverview/Backend/ContextualMenu.rst
  Documentation/ApiOverview/CachingFramework/Architecture/Index.rst
  Documentation/ApiOverview/ContentElements/ContentElementsWizard.rst
  Documentation/ApiOverview/ContentElements/CustomBackendPreview.rst
  Documentation/ApiOverview/ContentElements/Index.rst
  Documentation/ApiOverview/DataHandler/Database/Index.rst
  Documentation/ApiOverview/DataHandler/UsingDataHandler/Index.rst
  Documentation/ApiOverview/Debugging/Index.rst
  Documentation/ApiOverview/Events/Events/Backend/AfterPageTreeItemsPreparedEvent.rst
  Documentation/ApiOverview/Events/Events/Backend/BeforeRecordDownloadPresetsAreDisplayedEvent.rst
  Documentation/ApiOverview/Events/Events/Backend/ModifyNewContentElementWizardItemsEvent.rst
  Documentation/ApiOverview/Events/Events/Core/Configuration/ModifyLoadedPageTsConfigEvent.rst
  Documentation/ApiOverview/Events/Events/Core/TypoScript/BeforeLoadedPageTsConfigEvent.rst
  Documentation/ApiOverview/Events/Events/Core/TypoScript/BeforeLoadedUserTsConfigEvent.rst
  Documentation/ApiOverview/Events/Events/Redirects/ModifyRedirectManagementControllerViewDataEvent.rst
  Documentation/ApiOverview/Fal/Administration/Permissions.rst
  Documentation/ApiOverview/FlexForms/Index.rst
  Documentation/ApiOverview/FormEngine/Index.rst
  Documentation/ApiOverview/LinkHandling/Configuration.rst
  Documentation/ApiOverview/PageTypes/CreateNewPageType.rst
  Documentation/ApiOverview/Rte/Transformations/Introduction.rst
  Documentation/ApiOverview/Rte/Transformations/Overview.rst
  Documentation/ApiOverview/SiteHandling/AddLanguages.rst
  Documentation/ApiOverview/SiteHandling/SiteSets.rst
  Documentation/ApiOverview/SiteHandling/SiteSettings.rst
  Documentation/ApiOverview/SymfonyExpressionLanguage/Index.rst
  Documentation/CodingGuidelines/CglTsConfig.rst
  Documentation/Configuration/ConfigurationOverview.rst
  Documentation/Configuration/Index.rst
  Documentation/Configuration/Typo3ConfVars/BE.rst
  Documentation/Configuration/TypoScript/Index.rst
  Documentation/Configuration/TypoScript/TSconfig/Index.rst
  Documentation/ExtensionArchitecture/Extbase/Reference/Caching.rst
  Documentation/ExtensionArchitecture/FileStructure/Configuration/PageTsconfig.rst
  Documentation/ExtensionArchitecture/FileStructure/Configuration/TsConfig/Index.rst
  Documentation/ExtensionArchitecture/FileStructure/Configuration/UserTsconfig.rst
  Documentation/ExtensionArchitecture/Tutorials/Tea/DirectoryStructure.rst
  Documentation/Security/GuidelinesIntegrators/ContentElements.rst
Labels: backport 12.4, backport 13.4

#5077 [TASK] Add information regarding spelling
  Documentation/ApiOverview/Localization/Introduction.rst
  Documentation/ApiOverview/Localization/TranslationServer/Crowdin/OnlineTranslation.rst
Labels: backport 12.4, backport 13.4

#5076 [TASK] Add identifier for usage with page-content dataprocessor
  Documentation/ApiOverview/Backend/BackendLayout.rst
Labels: backport 13.4

#5063 [TASK] Add chapter to FAQ regarding Crowdin configuration filename
  Documentation/ApiOverview/Localization/TranslationServer/Crowdin/Faq.rst
Labels: backport 12.4, backport 13.4

#5073 [!!!][TASK] Remove deprecated methods in TypoScriptFrontendController
  Documentation/ApiOverview/DataHandler/Database/Index.rst
Labels: backport 13.4

#5056 [TASK] Add section about 'htaccess', also for upgrades
  Documentation/Administration/Installation/SystemRequirements/Apache.rst.txt
  Documentation/Administration/Upgrade/Major/PostupgradeTasks/BackendTranslations.rst.txt
  Documentation/Administration/Upgrade/Major/PostupgradeTasks/ClearCaches.rst.txt
  Documentation/Administration/Upgrade/Major/PostupgradeTasks/DatabaseAnalyser.rst.txt
  Documentation/Administration/Upgrade/Major/PostupgradeTasks/Index.rst
  Documentation/Administration/Upgrade/Major/PostupgradeTasks/UpgradeWizard.rst.txt
  Documentation/Administration/Upgrade/Major/PostupgradeTasks/UserSettings.rst.txt
  Documentation/Administration/Upgrade/Major/PostupgradeTasks/WebserverConfiguration.rst.txt
  Documentation/Security/GuidelinesAdministrators/RestrictAccessToFiles.rst
Labels: backport 12.4, backport 13.4

#5089 [TASK] Make introduction quick and short
  Documentation/ApiOverview/SystemOverview/Index.rst
  Documentation/Introduction/Index.rst
Labels: backport 12.4, backport 13.4

#5094 Link sitepackage in directory structure chapter
  Documentation/ApiOverview/DirectoryStructure/Index.rst
Labels: backport 12.4, backport 13.4

#5093 Add anchor to backend debug mode
  Documentation/ApiOverview/Debugging/Index.rst
Labels: backport 12.4, backport 13.4

#5100 Use getRecordType() in PageContentPreviewRenderingEvent example
  Documentation/ApiOverview/Events/Events/Backend/_PageContentPreviewRenderingEvent/_MyEventListener.php
Labels: backport 13.4
