Repository TYPO3-Documentation/TYPO3CMS-Reference-CoreApi, pull requests merged in 2024-04, with the labels that each got.

#4240 [TASK] Update code snippets
  Documentation/CodeSnippets/FlexForms/Examples/PluginHaikuList.rst.txt
Labels: backport 11.5, backport 12.4

#4244 [TASK] Add link on how to override backend templates
  Documentation/ExtensionArchitecture/HowTo/BackendModule/Index.rst
Labels: backport 12.4

#4245 [FEATURE] #87889 - Make backend URL configurable
  Documentation/Configuration/BackendEntryPoint/Index.rst
  Documentation/Configuration/Index.rst
  Documentation/Configuration/Typo3ConfVars/BE.rst
  Documentation/Images/ManualScreenshots/AdminTools/ConfigureEntryPoint.png
Labels: changelog

#4237 [TASK] Add references to "DataHandler basics / Command keywords" section
  Documentation/ApiOverview/DataHandler/Database/Index.rst
Labels: content, backport 11.5, backport 12.4

#4259 replace array() With [ ] Square Brackets
  Documentation/ApiOverview/ErrorAndExceptionHandling/Examples/Index.rst
Labels: backport 11.5, backport 12.4

#4263 [TASK] Use dependency injection in examples of "DataHandler basics" chapter
  Documentation/ApiOverview/DataHandler/Database/Index.rst
  Documentation/ApiOverview/DataHandler/Database/_BasicUsage.php
  Documentation/ApiOverview/DataHandler/Database/_basic_usage.php
Labels: content, backport 11.5, backport 12.4

#4260 [TASK] Use dependency injection in examples of "Using DataHandler" chapter
  Documentation/ApiOverview/DataHandler/UsingDataHandler/Index.rst
  Documentation/ApiOverview/DataHandler/UsingDataHandler/_ClearCache.php
  Documentation/ApiOverview/DataHandler/UsingDataHandler/_ErrorHandling.php
  Documentation/ApiOverview/DataHandler/UsingDataHandler/_ExecuteCommands.php
  Documentation/ApiOverview/DataHandler/UsingDataHandler/_SubmitComplexData.php
  Documentation/ApiOverview/DataHandler/UsingDataHandler/_SubmitData.php
  Documentation/ApiOverview/DataHandler/UsingDataHandler/_UseAlternativeUser.php
Labels: content, backport 11.5, backport 12.4

#4273 [TASK] Use confvals for DataHandler's data array keywords
  Documentation/ApiOverview/DataHandler/Database/Index.rst
Labels: content, backport 11.5, backport 12.4

#4271 [BUGFIX] Add missing use statement in DataHandler example
  Documentation/ApiOverview/DataHandler/Database/Index.rst
  Documentation/ApiOverview/DataHandler/Database/_BasicUsage.php
Labels: backport 12.4

#4280 [BUGFIX] Correct highlighted line in FlexForm example
  Documentation/CodeSnippets/Config/ExtensionDevelopment/Extbase.php
  Documentation/CodeSnippets/Extbase/Configuration/PluginSettings.rst.txt
Labels: backport 12.4

#4278 [TASK] Streamline DataHandler's "Clear cache" section
  Documentation/ApiOverview/DataHandler/Database/Index.rst
Labels: backport 11.5, backport 12.4

#4279 [TASK] Adjust addCacheTags() example
  Documentation/ApiOverview/DataHandler/Database/_SomeController.php
Labels: backport 11.5, backport 12.4

#4277 [TASK] Use references in DataHandler's data array section
  Documentation/ApiOverview/DataHandler/Database/Index.rst
Labels: backport 11.5, backport 12.4

#4288 [TASK] Use confvals for DataHandler's flags section
  Documentation/ApiOverview/DataHandler/Database/Index.rst
Labels: content, backport 11.5, backport 12.4

#4258 [TASK] #103496 - Use ISO 8601 format for date rendering
  Documentation/Configuration/Typo3ConfVars/SYS.rst
Labels: changelog, backport 12.4

#4291 Update Index.rst
  Documentation/ApiOverview/ErrorAndExceptionHandling/Examples/Index.rst
Labels: backport 11.5, backport 12.4

#4293 Add example for site configuration custom field comparison
  Documentation/ApiOverview/SiteHandling/UseSiteInConditions.rst
Labels: backport 11.5, backport 12.4

#4292 Update Index.rst
  Documentation/ApiOverview/ErrorAndExceptionHandling/Extending/Index.rst
Labels: backport 11.5, backport 12.4

#4247 [TASK] Remove unneeded 'horizbuttons' reference
  Documentation/ApiOverview/DataFormats/Index.rst
  Documentation/ApiOverview/FlexForms/Index.rst
  Documentation/ApiOverview/FlexForms/T3datastructure/Elements/Index.rst
  Documentation/ApiOverview/FlexForms/T3datastructure/Index.rst
  Documentation/ApiOverview/FlexForms/T3datastructure/Parsing/Index.rst
  Documentation/ApiOverview/FlexForms/T3datastructure/SheetReferences/Index.rst
Labels: backport 11.5, backport 12.4

#4308 Update RegisterToplevelModuleWithExtbase.rst
  Documentation/ExtensionArchitecture/HowTo/BackendModule/BackendModulesWithExtbase/RegisterToplevelModuleWithExtbase.rst
Labels: backport-required, backport 12.4

#4304 [TASK] Streamline TypoScript coding guidelines chapter
  Documentation/CodingGuidelines/CglTypoScript/Index.rst
Labels: backport 12.4

#4314 [TASK] Discard setup information for old translation server
  Documentation/ApiOverview/Localization/TranslationServer/Crowdin/ExtensionIntegration.rst
Labels: backport 11.5, backport 12.4

#4313 [FEATURE] Add section about disabling pushing changes from Crowdin
  Documentation/ApiOverview/Localization/TranslationServer/Crowdin/Faq.rst
Labels: backport 11.5, backport 12.4

#4311 [TASK] Add information about DI and Caches
  Documentation/ExtensionArchitecture/HowTo/UpdateExtensions/UpdateWizards/Creation.rst
  Documentation/ExtensionArchitecture/HowTo/UpdateExtensions/UpdateWizards/_tagUpgradeWizard.yaml
Labels: backport 12.4

#4325 [TASK] Drop two outdated notes in MFA chapter
  Documentation/ApiOverview/Authentication/MultiFactorAuthentication.rst
Labels: content outdated, backport 11.5, backport 12.4

#4324 [TASK] Add link to "How to use DI in XCLASSed class" blog article
  Documentation/ApiOverview/Xclasses/Index.rst
Labels: backport 11.5, backport 12.4

#4328 [TASK] Adjust indentation in MFA chapter
  Documentation/ApiOverview/Authentication/MultiFactorAuthentication.rst
Labels: reST formatting, backport 11.5, backport 12.4

#4337 [TASK] Adjust indentation of TYPO3_CONF_VARS[FE]
  Documentation/Configuration/Typo3ConfVars/FE.rst
Labels: reST formatting, backport 12.4

#4336 [TASK] Adjust indentation of TYPO3_CONF_VARS[EXT]
  Documentation/Configuration/Typo3ConfVars/EXT.rst
Labels: reST formatting, backport 11.5, backport 12.4

#4334 [TASK] Streamline MFA chapter
  Documentation/ApiOverview/Authentication/MultiFactorAuthentication.rst
  Documentation/ApiOverview/Authentication/MultiFactorAuthentication/DeactivateExistingProvider.yaml
  Documentation/ApiOverview/Authentication/MultiFactorAuthentication/RegisterCustomProvider.yaml
Labels: backport 11.5, backport 12.4

#4341 [TASK] Remove information about Crowdin Initiative
  Documentation/ApiOverview/Localization/TranslationServer/Crowdin.rst
  Documentation/ApiOverview/Localization/TranslationServer/Crowdin/Faq.rst
Labels: backport 11.5, backport 12.4

#4345 [TASK] Add third-party MFA providers
  Documentation/ApiOverview/Authentication/MultiFactorAuthentication.rst
Labels: backport 11.5, backport 12.4

#4335 [TASK] Reference MFA sections from MFA options of TYPO3_CONF_VARS[BE]
  Documentation/ApiOverview/Authentication/MultiFactorAuthentication.rst
  Documentation/Configuration/Typo3ConfVars/BE.rst
Labels: backport 11.5, backport 12.4

#4331 [BUGFIX] Fix issues in example of Pagination
  Documentation/ApiOverview/Pagination/Index.rst
Labels: backport 12.4

#4322 [TASK] Add Xdebug in "Debugging" chapter
  Documentation/ApiOverview/Debugging/Index.rst
Labels: content, backport 11.5, backport 12.4

#4323 [TASK] Streamline "Extending TCA > Storing the changes" chapter
  Documentation/ExtensionArchitecture/HowTo/ExtendingTca/StoringChanges/Index.rst
Labels: backport 11.5, backport 12.4

#4346 [TASK] Correct indentation and language levels
  Documentation/Configuration/TypoScript/Syntax/Operators/Index.rst
Labels: backport 11.5, backport 12.4

#4354 [TASK] Transform language properties into confvals
  Documentation/ApiOverview/SiteHandling/AddLanguages.rst
Labels: backport 12.4

#4357 [BUGFIX] Resolve duplicate link anchors
  Documentation/ExtensionArchitecture/FileStructure/ExtConfTemplate.rst
Labels: backport 11.5, backport 12.4

#4355 [FEATURE] Provide null coalescing operator for TypoScript constants
  Documentation/Configuration/TypoScript/Syntax/Operators/Index.rst
Labels: changelog

#4360 [BUGFIX] Add missing names to confvals in context
  Documentation/ApiOverview/Context/Index.rst
Labels: backport 11.5, backport 12.4

#4363 [BUGFIX] Add names to confvals
  Documentation/ApiOverview/Logging/Writers/Index.rst
Labels: backport 11.5, backport 12.4

#4364 [BUGFIX] Add names to confvals
  Documentation/ApiOverview/SystemRegistry/Index.rst
Labels: backport 11.5, backport 12.4

#4366 [BUGFIX] Add names to confvals
  Documentation/Configuration/Typo3ConfVars/DB.rst
Labels: backport 11.5, backport 12.4
