Repository TYPO3-Documentation/TYPO3CMS-Reference-CoreApi, pull requests merged in 2024-01, with the labels that each got.

#3850 [TASK] #102715 - Frontend "determineId()" related events changed
  Documentation/ApiOverview/Events/Events/Frontend/AfterPageAndLanguageIsResolvedEvent.rst
  Documentation/ApiOverview/Events/Events/Frontend/AfterPageWithRootLineIsResolvedEvent.rst
  Documentation/ApiOverview/Events/Events/Frontend/BeforePageIsResolvedEvent.rst
  Documentation/CodeSnippets/Events/Frontend/AfterPageAndLanguageIsResolvedEvent.rst.txt
  Documentation/CodeSnippets/Events/Frontend/AfterPageWithRootLineIsResolvedEvent.rst.txt
  Documentation/CodeSnippets/Events/Frontend/BeforePageIsResolvedEvent.rst.txt
Labels: changelog

#3851 [TASK] Streamline "Database / Middleware" chapter
  Documentation/ApiOverview/Database/Middleware/Index.rst
Labels: backport 12.4

#3854 [FEATURE] Add TypoScript plugin configuration example
  Documentation/ExtensionArchitecture/Extbase/Reference/TypoScriptConfiguration.rst
  Documentation/ExtensionArchitecture/Extbase/Reference/_TypoScriptConfiguration/_pluginconf.typoscript
Labels: backport 11.5, backport 12.4

#3856 [FEATURE] #102496 - Introduce global Doctrine DBAL driver middlewares
  Documentation/ApiOverview/Database/Middleware/Index.rst
  Documentation/ApiOverview/Database/Middleware/_ext_localconf_global.php
  Documentation/ApiOverview/Database/Middleware/_ext_localconf_global_disable.php
  Documentation/ApiOverview/Database/Middleware/_ext_localconf_specific.php
Labels: changelog

#3858 [FEATURE] #102586 - Introduce sortable Doctrine DBAL middleware registration
  Documentation/ApiOverview/Database/Middleware/Index.rst
  Documentation/ApiOverview/Database/Middleware/_ext_localconf_global.php
  Documentation/ApiOverview/Database/Middleware/_ext_localconf_global_disable.php
  Documentation/ApiOverview/Database/Middleware/_ext_localconf_sorting.php
  Documentation/ApiOverview/Database/Middleware/_ext_localconf_specific.php
  Documentation/ApiOverview/Database/Middleware/_ext_localconf_specific_deprecated.php
  Documentation/ApiOverview/Database/Middleware/_ext_localconf_specific_dual_versions.php
  Documentation/Images/ManualScreenshots/Database/MiddlewareConfigurationModule.png
Labels: changelog

#3859 [TASK] Use correct dbmns vendor name
  Documentation/ApiOverview/Database/Statement/Index.rst
Labels: backport 11.5, backport 12.4

#3863 [CI] Run tests with at least PHP 8.2
  .github/workflows/tests.yml
  Build/Scripts/runTests.sh
  Build/testing-docker/docker-compose.yml
  composer.json
Labels: changelog

#3862 [TASK] Add note about outdated example for AfterCacheableContentIsGeneratedEvent
  Documentation/ApiOverview/Events/Events/Frontend/AfterCacheableContentIsGeneratedEvent.rst
Labels: changelog

#3868 [TASK] Remove note about outdated kickstarter extension
  Documentation/ExtensionArchitecture/Tutorials/Kickstart/Index.rst
Labels: backport 12.4

#3867 [TASK] Add criteria for Composer packages to be imported into TER
  Documentation/ExtensionArchitecture/FileStructure/ComposerJson.rst
Labels: backport 11.5, backport 12.4

#3865 [FEATURE] #102587 - Introduce driver middleware interface UsableForConnectionInterface
  Documentation/ApiOverview/Database/Middleware/Index.rst
  Documentation/ApiOverview/Database/Middleware/_CustomDriver.php
  Documentation/ApiOverview/Database/Middleware/_CustomMiddleware.php
  Documentation/ApiOverview/Database/Middleware/_ext_localconf_CustomMiddleware.php
  Documentation/CodeSnippets/Config/Api/All.php
  Documentation/CodeSnippets/Config/Api/Database.php
  Documentation/CodeSnippets/Manual/Database/UsableForConnectionInterface.rst.txt
Labels: changelog

#3875 [TASK] Adjust ordering of the "Request life cycle" TOC
  Documentation/ApiOverview/RequestLifeCycle/Index.rst
Labels: backport 11.5, backport 12.4

#3869 [FEATURE] #102755 - PSR-14 event for modifying getImageResource result
  Documentation/ApiOverview/Events/Events/Frontend/AfterImageResourceResolvedEvent.rst
  Documentation/ApiOverview/Events/Events/Frontend/_AfterImageResourceResolvedEvent/_MyEventListener.php
  Documentation/CodeSnippets/Config/Api/Events/EventsFrontend.php
  Documentation/CodeSnippets/Events/Frontend/AfterImageResourceResolvedEvent.rst.txt
Labels: changelog

#3878 [FEATURE] #102793 - PSR-14 event for modifying default constraints in PageRepository
  Documentation/ApiOverview/Events/Events/Core/Domain/ModifyDefaultConstraintsForDatabaseQueryEvent.rst
  Documentation/CodeSnippets/Config/Api/Events/EventsCore.php
  Documentation/CodeSnippets/Events/Core/ModifyDefaultConstraintsForDatabaseQueryEvent.rst.txt
Labels: changelog

#3879 [BUGFIX] Update _Registration.php
  Documentation/ExtensionArchitecture/HowTo/BackendModule/_ModuleConfiguration/_Registration.php
Labels: backport 12.4

#3881 [TASK] Add a note for extbase module registration params
  Documentation/ExtensionArchitecture/HowTo/BackendModule/ModuleConfiguration.rst
Labels: backport 12.4

#3884 Update BackendUserObject.rst
  Documentation/ApiOverview/Backend/BackendUserObject.rst
Labels: backport 11.5, backport 12.4

#3888 Drop obsolete "deleteTree" DataHandler flag
  Documentation/ApiOverview/Typo3CoreEngine/Database/Index.rst
Labels: backport 11.5, backport 12.4

#3895 adjustment in the ES6 JavaScript EventApi
  Documentation/ApiOverview/Backend/JavaScript/EventApi/Index.rst
  Documentation/ApiOverview/Backend/JavaScript/EventApi/_DebounceEvent.js
  Documentation/ApiOverview/Backend/JavaScript/EventApi/_DirectBinding.js
  Documentation/ApiOverview/Backend/JavaScript/EventApi/_EventDelegation.js
  Documentation/ApiOverview/Backend/JavaScript/EventApi/_RegularEvent.js
  Documentation/ApiOverview/Backend/JavaScript/EventApi/_ReleaseEvent.js
  Documentation/ApiOverview/Backend/JavaScript/EventApi/_RequestAnimationFrameEvent.js
  Documentation/ApiOverview/Backend/JavaScript/EventApi/_ThrottleEvent.js
  Documentation/ApiOverview/Backend/JavaScript/Modules/_Modals/_static_backdrop.js
  Documentation/ApiOverview/Backend/JavaScript/Modules/_SessionStorageWrapper/_storage.js
  Documentation/ApiOverview/Icon/Index.rst
Labels: backport 12.4

#3898 [TASK] Unify icon identifiers
  Documentation/ApiOverview/Icon/Index.rst
  Documentation/ApiOverview/Icon/_Icons.php
Labels: backport 12.4

#3891 [FEATURE] #102588 - Implement PDO DriverResult as doctrine/dbal driver middleware
  Documentation/ApiOverview/Database/Middleware/Index.rst
  Documentation/ApiOverview/Database/Middleware/_ext_localconf_CustomMiddleware.php
  Documentation/ApiOverview/Database/Middleware/_ext_localconf_global.php
  Documentation/ApiOverview/Database/Middleware/_ext_localconf_global_disable.php
  Documentation/ApiOverview/Database/Middleware/_ext_localconf_sorting.php
  Documentation/ApiOverview/Database/Middleware/_ext_localconf_specific.php
  Documentation/ApiOverview/Database/Middleware/_ext_localconf_specific_dual_versions.php
Labels: changelog

#3892 [FEATURE] #102806 - BeforePageIsRetrievedEvent in PageRepository
  Documentation/ApiOverview/Events/Events/Core/Domain/BeforePageIsRetrievedEvent.rst
  Documentation/ApiOverview/Events/Events/Core/Domain/_BeforePageIsRetrievedEvent/_MyEventListener.php
  Documentation/CodeSnippets/Config/Api/Events/EventsCore.php
  Documentation/CodeSnippets/Events/Core/BeforePageIsRetrievedEvent.rst.txt
Labels: changelog

#3901 [FEATURE] Document cli backend login
  Documentation/ApiOverview/CommandControllers/Index.rst
  Documentation/ApiOverview/Typo3CoreEngine/UsingDataHandler/Index.rst
Labels: backport 11.5, backport 12.4

#3893 [FEATURE] #99323 - PSR-14 Event for modifying records after fetching content
  Documentation/ApiOverview/Events/Events/Frontend/ModifyRecordsAfterFetchingContentEvent.rst
  Documentation/ApiOverview/Events/Events/Frontend/_ModifyRecordsAfterFetchingContentEvent/_MyEventListener.php
  Documentation/CodeSnippets/Config/Api/Events/EventsFrontend.php
  Documentation/CodeSnippets/Events/Frontend/ModifyRecordsAfterFetchingContentEvent.rst.txt
Labels: changelog

#3894 [BUGFIX] #102837 - Remove invalid configuration option from SMTP upgr…
  Documentation/Configuration/Typo3ConfVars/MAIL.rst
Labels: changelog, backport 11.5, backport 12.4

#3909 [BUGFIX] Adhere to the CGL for validateRstFiles.php
  Build/Scripts/validateRstFiles.php
Labels: backport 12.4

#3911 [TASK] Break up "page/userTSconfig" as two words
  Documentation/ExtensionArchitecture/FileStructure/ExtLocalconf.rst
Labels: backport 11.5, backport 12.4

#3913 Typo fixed
  Documentation/ApiOverview/ContentElements/Introduction.rst
Labels: backport 11.5, backport 12.4

#3914 Typo fixed
  Documentation/CodeSnippets/CustomContentElements/CustomContentElement.rst.txt
Labels: backport 11.5, backport 12.4

#3923 [TASK] #102873 - Add localRootLine to PageInformation
  Documentation/ApiOverview/RequestLifeCycle/RequestAttributes/FrontendPageInformation.rst
Labels: changelog

#3922 [FEATURE] #102745 - PSR-14 events for modifying ContentObject stdWrap functionality
  Documentation/ApiOverview/Events/Events/Frontend/AfterStdWrapFunctionsExecutedEvent.rst
  Documentation/ApiOverview/Events/Events/Frontend/AfterStdWrapFunctionsInitializedEvent.rst
  Documentation/ApiOverview/Events/Events/Frontend/BeforeStdWrapFunctionsExecutedEvent.rst
  Documentation/ApiOverview/Events/Events/Frontend/BeforeStdWrapFunctionsInitializedEvent.rst
  Documentation/ApiOverview/Events/Events/Frontend/EnhanceStdWrapEvent.rst
  Documentation/ApiOverview/Events/Events/Frontend/_EnhanceStdWrapEvent/_MyEventListener.php
  Documentation/CodeSnippets/Config/Api/Events/EventsFrontend.php
  Documentation/CodeSnippets/Events/Frontend/AfterStdWrapFunctionsExecutedEvent.rst.txt
  Documentation/CodeSnippets/Events/Frontend/AfterStdWrapFunctionsInitializedEvent.rst.txt
  Documentation/CodeSnippets/Events/Frontend/BeforeStdWrapFunctionsExecutedEvent.rst.txt
  Documentation/CodeSnippets/Events/Frontend/BeforeStdWrapFunctionsInitializedEvent.rst.txt
  Documentation/CodeSnippets/Events/Frontend/EnhanceStdWrapEvent.rst.txt
Labels: changelog

#3926 [BUGFIX] #102899 - Fix BeforeRequestTokenProcessedEvent code example
  Documentation/ApiOverview/Events/Events/Core/Authentication/BeforeRequestTokenProcessedEvent.rst
  Documentation/ApiOverview/Events/Events/Core/Authentication/_BeforeRequestTokenProcessedEvent/_MyEventListener.php
Labels: backport 12.4

#3925 [FEATURE] Link site.websiteTitle and PageTitle API
  Documentation/ApiOverview/Seo/PageTitleApi.rst
  Documentation/ApiOverview/SiteHandling/Basics.rst
Labels: backport 11.5, backport 12.4

#3930 Explain how to fetch the current tt_content UID
  Documentation/ApiOverview/Fal/UsingFal/ExamplesFileFolder.rst
  Documentation/ApiOverview/RequestLifeCycle/RequestAttributes/CurrentContentObject.rst
Labels: backport 12.4

#3924 [TASK] Mention type casting for FlexForms
  Documentation/ApiOverview/DataFormats/T3datastructure/Elements/Index.rst
Labels: backport 11.5, backport 12.4

#3931 [TASK] Overhaul Developing a custom ViewHelper
  Documentation/ApiOverview/Fluid/DevelopCustomViewhelper.rst
  Documentation/ApiOverview/Fluid/_CustomViewHelper/_GravatarTagBasedViewHelper.php
  Documentation/ApiOverview/Fluid/_CustomViewHelper/_GravatarTagBasedViewHelper2.php
  Documentation/ApiOverview/Fluid/_CustomViewHelper/_GravatarViewHelper.php
  Documentation/ApiOverview/Fluid/_CustomViewHelper/_GravatarWithContentElementsViewHelper.php
  Documentation/ApiOverview/Fluid/_CustomViewHelper/_StrtolowerViewHelper.php
Labels: backport 12.4

#3938 [FEATURE] #102835 - Add PSR-14 events to manipulate TypoLinkCodecService
  Documentation/ApiOverview/Events/Events/Core/LinkHandling/AfterTypoLinkDecodedEvent.rst
  Documentation/ApiOverview/Events/Events/Core/LinkHandling/BeforeTypoLinkEncodedEvent.rst
  Documentation/ApiOverview/Events/Events/Core/LinkHandling/Index.rst
  Documentation/ApiOverview/Events/Events/Core/LinkHandling/_AfterTypoLinkDecodedEvent/_MyEventListener.php
  Documentation/ApiOverview/Events/Events/Core/LinkHandling/_BeforeTypoLinkEncodedEvent/_MyEventListener.php
  Documentation/CodeSnippets/Config/Api/Events/EventsCore.php
  Documentation/CodeSnippets/Events/Core/LinkHandling/AfterTypoLinkDecodedEvent.rst.txt
  Documentation/CodeSnippets/Events/Core/LinkHandling/BeforeTypoLinkEncodedEvent.rst.txt
Labels: changelog

#3937 [TASK] Adjust headings on introduction page of Caching chapter
  Documentation/ApiOverview/CachingFramework/Index.rst
Labels: backport 11.5, backport 12.4

#3942 [TASK] Clean up link handler events section
  Documentation/ApiOverview/LinkHandling/Linkhandler/Events.rst
Labels: content

#3939 [FEATURE] #102849 - PSR-14 event for manipulating store cache functionality of stdWrap
  Documentation/ApiOverview/Events/Events/Frontend/BeforeStdWrapContentStoredInCacheEvent.rst
  Documentation/ApiOverview/Events/Events/Frontend/_BeforeStdWrapContentStoredInCacheEvent/_MyEventListener.php
  Documentation/CodeSnippets/Config/Api/Events/EventsFrontend.php
  Documentation/CodeSnippets/Events/Frontend/BeforeStdWrapContentStoredInCacheEvent.rst.txt
Labels: changelog

#3941 [FEATURE] #102855 - PSR-14 event for modifying resolved link result data
  Documentation/ApiOverview/Events/Events/Core/LinkHandling/AfterLinkResolvedByStringRepresentationEvent.rst
  Documentation/ApiOverview/Events/Events/Core/LinkHandling/_AfterLinkResolvedByStringRepresentationEvent/_MyEventListener.php
  Documentation/ApiOverview/LinkHandling/Linkhandler/Events.rst
  Documentation/CodeSnippets/Config/Api/Events/EventsCore.php
  Documentation/CodeSnippets/Events/Core/LinkHandling/AfterLinkResolvedByStringRepresentationEvent.rst.txt
Labels: changelog

#3944 [TASK] Simplify ModifyUrlForCanonicalTagEvent listener example
  Documentation/ApiOverview/Events/Events/SEO/_ModifyUrlForCanonicalTagEvent/_MyEventListener.php
Labels: backport 12.4

#3943 [FEATURE] #99807 - Always allow listeners to manipulate the canonical…
  Documentation/ApiOverview/Events/Events/SEO/ModifyUrlForCanonicalTagEvent.rst
  Documentation/ApiOverview/Events/Events/SEO/_ModifyUrlForCanonicalTagEvent/_MyEventListener.php
  Documentation/CodeSnippets/Events/Seo/ModifyUrlForCanonicalTagEvent.rst.txt
Labels: changelog

#3948 [TASK] #102632 - Use strict types in Extbase ActionController
  Documentation/CodeSnippets/Extbase/Controllers/BackendControllerInitialize.rst.txt
Labels: changelog

#3949 [TASK] Update code snippets for tutorial of EXT:tea
  Documentation/CodeSnippets/Tutorials/Tea/Classes/Domain/Model/TeaImage.rst.txt
  Documentation/CodeSnippets/Tutorials/Tea/Classes/Domain/Repository/TeaRepository.rst.txt
  Documentation/CodeSnippets/Tutorials/Tea/ComposerJsonSimplified.rst.txt
  Documentation/CodeSnippets/Tutorials/Tea/Configuration/TCA/TeaCtrl.rst.txt
  Documentation/CodeSnippets/Tutorials/Tea/Configuration/TCA/TeaTypes.rst.txt
  Documentation/CodeSnippets/Tutorials/Tea/ExtEmconf.rst.txt
  Documentation/CodeSnippets/Tutorials/Tea/ExtTablesSql.rst.txt
Labels: backport 12.4

#3951 [FEATURE] #102865 - PSR-14 event for modifying loaded form definition
  Documentation/ApiOverview/Events/Events/Form/AfterLinkResolvedByStringRepresentationEvent.rst
  Documentation/ApiOverview/Events/Events/Form/Index.rst
  Documentation/ApiOverview/Events/Events/Form/_AfterFormDefinitionLoadedEvent/_MyEventListener.php
  Documentation/CodeSnippets/Config/Api/Events/All.php
  Documentation/CodeSnippets/Config/Api/Events/EventsForm.php
  Documentation/CodeSnippets/Events/Form/AfterFormDefinitionLoadedEvent.rst.txt
Labels: changelog

#3952 [TASK] #102875 - Changed Connection->lastInsertId() method signature
  Documentation/ApiOverview/Database/Connection/Index.rst
  Documentation/ApiOverview/Database/Connection/_MyTableRepository_lastinsertId.php
Labels: changelog

#3946 [FEATURE] #99485 - Show the redirect integrity status
  Documentation/ApiOverview/Events/Events/Redirects/ModifyRedirectManagementControllerViewDataEvent.rst
  Documentation/CodeSnippets/Events/Redirects/ModifyRedirectManagementControllerViewDataEvent.rst.txt
Labels: changelog

#3955 [TASK] Replace PDO constants with those from Connection class
  Documentation/ApiOverview/Database/ExpressionBuilder/Index.rst
  Documentation/ApiOverview/Database/QueryBuilder/Index.rst
  Documentation/ApiOverview/Workspaces/Index.rst
Labels: changelog, backport 11.5, backport 12.4

#3959 [BUGFIX] Correct malformed hyperlink target in "Using DataHandler"
  Documentation/ApiOverview/Typo3CoreEngine/UsingDataHandler/Index.rst
Labels: backport 11.5, backport 12.4

#3965 [TASK] #102875 - Add note about dropped "\PDO::PARAM_*" in Doctrine DBAL v4
  Documentation/ApiOverview/Database/QueryBuilder/Index.rst
Labels: backport 11.5, backport 12.4
