Repository TYPO3-Documentation/TYPO3CMS-Reference-CoreApi, pull requests merged in 2024-06, with the labels that each got.

#4471 Fix code example for ArrayPaginator
  Documentation/ApiOverview/Pagination/Index.rst
Labels: backport 12.4

#4472 Fix utility class name used for debugging
  Documentation/CodingGuidelines/CglPhp/PhpSyntaxFormatting.rst
Labels: backport 11.5, backport 12.4

#4478 [TASK] Update select field flexform example
  Documentation/ApiOverview/FlexForms/Index.rst
  Documentation/ApiOverview/FlexForms/T3datastructure/SheetReferences/Index.rst
Labels: backport 12.4

#4481 [TASK] Remove Testing FAQ section
  Documentation/Testing/Faq.rst
  Documentation/Testing/Index.rst
Labels: backport 12.4

#4483 [TASK] Move Unit test examples in php files
  Documentation/Testing/WritingUnit.rst
  Documentation/Testing/_UnitTests/_ArrayUtility.php
  Documentation/Testing/_UnitTests/_ArrayUtilityTest.php
  Documentation/Testing/_UnitTests/_ArrayUtilityTestDataProvider.php
  Documentation/Testing/_UnitTests/_CacheManagerTest.php
  Documentation/Testing/_UnitTests/_FormInlineAjaxControllerTest.php
  Documentation/Testing/_UnitTests/_SomeTest.php
  Documentation/Testing/_UnitTests/_SomeTestSingleton.php
Labels: backport 11.5, backport 12.4

#4485 [TASK] Move Functional test examples in php files
  Documentation/Testing/WritingFunctional.rst
  Documentation/Testing/_FunctionalTests/_Fixture.csv
  Documentation/Testing/_FunctionalTests/_GeneratorTest.php
  Documentation/Testing/_FunctionalTests/_LocalizationRepositoryTest.php
  Documentation/Testing/_FunctionalTests/_SomeTest.php
  Documentation/Testing/_FunctionalTests/_SomeTestConfiguration.php
  Documentation/Testing/_FunctionalTests/_SomeTestExtensions.php
  Documentation/Testing/_FunctionalTests/_SomeTestFiles.php
  Documentation/Testing/_FunctionalTests/_SomeTestFrontend.php
  Documentation/Testing/_FunctionalTests/_SomeTestImportDataSet.php
Labels: backport 12.4

#4491 [TASK] Modernize Unit test examples
  Documentation/Testing/WritingUnit.rst
  Documentation/Testing/_UnitTests/_ArrayUtility.php
  Documentation/Testing/_UnitTests/_ArrayUtilityTest.php
  Documentation/Testing/_UnitTests/_ArrayUtilityTestDataProvider.php
  Documentation/Testing/_UnitTests/_CacheManagerTest.php
  Documentation/Testing/_UnitTests/_FormInlineAjaxControllerTest.php
  Documentation/Testing/_UnitTests/_OnTheFlyTest.php
  Documentation/Testing/_UnitTests/_SomeTest.php
  Documentation/Testing/_UnitTests/_SomeTestSingleton.php
  Documentation/Testing/_UnitTests/_TcaFlexPrepareTest.php
Labels: backport 12.4

#4495 [TASK] Display TYPO3_CONF_VARS in confval menu
  Documentation/Configuration/Typo3ConfVars/BE.rst
  Documentation/Configuration/Typo3ConfVars/DB.rst
  Documentation/Configuration/Typo3ConfVars/EXT.rst
  Documentation/Configuration/Typo3ConfVars/FE.rst
  Documentation/Configuration/Typo3ConfVars/GFX.rst
  Documentation/Configuration/Typo3ConfVars/HTTP.rst
  Documentation/Configuration/Typo3ConfVars/MAIL.rst
  Documentation/Configuration/Typo3ConfVars/SYS.rst
Labels: backport 12.4

#4497 [TASK] Use confval menues and names
  Documentation/ApiOverview/Backend/JavaScript/Modules/Modals.rst
Labels: backport 12.4

#4503 [TASK] Split up Writing Unit Test
  Documentation/Testing/Index.rst
  Documentation/Testing/UnitTesting/Index.rst
  Documentation/Testing/UnitTesting/Introduction.rst
  Documentation/Testing/UnitTesting/_UnitTests/_ArrayUtility.php
  Documentation/Testing/UnitTesting/_UnitTests/_ArrayUtilityTest.php
  Documentation/Testing/UnitTesting/_UnitTests/_ArrayUtilityTestDataProvider.php
  Documentation/Testing/UnitTesting/_UnitTests/_FormInlineAjaxControllerTest.php
  Documentation/Testing/UnitTesting/_UnitTests/_OnTheFlyTest.php
  Documentation/Testing/UnitTesting/_UnitTests/_SomeTest.php
  Documentation/Testing/UnitTesting/_UnitTests/_TcaFlexPrepareTest.php
Labels: backport 12.4

#4506 [TASK] Split up Writing Functional Test
  Documentation/Testing/FunctionalTesting/Index.rst
  Documentation/Testing/FunctionalTesting/Introduction.rst
  Documentation/Testing/FunctionalTesting/_FunctionalTests/_Fixture.csv
  Documentation/Testing/FunctionalTesting/_FunctionalTests/_GeneratorTest.php
  Documentation/Testing/FunctionalTesting/_FunctionalTests/_LocalizationRepositoryTest.php
  Documentation/Testing/FunctionalTesting/_FunctionalTests/_SomeTest.php
  Documentation/Testing/FunctionalTesting/_FunctionalTests/_SomeTestConfiguration.php
  Documentation/Testing/FunctionalTesting/_FunctionalTests/_SomeTestExtensions.php
  Documentation/Testing/FunctionalTesting/_FunctionalTests/_SomeTestFiles.php
  Documentation/Testing/FunctionalTesting/_FunctionalTests/_SomeTestFrontend.php
  Documentation/Testing/FunctionalTesting/_FunctionalTests/_SomeTestImportDataSet.php
  Documentation/Testing/Index.rst
  Documentation/Testing/UnitTesting/Index.rst
  Documentation/Testing/UnitTesting/Introduction.rst
Labels: backport 12.4

#4505 [TASK] Running unit tests
  Documentation/Testing/UnitTesting/Index.rst
  Documentation/Testing/UnitTesting/Running.rst
Labels: backport 12.4

#4512 [BUGFIX] set code language
  Documentation/ApiOverview/Database/QueryBuilder/Index.rst
Labels: backport 11.5, backport 12.4

#4515 [TASK] Move chapter on Acceptance testing of site_introduction
  Documentation/Testing/ProjectTesting.rst
  Documentation/Testing/Tutorial/Acceptance.rst
  Documentation/Testing/Tutorial/Index.rst
Labels: backport 12.4

#4509 [FEATURE] Write new chapter on project testing
  Documentation/Testing/ProjectTesting.rst
  Documentation/Testing/Tutorial/Acceptance.rst
  Documentation/Testing/_ProjectTesting/_composer.json
  Documentation/Testing/_ProjectTesting/_php-cs-fixer.dist.php
  Documentation/Testing/_ProjectTesting/_phpstan.neon
Labels: backport 12.4

#4457 [TASK] Add components of TYPO3 extension
  Documentation/ExtensionArchitecture/Tutorials/ComponentsOfTYPO3Extension/CreatingDatabaseModel.rst
  Documentation/ExtensionArchitecture/Tutorials/ComponentsOfTYPO3Extension/Index.rst
  Documentation/ExtensionArchitecture/Tutorials/ComponentsOfTYPO3Extension/MakingDataPersistable.rst
  Documentation/ExtensionArchitecture/Tutorials/ComponentsOfTYPO3Extension/MakingTheExtensionInstallable.rst
  Documentation/ExtensionArchitecture/Tutorials/Index.rst
Labels: backport 12.4

#4521 [BUGFIX] Set language for literalinclude
  Documentation/Testing/ProjectTesting.rst
Labels: backport 12.4

#4520 [BUGFIX] Use proper #[Cascade(['value' => ''])] annotation
  Documentation/ExtensionArchitecture/Extbase/Reference/_Annotations/_Cascade.php
  Documentation/ExtensionArchitecture/Extbase/Reference/_Annotations/_Multiple.php
Labels: backport 12.4

#4528 Embed YouTube Video Tutorial
  Documentation/ApiOverview/Localization/TranslationServer/Crowdin.rst
Labels: backport 11.5, backport 12.4

#4524 [TASK] Describe available fields in sys_file_metadata
  Documentation/ApiOverview/Fal/Architecture/Database.rst
  Documentation/ApiOverview/Fal/UsingFal/Frontend.rst
Labels: backport 11.5, backport 12.4

#4494 [TASK] Note about automatic nonce inclusion for inline scripts/styles
  Documentation/ApiOverview/ContentSecurityPolicy/Index.rst
Labels: backport 12.4

#4536 [FOLLOWUP] Add linebreaks to extbase URI example
  Documentation/ExtensionArchitecture/Extbase/Reference/UriArguments.rst
Labels: backport 11.5, backport 12.4

#4542 [TASK] Rename "Edit Links" to "UriBuilder"
  Documentation/ApiOverview/Backend/UriBuilder.rst
Labels: backport 11.5, backport 12.4

#4545 [TASK] Overhaul Backend UriBuilder page
  Documentation/ApiOverview/Backend/UriBuilder.rst
  Documentation/ApiOverview/Backend/_UriBuilder/_CreateNewRecord.html
  Documentation/ApiOverview/Backend/_UriBuilder/_EditRecord.html
  Documentation/ApiOverview/Backend/_UriBuilder/_ModuleController.php
  Documentation/ApiOverview/Backend/_UriBuilder/_ModuleCreateController.php
  Documentation/ApiOverview/Backend/_UriBuilder/_ModuleEditController.php
Labels: backport 12.4

#4549 [TASK] Use examples from EXT:examples for UriBuilder
  Documentation/ApiOverview/Backend/BackendModules/_InitializeModuleTemplate.rst.txt
  Documentation/ApiOverview/Backend/BackendModules/_ModifyDocHeaderComponent.rst.txt
  Documentation/ApiOverview/Backend/UriBuilder.rst
  Documentation/ApiOverview/Backend/_UriBuilder/_CreateHaikuBlankLink.rst.txt
  Documentation/ApiOverview/Backend/_UriBuilder/_CreateHaikuLink.rst.txt
  Documentation/ApiOverview/Backend/_UriBuilder/_CreateHaikuLinkPhp.rst.txt
  Documentation/ApiOverview/Backend/_UriBuilder/_CreateNewRecord.html
  Documentation/ApiOverview/Backend/_UriBuilder/_GetEditDoktypeLink.rst.txt
  Documentation/ApiOverview/Backend/_UriBuilder/_LinksAction.rst.txt
  Documentation/ApiOverview/Backend/_UriBuilder/_ModuleController.php
  Documentation/ApiOverview/Backend/_UriBuilder/_ModuleCreateController.php
  Documentation/CodeSnippets/Config/Api/BackendApi.php
  Documentation/CodeSnippets/Events/Core/EvaluateModifierFunctionEvent.rst.txt
  Documentation/CodeSnippets/Examples/EditLinks/EditLinksDisplay.rst.txt
  Documentation/CodeSnippets/Examples/EditLinks/LinksAction.rst.txt
  Documentation/ExtensionArchitecture/Extbase/Reference/Domain/_CustomValidator/_PropertyValidator.rst.txt
Labels: backport 12.4

#4551 Update SoftwareDesignPrinciples.rst
  Documentation/ExtensionArchitecture/BestPractises/SoftwareDesignPrinciples.rst
Labels: backport 11.5, backport 12.4

#4560 Solve spelling errors introduction diagram
  Documentation/Images/Graphics/Typo3CmsStructure.png
  Documentation/Images/Graphics/Typo3CmsStructure.svg
  Documentation/Introduction/Index.rst
Labels: backport 11.5, backport 12.4

#4559 Update example for sliding pagination
  Documentation/ApiOverview/Pagination/Index.rst
Labels: backport 12.4

#4557 Update example of DocHeader
  Documentation/ExtensionArchitecture/HowTo/BackendModule/CreateModule.rst
Labels: backport 12.4

#4565 [BUGFIX] Document ModuleConfiguration - source code of Modules.php included
  Documentation/CodeSnippets/Config/Api/BackendApi.php
  Documentation/ExtensionArchitecture/HowTo/BackendModule/ModuleConfiguration.rst
  Documentation/ExtensionArchitecture/HowTo/BackendModule/_ModuleConfiguration/_Modules.rst.txt
  Documentation/ExtensionArchitecture/HowTo/BackendModule/_ModuleConfiguration/_Registration.php
Labels: backport 12.4

#4558 Use LanguageServiceFactory instead of global LANG
  Documentation/ExtensionArchitecture/HowTo/Localization/Php.rst
  Documentation/ExtensionArchitecture/HowTo/Localization/_php/MyBackendClass.php
Labels: backport 11.5, backport 12.4, Follow Up

#4568 [TASK] Switch to constructor property promotion
  Documentation/ExtensionArchitecture/HowTo/Localization/_php/MyBackendClass.php
Labels: backport 12.4

#4554 [TASK] Add information about Test Runners, with their advantages and disadvantages
  Documentation/Testing/AcceptanceTesting/Index.rst
  Documentation/Testing/ExtensionTesting.rst
  Documentation/Testing/FunctionalTesting/Introduction.rst
  Documentation/Testing/Index.rst
  Documentation/Testing/ProjectTesting.rst
  Documentation/Testing/TestRunners.rst
  Documentation/Testing/UnitTesting/Running.rst
Labels: content, backport 11.5, backport 12.4

#4575 [BUGFIX] Use consistent variable name in FlexFormProcessor example
  Documentation/ApiOverview/FlexForms/Index.rst
Labels: backport 11.5, backport 12.4

#4582 [TASK] Move examples to separate files
  Documentation/ApiOverview/Fal/UsingFal/ExamplesFileFolder.rst
  Documentation/ApiOverview/Fal/UsingFal/_ExamplesFileFolder/_SomeFileEid1.php
  Documentation/ApiOverview/Fal/UsingFal/_ExamplesFileFolder/_SomeFileEid2.php
  Documentation/ApiOverview/Fal/UsingFal/_ExamplesFileFolder/_SomeFileEid3.php
Labels: backport 12.4
