Repository TYPO3-Documentation/TYPO3CMS-Reference-CoreApi, pull requests merged in 2024-12, with the labels that each got.

#5107 [TASK] Get rid of "resname" attribute in XLF files
  Documentation/ApiOverview/Events/Events/Core/Country/_BeforeCountriesEvaluatedEvent/_countries.xlf
  Documentation/ApiOverview/Events/Events/Core/Country/_BeforeCountriesEvaluatedEvent/_de.countries.xlf
  Documentation/ApiOverview/Events/Events/Core/Country/_BeforeCountriesEvaluatedEvent/_tlh.countries.xlf
  Documentation/ApiOverview/Localization/ManagingTranslations.rst
  Documentation/ApiOverview/Localization/TranslationServer/Crowdin/Faq.rst
  Documentation/ApiOverview/Localization/XliffFormat.rst
  Documentation/ApiOverview/Localization/_de.locallang_modadministration.xlf
  Documentation/ApiOverview/Localization/_snippets/_example.xlf
  Documentation/ApiOverview/Localization/_snippets/_example2.xlf
  Documentation/Configuration/Typo3ConfVars/SYS.rst
Labels: backport 12.4, backport 13.4

#5114 [TASK] Add anchors to assets
  Documentation/ApiOverview/Assets/Index.rst
Labels: backport 12.4, backport 13.4

#5084 [TASK] Document changes to base-distribution
  Documentation/ApiOverview/DirectoryStructure/Index.rst
Labels: backport 12.4, backport 13.4

#5120 [BUGFIX] $frontendUserAuthentification->fetchGroupData() returns void
  Documentation/ApiOverview/RequestLifeCycle/RequestAttributes/FrontendUser.rst
Labels: backport 12.4, backport 13.4

#5123 [TASK] Hint at related frontend user chapters
  Documentation/ApiOverview/RequestLifeCycle/RequestAttributes/FrontendUser.rst
Labels: backport 12.4, backport 13.4

#5126 [TASK] Make clear what type is the request
  Documentation/ApiOverview/RequestLifeCycle/RequestAttributes/FrontendUser.rst
Labels: backport 12.4, backport 13.4

#5086 [TASK] Mention sets in the file structure for extensions
  Documentation/ExtensionArchitecture/FileStructure/Configuration/Index.rst
  Documentation/ExtensionArchitecture/FileStructure/Configuration/PageTsconfig.rst
  Documentation/ExtensionArchitecture/FileStructure/Configuration/Sets/Index.rst
  Documentation/ExtensionArchitecture/FileStructure/Configuration/TsConfig/Index.rst
  Documentation/ExtensionArchitecture/FileStructure/Configuration/TypoScript/Index.rst
  Documentation/ExtensionArchitecture/FileStructure/Configuration/TypoScript/_snippets/_sys_template.php
  Documentation/ExtensionArchitecture/FileStructure/Index.rst
  Documentation/ExtensionArchitecture/SitePackage/Index.rst
Labels: backport 13.4

#5131 [TASK] Escape table columns
  Documentation/ApiOverview/Seo/XmlSitemap.rst
Labels: backport 12.4, backport 13.4

#5111 [BUGFIX] Reestablish manipulation of EXT:indexed_search query
  Documentation/ApiOverview/Events/Events/IndexedSearch/BeforeFinalSearchQueryIsExecutedEvent.rst
  Documentation/ApiOverview/Events/Events/IndexedSearch/Index.rst
  Documentation/ApiOverview/Events/Events/IndexedSearch/_BeforeFinalSearchQueryIsExecutedEvent/_MyEventListener.php
  Documentation/CodeSnippets/Config/Api/Events/All.php
  Documentation/CodeSnippets/Config/Api/Events/EventsIndexedSearch.php
  Documentation/CodeSnippets/Events/IndexedSearch/BeforeFinalSearchQueryIsExecutedEvent.rst.txt
Labels: backport 13.4

#5113 [DOCS] Improve LoginProviderInterface->modifyView() ReST
  Documentation/ApiOverview/Backend/LoginProvider.rst
  Documentation/ApiOverview/Backend/_LoginProvider/_MyLoginProvider.php
Labels: backport 13.4

#5110 [FEATURE] Allow modifying fetched page content
  Documentation/ApiOverview/Events/Events/Frontend/AfterContentHasBeenFetchedEvent.rst
  Documentation/ApiOverview/Events/Events/Frontend/_AfterContentHasBeenFetchedEvent/_MyEventListener.php
  Documentation/CodeSnippets/Config/Api/Events/EventsFrontend.php
  Documentation/CodeSnippets/Events/Frontend/AfterContentHasBeenFetchedEvent.rst.txt
Labels: backport 13.4

#5138 Update CreateModuleWithExtbase.rst
  Documentation/ExtensionArchitecture/HowTo/BackendModule/CreateModuleWithExtbase.rst
Labels: backport 13.4

#5140 [FORWARDPORT] CreateModuleWithExtbase.rst (#5138)
  Documentation/ExtensionArchitecture/HowTo/BackendModule/CreateModuleWithExtbase.rst
Labels: backport 13.4

#5143 Added note about caching a QueryResult
  Documentation/ExtensionArchitecture/Extbase/Reference/Domain/Repository.rst
Labels: backport 12.4, backport 13.4

#5154 [BUGFIX] Fix wrong literalincludes for FunctionalTesting chapter
  Documentation/Testing/FunctionalTesting/Index.rst
Labels: backport 12.4, backport 13.4

#5153 [TASK] Fix description of additionalCanonicalizedUrlParameters
  Documentation/ApiOverview/Seo/CanonicalApi.rst
  Documentation/Configuration/Typo3ConfVars/FE.rst
Labels: backport 12.4, backport 13.4

#5150 Update CreateModuleWithExtbase.rst - rendering example is broken
  Documentation/ExtensionArchitecture/HowTo/BackendModule/CreateModuleWithExtbase.rst
Labels: backport-required

#5161 Fix wrong import directory
  Documentation/ApiOverview/SiteHandling/SiteSets.rst
Labels: backport 13.4

#5166 [DOCS] Have a better example in event listener docs
  Documentation/ApiOverview/Events/EventDispatcher/Index.rst
  Documentation/ApiOverview/Events/EventDispatcher/_MailerEventListener.php
  Documentation/ApiOverview/Events/EventDispatcher/_MailerEventListenerRepeatable.php
  Documentation/ApiOverview/Events/EventDispatcher/_MailerEventListenerRepeatable2.php
  Documentation/ApiOverview/Events/Events/Core/Mail/BeforeMailerSentMessageEvent.rst
  Documentation/ApiOverview/Events/Events/Core/Mail/_AfterMailerInitializationEvent/_MyEventListener.php
  Documentation/ApiOverview/Events/Events/Core/Mail/_BeforeMailerSentMessageEvent/_MyEventListener.php
Labels: backport 13.4

#5147 [TASK] Remove useless AfterMailerInitializationEvent #1177
  Documentation/ApiOverview/Events/EventDispatcher/Index.rst
  Documentation/ApiOverview/Events/Events/Core/Mail/AfterMailerInitializationEvent.rst
  Documentation/ApiOverview/Events/Events/Core/Mail/_AfterMailerInitializationEvent/_MyEventListener.php
  Documentation/ApiOverview/Mail/Index.rst
  Documentation/CodeSnippets/Config/Api/Events/EventsCore.php
  Documentation/CodeSnippets/Events/Core/AfterMailerInitializationEvent.rst.txt
Labels: changelog
