Repository TYPO3-Documentation/TYPO3CMS-Reference-CoreApi, pull requests merged in 2024-02, with the labels that each got.

#3956 [FEATURE] #102935 - Add PackageInitializationEvent
  Documentation/ApiOverview/Events/Events/Core/Package/PackageInitializationEvent.rst
  Documentation/ApiOverview/Events/Events/Core/Package/_PackageInitializationEvent/_MyEventListener.php
  Documentation/ApiOverview/Events/Events/ExtensionManager/AfterExtensionDatabaseContentHasImportedEvent.rst
  Documentation/ApiOverview/Events/Events/ExtensionManager/AfterExtensionFilesHaveBeenImportedEvent.rst
  Documentation/ApiOverview/Events/Events/ExtensionManager/AfterExtensionStaticDatabaseContentHasBeenImportedEvent.rst
  Documentation/CodeSnippets/Config/Api/Events/EventsCore.php
  Documentation/CodeSnippets/Config/Api/Events/EventsExtensionManager.php
  Documentation/CodeSnippets/Events/Core/Package/PackageInitializationEvent.rst.txt
  Documentation/CodeSnippets/Events/ExtensionManager/AfterExtensionDatabaseContentHasBeenImportedEvent.rst.txt
  Documentation/CodeSnippets/Events/ExtensionManager/AfterExtensionFilesHaveBeenImportedEvent.rst.txt
  Documentation/CodeSnippets/Events/ExtensionManager/AfterExtensionStaticDatabaseContentHasBeenImportedEvent.rst.txt
Labels: changelog

#3968 [TASK] Adapt information about removed QueryBuilder->execute() method
  Documentation/ApiOverview/Database/QueryBuilder/Index.rst
Labels: changelog

#3971 [TASK] Use import in code snippets
  Documentation/ApiOverview/Events/JavaScript/DebounceEvent/Index.rst
  Documentation/ApiOverview/Events/JavaScript/RegularEvent/Index.rst
  Documentation/ApiOverview/Events/JavaScript/RequestAnimationFrameEvent/Index.rst
  Documentation/ApiOverview/Events/JavaScript/ThrottleEvent/Index.rst
Labels: backport 12.4

#3969 [TASK] Add link to CSP introduction
  Documentation/ApiOverview/ContentSecurityPolicy/Index.rst
Labels: backport 12.4

#3975 [BUGFIX] Add missing colon in code-block directive
  Documentation/ApiOverview/DataFormats/T3datastructure/Elements/Index.rst
Labels: backport 11.5, backport 12.4

#3970 [TASK] Modernize XLIFF example
  Documentation/ApiOverview/Localization/_de.locallang_modadministration.xlf
Labels: backport 11.5, backport 12.4

#3977 [TASK] Removed file reference related functionality
  Documentation/ApiOverview/Fal/Architecture/Database.rst
Labels: changelog

#3976 [TASK] Removed file reference related functionality
  Documentation/ApiOverview/Fal/Architecture/Database.rst
Labels: changelog

#3978 [BUGFIX] Remove outdated information about ext_tables_static+adt.sql
  Documentation/ExtensionArchitecture/FileStructure/ExtTablesStaticAdtSql.rst
Labels: backport 11.5, backport 12.4

#3992 [TASK] Describe how to override PSR-14 event listeners
  Documentation/ApiOverview/Events/EventDispatcher/Index.rst
  Documentation/ApiOverview/Events/EventDispatcher/_ServicesOverrideBase.php
  Documentation/ApiOverview/Events/EventDispatcher/_ServicesOverrideBase.yaml
  Documentation/ApiOverview/Events/EventDispatcher/_ServicesOverrideCustom.php
  Documentation/ApiOverview/Events/EventDispatcher/_ServicesOverrideCustom.yaml
Labels: backport 12.4

#3994 Improve new page type example
  Documentation/ApiOverview/PageTypes/_pages.php
Labels: backport 12.4

#3732 [DOCS] Create a how-to tutorial on how to extend Extbase models
  Documentation/ExtensionArchitecture/Extbase/Reference/Domain/Model.rst
  Documentation/ExtensionArchitecture/Extbase/Reference/Domain/Persistence.rst
  Documentation/ExtensionArchitecture/HowTo/ExtendExtbaseModel/Index.rst
  Documentation/ExtensionArchitecture/HowTo/ExtendExtbaseModel/_Classes.php
  Documentation/ExtensionArchitecture/HowTo/ExtendExtbaseModel/_MyExtendedModel.php
  Documentation/ExtensionArchitecture/HowTo/ExtendExtbaseModel/_MyExtendedModelRepository.php
  Documentation/ExtensionArchitecture/HowTo/ExtendExtbaseModel/_ext_localconf.php
  Documentation/Settings.cfg
Labels: backport 12.4

#3935 [TASK] Changes on PasswordHashing
  Documentation/ApiOverview/PasswordHashing/Index.rst
Labels: backport 12.4

#3991 [TASK] Enhance PSR-14 EventDispatcher documentation
  Documentation/ApiOverview/Events/EventDispatcher/Index.rst
Labels: backport 12.4

#4001 remove duplicate word "upgrade"
  Documentation/ApiOverview/PasswordHashing/Index.rst
Labels: backport 12.4

#4005 [TASK] #102799 - TYPO3_CONF_VARS.GFX.processor_stripColorProfileParameters option added
  Documentation/Configuration/Typo3ConfVars/GFX.rst
Labels: changelog, backport 11.5, backport 12.4

#4010 [TASK] Add missing version to processor_stripColorProfileParameters
  Documentation/Configuration/Typo3ConfVars/GFX.rst
Labels: backport 11.5, backport 12.4

#4014 Set correct icon in typeicon_classes
  Documentation/ApiOverview/PageTypes/_pages.php
Labels: backport 12.4

#4017 [TASK] Fix typo
  Documentation/ApiOverview/Backend/EditLinks.rst
Labels: backport 11.5, backport 12.4

#4020 [SEO] Mention "FlashMessageService" in the text
  Documentation/ApiOverview/FlashMessages/FlashMessagesApi.rst
Labels: backport 12.4

#4016 [TASK] Address recent Coding Standards
  Documentation/CodingGuidelines/CglPhp/PhpFileFormatting/FileStructure.rst
  Documentation/CodingGuidelines/CglPhp/PhpFileFormatting/GeneralRequirementsForPhpFiles.rst
Labels: backport 11.5, backport 12.4

#3997 [TASK] Adjust example for mapping a TYPO3 table to another database
  Documentation/ApiOverview/Database/Configuration/Index.rst
  Documentation/Configuration/Typo3ConfVars/DB.rst
Labels: changelog, backport 11.5, backport 12.4

#4024 [TASK] Adjust condition in example for PolicyMutatedEvent
  Documentation/ApiOverview/Events/Events/Core/Security/_PolicyMutatedEvent/_MyEventListener.php
Labels: backport 12.4

#4027 [BUGFIX] Correct connection name in example of Database/Configuration chapter
  Documentation/ApiOverview/Database/Configuration/Index.rst
Labels: backport 11.5, backport 12.4

#4028 [FEATURE] #102932 - Add getConfigArray() method to frontend.typoscript request attribute
  Documentation/ApiOverview/RequestLifeCycle/RequestAttributes/FrontendTyposcript.rst
  Documentation/CodeSnippets/Manual/Entity/FrontendTypoScript.rst.txt
Labels: changelog

#4029 [FEATURE] #102932 - New TypoScript related frontend events
  Documentation/ApiOverview/Events/Events/Frontend/AfterTypoScriptDeterminedEvent.rst
  Documentation/ApiOverview/Events/Events/Frontend/BeforePageCacheIdentifierIsHashedEvent.rst
  Documentation/ApiOverview/Events/Events/Frontend/ModifyTypoScriptConfigEvent.rst
  Documentation/CodeSnippets/Config/Api/Events/EventsFrontend.php
  Documentation/CodeSnippets/Events/Frontend/AfterTypoScriptDeterminedEvent.rst.txt
  Documentation/CodeSnippets/Events/Frontend/BeforePageCacheIdentifierIsHashedEvent.rst.txt
  Documentation/CodeSnippets/Events/Frontend/ModifyTypoScriptConfigEvent.rst.txt
Labels: changelog

#4033 [FEATURE] #102960 - Clarify main tables must be on default connection
  Documentation/ApiOverview/Database/Configuration/Index.rst
  Documentation/Configuration/Typo3ConfVars/DB.rst
Labels: changelog

#4034 [TASK] #102916 - Use TrimMode class constants for ExpressionBuilder::trim()
  Documentation/ApiOverview/Database/ExpressionBuilder/Index.rst
Labels: changelog, backport 11.5, backport 12.4

#4035 [TASK] #102875 - QueryBuilder::add() has been removed
  Documentation/ApiOverview/Database/QueryBuilder/Index.rst
Labels: changelog

#4036 [TASK] #102875 - QueryBuilder::add() will be removed
  Documentation/ApiOverview/Database/QueryBuilder/Index.rst
Labels: changelog

#4039 [TASK] Document QueryBuilder::setMaxResults(null) to get all results
  Documentation/ApiOverview/Database/QueryBuilder/Index.rst
Labels: backport 11.5, backport 12.4

#4042 [TASK] #102875 - Add note about QueryBuilder::setMaxResults(0)
  Documentation/ApiOverview/Database/QueryBuilder/Index.rst
Labels: changelog

#4007 [TASK] #102800 - FAL enforces absolute paths to match project root or lockRootPath
  Documentation/ApiOverview/Fal/Administration/Storages.rst
  Documentation/Configuration/Typo3ConfVars/BE.rst
Labels: changelog, backport 11.5, backport 12.4

#4045 add reference to Service API
  Documentation/ApiOverview/Authentication/Index.rst
Labels: backport 12.4

#4048 Fix $GLOBALS[TYPO3_CONF_VARS][MAIL] documentation for symfony/mailer
  Documentation/Configuration/Typo3ConfVars/MAIL.rst
Labels: backport 11.5, backport 12.4

#4053 [TASK] Add section about using DI inside ext_conf_template.txt userfuncs
  Documentation/ApiOverview/DependencyInjection/Index.rst
Labels: backport 11.5, backport 12.4

#4051 [TASK] Add information about blocked sys_file in DataHandler
  Documentation/ApiOverview/Fal/Architecture/Database.rst
  Documentation/ApiOverview/Typo3CoreEngine/Database/Index.rst
Labels: backport 11.5, backport 12.4

#4060 [TASK] Adjust meta tag introduction
  Documentation/ApiOverview/Seo/MetaTagApi.rst
Labels: backport 11.5, backport 12.4
