Repository TYPO3-Documentation/TYPO3CMS-Reference-CoreApi, pull requests merged in 2024-03, with the labels that each got.

#4067 [TASK] Add PropagateResponseException to ActionController section
  Documentation/ExtensionArchitecture/Extbase/Reference/Controller/ActionController.rst
  Documentation/ExtensionArchitecture/Extbase/Reference/_FrontendPlugin/_ExternalRedirectController.php
  Documentation/ExtensionArchitecture/Extbase/Reference/_FrontendPlugin/_PropagateResponseExceptionController.php
Labels: backport 11.5, backport 12.4

#4074 [TASK] Add section about parameter types in the DB/Connection chapter
  Documentation/ApiOverview/Database/Connection/Index.rst
  Documentation/ApiOverview/Database/ExpressionBuilder/Index.rst
  Documentation/ApiOverview/Database/ExpressionBuilder/_MyTableRepository.php
  Documentation/ApiOverview/Database/QueryBuilder/Index.rst
Labels: backport 11.5, backport 12.4

#4077 [BUGFIX] Correct comment in example for AfterPageTreeItemsPreparedEvent
  Documentation/ApiOverview/Events/Events/Backend/_AfterPageTreeItemsPreparedEvent/_MyEventListener.php
Labels: backport 12.4

#4079 [BUGFIX] Insert missing namespace import for Extbase\Annotation\Validate
  Documentation/ExtensionArchitecture/Extbase/Reference/Domain/_CustomValidator/_ObjectValidatorUsage.php
Labels: backport 11.5, backport 12.4

#4085 [FEATURE] Describe Validate/IgnoreValidation DTO alternatives
  Documentation/ExtensionArchitecture/Extbase/Reference/Annotations.rst
Labels: backport 12.4

#4081 [FEATURE] #103211 - Introduce tree node labels
  Documentation/ApiOverview/Events/Events/Backend/AfterPageTreeItemsPreparedEvent.rst
  Documentation/ApiOverview/Events/Events/Backend/_AfterPageTreeItemsPreparedEvent/_MyEventListener.php
Labels: changelog

#4090 [TASK] Drop "PHP Best Practices / Hook naming" chapter
  Documentation/CodingGuidelines/CglPhp/CodingBestPractices/HookNaming.rst
  Documentation/CodingGuidelines/CglPhp/CodingBestPractices/Index.rst
Labels: content outdated, backport 11.5, backport 12.4

#4091 [TASK] Streamline "PHP Best Practices / Working with exceptions" chapter
  Documentation/CodingGuidelines/CglPhp/PhpArchitecture/WorkingWithExceptions.rst
Labels: backport 11.5, backport 12.4

#4092 [TASK] Drop "PHP Best Practices / General links" chapter
  Documentation/CodingGuidelines/CglPhp/PhpArchitecture/GeneralLinks.rst
  Documentation/CodingGuidelines/CglPhp/PhpArchitecture/Index.rst
Labels: backport 11.5, backport 12.4

#4093 [TASK] Drop mentioning of signals in Xclasses chapter
  Documentation/ApiOverview/Xclasses/Index.rst
Labels: backport 11.5, backport 12.4

#4089 [TASK] Update "PHP Best Practices / Accessing the Database" chapter
  Documentation/CodingGuidelines/CglPhp/CodingBestPractices/AccessingTheDatabase.rst
  Documentation/CodingGuidelines/CglPhp/CodingBestPractices/_AccessingTheDatabase/_MyTableRepository.php
Labels: backport 11.5, backport 12.4

#4103 [TASK] Streamline "PHP Best Practices / Localization" chapter
  Documentation/CodingGuidelines/CglPhp/CodingBestPractices/Localization.rst
Labels: backport 11.5, backport 12.4

#4108 [TASK] Merge localization chapter into Xliff coding guidelines
  Documentation/CodingGuidelines/CglPhp/CodingBestPractices/Index.rst
  Documentation/CodingGuidelines/CglPhp/CodingBestPractices/Localization.rst
  Documentation/CodingGuidelines/CglXliff/Index.rst
Labels: backport 11.5, backport 12.4

#4110 [TASK] Move "PHP Architecture" one level up
  Documentation/CodingGuidelines/CglPhp/Index.rst
  Documentation/CodingGuidelines/Index.rst
  Documentation/CodingGuidelines/PhpArchitecture/Index.rst
  Documentation/CodingGuidelines/PhpArchitecture/ModelingCrossCuttingConcerns/Index.rst
  Documentation/CodingGuidelines/PhpArchitecture/ModelingCrossCuttingConcerns/Services.rst
  Documentation/CodingGuidelines/PhpArchitecture/ModelingCrossCuttingConcerns/StaticMethods.rst
  Documentation/CodingGuidelines/PhpArchitecture/ModelingCrossCuttingConcerns/Traits.rst
  Documentation/CodingGuidelines/PhpArchitecture/WorkingWithExceptions.rst
Labels: backport 11.5, backport 12.4

#4113 [TASK] Move cross-cutting concerns one level up
  Documentation/CodingGuidelines/PhpArchitecture/Index.rst
  Documentation/CodingGuidelines/PhpArchitecture/ModelingCrossCuttingConcerns/Index.rst
  Documentation/CodingGuidelines/PhpArchitecture/Services.rst
  Documentation/CodingGuidelines/PhpArchitecture/StaticMethods.rst
  Documentation/CodingGuidelines/PhpArchitecture/Traits.rst
  Documentation/CodingGuidelines/PhpArchitecture/WorkingWithExceptions.rst
Labels: backport 11.5, backport 12.4

#4086 [DOCS] How to disable all logging
  Documentation/ApiOverview/Logging/Configuration/Index.rst
Labels: backport 11.5, backport 12.4

#4116 [TASK] Move "Coding guidelines" and "Best practice" one level up
  Documentation/CodingGuidelines/CglJavaScript/Index.rst
  Documentation/CodingGuidelines/CglPhp/FileStructure.rst
  Documentation/CodingGuidelines/CglPhp/GeneralRequirementsForPhpFiles.rst
  Documentation/CodingGuidelines/CglPhp/Index.rst
  Documentation/CodingGuidelines/CglPhp/PhpFileFormatting/Index.rst
  Documentation/CodingGuidelines/CglPhp/PhpSyntaxFormatting.rst
  Documentation/CodingGuidelines/CglPhp/UsingPhpdoc.rst
  Documentation/CodingGuidelines/CglRest/Index.rst
  Documentation/CodingGuidelines/CglTsConfig.rst
  Documentation/CodingGuidelines/CglTypeScript/Index.rst
  Documentation/CodingGuidelines/CglTypoScript/Index.rst
  Documentation/CodingGuidelines/CglYaml.rst
  Documentation/CodingGuidelines/CodingBestPractices/AccessingTheDatabase.rst
  Documentation/CodingGuidelines/CodingBestPractices/ClassNamesOfUserFiles.rst
  Documentation/CodingGuidelines/CodingBestPractices/HandlingDeprecations.rst
  Documentation/CodingGuidelines/CodingBestPractices/Index.rst
  Documentation/CodingGuidelines/CodingBestPractices/Singletons.rst
  Documentation/CodingGuidelines/CodingBestPractices/StaticMethods.rst
  Documentation/CodingGuidelines/CodingBestPractices/UnitTests.rst
  Documentation/CodingGuidelines/CodingBestPractices/_AccessingTheDatabase/_MyTableRepository.php
  Documentation/CodingGuidelines/Index.rst
  Documentation/CodingGuidelines/Introduction.rst
  Documentation/CodingGuidelines/PhpArchitecture/Index.rst
  Documentation/CodingGuidelines/PhpArchitecture/WorkingWithExceptions.rst
Labels: backport 11.5, backport 12.4

#4102 Small markdown change at restrictions/RootlevelRestriction description
  Documentation/ApiOverview/Database/RestrictionBuilder/Index.rst
Labels: backport 11.5, backport 12.4

#4123 [BUGFIX] Use inline literal for SQL part in restriction builder chapter
  Documentation/ApiOverview/Database/RestrictionBuilder/Index.rst
Labels: backport 11.5, backport 12.4

#4131 [TASK] Enhance configuration options section in password hashing chapter
  Documentation/ApiOverview/PasswordHashing/Index.rst
  Documentation/Configuration/Typo3ConfVars/BE.rst
Labels: backport 11.5, backport 12.4

#4130 [TASK] #103084 - Set Argon2id as default password hashing algorithm
  Documentation/ApiOverview/PasswordHashing/Index.rst
  Documentation/Images/AutomaticScreenshots/AdminTools/PasswordHashingSettings.png
  Documentation/Images/AutomaticScreenshots/AdminTools/PasswordHashingSettings.rst.txt
  Documentation/Images/ManualScreenshots/AdminTools/PasswordHashingSettings.png
Labels: changelog

#4129 [FEATURE] #103186 - Introduce tree node status information
  Documentation/ApiOverview/Events/Events/Backend/AfterPageTreeItemsPreparedEvent.rst
  Documentation/ApiOverview/Events/Events/Backend/_AfterPageTreeItemsPreparedEvent/_MyEventListener.php
Labels: changelog

#4126 [TASK] Use "-" instead of "_" in page type icon name
  Documentation/ApiOverview/PageTypes/_Icons.php
  Documentation/ApiOverview/PageTypes/_pages.php
Labels: backport 12.4

#4142 [TASK] Update hint for publishing Composer extensions on TER
  Documentation/ExtensionArchitecture/FileStructure/ComposerJson.rst
Labels: backport 11.5, backport 12.4

#4140 [BUGFIX] Correct some rendering warnings
  Documentation/ApiOverview/Typo3CoreEngine/Database/Index.rst
  Documentation/CodingGuidelines/CglPhp/FileStructure.rst
  Documentation/CodingGuidelines/Introduction.rst
Labels: backport 11.5, backport 12.4

#4143 [TASK] Clean up DataHandler
  Documentation/ApiOverview/CommandControllers/Index.rst
  Documentation/ApiOverview/Database/Connection/Index.rst
  Documentation/ApiOverview/Database/Introduction/Index.rst
  Documentation/ApiOverview/FormEngine/Introduction/Index.rst
  Documentation/ApiOverview/Typo3CoreEngine/Database/Index.rst
  Documentation/ApiOverview/Typo3CoreEngine/Files/Index.rst
  Documentation/ApiOverview/Typo3CoreEngine/Index.rst
  Documentation/ApiOverview/Typo3CoreEngine/Introduction/Index.rst
  Documentation/ApiOverview/Typo3CoreEngine/TceDb/Index.rst
  Documentation/ApiOverview/Typo3CoreEngine/TceFile/Index.rst
  Documentation/ApiOverview/Typo3CoreEngine/UsingDataHandler/Index.rst
Labels: backport 11.5, backport 12.4

#4155 [BUGFIX] Fix indentation in Services Chapter
  Documentation/ApiOverview/Services/Developer/Implementing.rst
Labels: reST formatting

#4154 [TASK] Mention configuration option for fileadmin folder
  Documentation/ApiOverview/DirectoryStructure/Index.rst
Labels: backport 11.5, backport 12.4

#4152 [TASK] Revise Registry chapter
  Documentation/ApiOverview/SystemRegistry/Index.rst
  Documentation/ApiOverview/SystemRegistry/_instance.php
  Documentation/CodeSnippets/Config/Api/All.php
  Documentation/CodeSnippets/Config/Api/Registry.php
  Documentation/CodeSnippets/Manual/Registry/Registry.rst.txt
Labels: content, backport 11.5, backport 12.4

#4151 [TASK] Move Typo3CoreEngine to DataHandler
  Documentation/ApiOverview/DataHandler/Database/Index.rst
  Documentation/ApiOverview/DataHandler/Database/_ext_localconf.php
  Documentation/ApiOverview/DataHandler/Index.rst
  Documentation/ApiOverview/DataHandler/Introduction/Index.rst
  Documentation/ApiOverview/DataHandler/TceDb/Index.rst
  Documentation/ApiOverview/DataHandler/UsingDataHandler/Index.rst
Labels: backport 11.5, backport 12.4

#4170 [BUGFIX] Correct index/anchor for DataHandler data array
  Documentation/ApiOverview/DataHandler/Database/Index.rst
Labels: backport 11.5, backport 12.4

#4171 [TASK] Revise DataHandler introduction
  Documentation/ApiOverview/DataHandler/Introduction/Index.rst
Labels: backport 11.5, backport 12.4

#4180 [TASK] Add link to request retrieval
  Documentation/Configuration/TypoScript/PhpApi/Index.rst
Labels: backport 12.4

#4179 [BUGFIX] Correct display of FQCN in reference
  Documentation/ExtensionArchitecture/HowTo/Localization/Php.rst
Labels: backport 11.5, backport 12.4

#4187 sting ==> string
  Documentation/ApiOverview/Localization/TranslationServer/Crowdin/OnlineTranslation.rst
Labels: backport 11.5, backport 12.4

#4185 [TASK] Remove development information for v12
  Documentation/ApiOverview/PasswordPolicies/Index.rst
Labels: backport 12.4

#4178 [TASK] Revise DataHandler basics chapter
  Documentation/ApiOverview/DataHandler/Database/Index.rst
  Documentation/ApiOverview/DataHandler/Database/_basic_usage.php
  Documentation/ApiOverview/DataHandler/Introduction/Index.rst
Labels: backport 11.5, backport 12.4

#4182 [TASK] Add Named Arguments best practices
  Documentation/CodingGuidelines/CodingBestPractices/Index.rst
  Documentation/CodingGuidelines/CodingBestPractices/NamedArguments.rst
Labels: backport 11.5, backport 12.4

#4194 [TASK] Streamline spelling and indentation of CGL named arguments chapter
  Documentation/CodingGuidelines/CodingBestPractices/NamedArguments.rst
Labels: backport 11.5, backport 12.4

#4197 [BUGFIX] Use additional.php instead of settings.php
  Documentation/ApiOverview/PasswordPolicies/Index.rst
Labels: backport 12.4

#4186 [FEATURE] Use Password Policy to validate password
  Documentation/ApiOverview/PasswordPolicies/Index.rst
  Documentation/ApiOverview/PasswordPolicies/_PrivateKeyGeneratorCommand.php
Labels: backport 12.4

#4201 [BUGFIX] Use new to create mails
  Documentation/ApiOverview/Mail/Index.rst
Labels: backport 12.4

#4202 Set request object for FluidEmail
  Documentation/ApiOverview/Mail/Index.rst
Labels: backport 12.4

#4204 Fix various small issues and spelling errors
  Documentation/ApiOverview/Backend/BackendLayout.rst
  Documentation/ApiOverview/Rte/Transformations/Introduction.rst
  Documentation/Configuration/Typo3ConfVars/BE.rst
  Documentation/Configuration/Typo3ConfVars/FE.rst
  Documentation/Configuration/Typo3ConfVars/GFX.rst
  Documentation/Configuration/Typo3ConfVars/HTTP.rst
  Documentation/Configuration/Typo3ConfVars/MAIL.rst
  Documentation/Configuration/Typo3ConfVars/SYS.rst
  Documentation/ExtensionArchitecture/HowTo/UpdateExtensions/Index.rst
Labels: backport 12.4

#4198 [TASK] Rework extbase model extension
  Documentation/ExtensionArchitecture/HowTo/ExtendExtbaseModel/Index.rst
  Documentation/ExtensionArchitecture/HowTo/ExtendExtbaseModel/_ext_localconf_repository.php
Labels: backport 12.4

#4208 Overhaul Tea extension directory structure
  Documentation/ExtensionArchitecture/Tutorials/Tea/DirectoryStructure.rst
Labels: backport 11.5, backport 12.4

#4211 [TASK] Sort sections in "Various expressions" in "Expression builder" chapter
  Documentation/ApiOverview/Database/ExpressionBuilder/Index.rst
Labels: backport 12.4

#4214 Update FlashMessagesApi.rst
  Documentation/ApiOverview/FlashMessages/FlashMessagesApi.rst
Labels: backport-required

#4217 [BUGFIX] Avoid TSFE constructor injection in DataHandler example
  Documentation/ApiOverview/DataHandler/Database/Index.rst
  Documentation/ApiOverview/DataHandler/Database/_SomeController.php
Labels: backport 11.5, backport 12.4

#4219 Avoid deprecated/removed setUpBackendUserFromFixture()
  Documentation/Testing/WritingFunctional.rst
Labels: backport 12.4

#4223 Overhaul advanced routing configuration
  Documentation/ApiOverview/Routing/AdvancedRoutingConfiguration.rst
Labels: backport 11.5, backport 12.4

#4218 fix crowdin translation path
  Documentation/ApiOverview/Localization/TranslationServer/Crowdin/Faq.rst
Labels: backport 11.5, backport 12.4

#4213 [TASK] Add example for LogoutConfirmedEvent listener
  Documentation/ApiOverview/Events/Events/FrontendLogin/LogoutConfirmedEvent.rst
  Documentation/ApiOverview/Events/Events/FrontendLogin/_LogoutConfirmedEvent/_DeletePrivateKeyOnLogout.php
  Documentation/ApiOverview/Events/Events/FrontendLogin/_LogoutConfirmedEvent/_Services.yaml
Labels: backport 12.4

#4228 [FEATURE] Add Maltese and Gaelic as supported languages
  Documentation/ApiOverview/Localization/Languages.rst
Labels: changelog

#4229 [TASK] Use confval instead of table for DataHandler's commands array
  Documentation/ApiOverview/DataHandler/Database/Index.rst
Labels: backport 11.5, backport 12.4

#4233 [TASK] Use confval instead of table for DataHandler's command keywords
  Documentation/ApiOverview/DataHandler/Database/Index.rst
Labels: backport 11.5, backport 12.4
