Repository TYPO3-Documentation/TYPO3CMS-Reference-CoreApi, pull requests merged in 2024-08, with the labels that each got.

#4641 Use FQNs and improve headlines
  Documentation/ApiOverview/Database/ConnectionPool/Index.rst
Labels: backport 12.4

#4649 [FEATURE] Add if() expression support to ExpressionBuilder
  Documentation/ApiOverview/Database/ExpressionBuilder/Index.rst
  Documentation/ApiOverview/Database/ExpressionBuilder/_ExpressionBuilderIf.rst.txt
  Documentation/CodeSnippets/Config/Api/Database.php
Labels: changelog

#4652 [TASK] Add example for multiple TOTP provider configuration
  Documentation/ApiOverview/Authentication/MultiFactorAuthentication.rst
  Documentation/ApiOverview/Authentication/MultiFactorAuthentication/RegisterCustomProvider.yaml
  Documentation/ApiOverview/Authentication/MultiFactorAuthentication/RegisterMultipleProviders.yaml
Labels: backport 12.4

#4656 Update BlogControllerNew.rst.txt
  Documentation/CodeSnippets/Extbase/Controllers/BlogControllerNew.rst.txt
Labels: backport 11.5, backport 12.4

#4655 Do not use Classes as part of namespace
  Documentation/ApiOverview/Backend/BackendModules/ModuleConfiguration/_ModuleConfiguration/_ControllerActions.php
  Documentation/ApiOverview/Backend/BackendModules/ModuleConfiguration/_ModuleConfiguration/_Routes.php
  Documentation/ApiOverview/DataHandler/UsingDataHandler/_ClearCache.php
  Documentation/ApiOverview/DataHandler/UsingDataHandler/_ErrorHandling.php
  Documentation/ApiOverview/DataHandler/UsingDataHandler/_ExecuteCommands.php
  Documentation/ApiOverview/DataHandler/UsingDataHandler/_SubmitComplexData.php
  Documentation/ApiOverview/DataHandler/UsingDataHandler/_SubmitData.php
  Documentation/ApiOverview/DataHandler/UsingDataHandler/_UseAlternativeUser.php
  Documentation/ApiOverview/Fal/UsingFal/_ExamplesStorageRepository/_GetDefaultStorageExample.php
  Documentation/ApiOverview/Fal/UsingFal/_ExamplesStorageRepository/_GetStorageObjectExample.php
  Documentation/ApiOverview/FlashMessages/Render.rst
  Documentation/ApiOverview/FormProtection/_FormProtectionExample.php
Labels: backport 12.4

#4658 Module: labels is an array of string
  Documentation/ApiOverview/Backend/BackendModules/ModuleConfiguration/Index.rst
  Documentation/ApiOverview/Backend/BackendModules/ModuleConfiguration/_ModuleConfiguration/_Routes.php
Labels: backport 12.4

#4660 add crosslink for locallang file reference
  Documentation/ApiOverview/Backend/BackendModules/ModuleConfiguration/Index.rst
Labels: backport 11.5, backport 12.4

#4659 Fix import statement of BlogController
  Documentation/ExtensionArchitecture/Extbase/Reference/Controller/ActionController.rst
Labels: backport 12.4, Follow Up

#4664 [TASK] Move code snippet to php file
  Documentation/ExtensionArchitecture/Extbase/Reference/Controller/ActionController.rst
  Documentation/ExtensionArchitecture/Extbase/Reference/Controller/_Snippets/_ActionController/_ext_localconf.php
Labels: backport 12.4

#4657 [TASK] Mention third-party extension for additional password policy validators
  Documentation/ApiOverview/PasswordPolicies/Index.rst
Labels: backport 12.4

#4667 [BUGFIX] Fix documentation about custom page type icon
  Documentation/ApiOverview/PageTypes/CreateNewPageType.rst
Labels: backport 12.4

#4668 Add notice about `strict_types=1` in `ext_emconf.php`
  Documentation/ExtensionArchitecture/FileStructure/ExtEmconf.rst
Labels: backport-done, backport 11.5

#4650 [TASK] Align header marker length
  Documentation/ApiOverview/CommandControllers/Index.rst
Labels: backport 11.5, backport 12.4

#4593 Improve terminology for Enhancers
  Documentation/ApiOverview/Routing/AdvancedRoutingConfiguration.rst
  Documentation/ApiOverview/Routing/Introduction.rst
Labels: backport 11.5, backport 12.4

#4677 [BUGFIX] Fix enhancer table
  Documentation/ApiOverview/Routing/Introduction.rst
Labels: backport 12.4

#4682 [TASK] Add anchors to debugging information
  Documentation/ApiOverview/Debugging/Index.rst
Labels: backport 12.4

#4654 [TASK] Add Extbase DebuggerUtility and Fluid Debug ViewHelper. Changed Order of contents
  Documentation/ApiOverview/Debugging/Index.rst
Labels: backport 12.4

#4684 [TASK] Introduce pre commit hooks
  .github/workflows/apply-precommit.yml
  .pre-commit-config.yaml
  Documentation/ApiOverview/Debugging/Index.rst
Labels: backport 11.5, backport 12.4

#4692 [TASK] Improve search results for IsContentUsedOnPageLayoutEvent
  Documentation/ApiOverview/Events/Events/Backend/IsContentUsedOnPageLayoutEvent.rst
Labels: backport 12.4

#4696 [TASK] Middleware: Move code snippets to their own files
  Documentation/ApiOverview/RequestLifeCycle/Middlewares.rst
  Documentation/ApiOverview/RequestLifeCycle/_Middlewares/_ExampleMiddleware.php
  Documentation/ApiOverview/RequestLifeCycle/_Middlewares/_NotAvailableMiddleware.php
  Documentation/ApiOverview/RequestLifeCycle/_Middlewares/_RequestEnrichingMiddleware.php
  Documentation/ApiOverview/RequestLifeCycle/_Middlewares/_RequestMiddlewaresDisable.php
  Documentation/ApiOverview/RequestLifeCycle/_Middlewares/_RequestMiddlewaresOrdering.php
  Documentation/ApiOverview/RequestLifeCycle/_Middlewares/_ResponseEnrichingMiddleware.php
  Documentation/ApiOverview/RequestLifeCycle/_Middlewares/_StatusCheckMiddleware.php
  Documentation/CodeSnippets/Config/Api/All.php
  Documentation/CodeSnippets/Config/Api/Middleware.php
  Documentation/CodeSnippets/Middleware/MiddlewareInterface.rst.txt
Labels: backport 12.4

#4693 Better document language overriding capabilities
  Documentation/ExtensionArchitecture/HowTo/Localization/TypoScript.rst
Labels: backport 11.5, backport 12.4

#4698 [TASK] TypoScript Localization: Move code snippets to their own files
  Documentation/ExtensionArchitecture/HowTo/Localization/TypoScript.rst
  Documentation/ExtensionArchitecture/HowTo/Localization/_TypoScript/_currentLanguageCondition.typoscript
  Documentation/ExtensionArchitecture/HowTo/Localization/_TypoScript/_locallang_extbase.typoscript
  Documentation/ExtensionArchitecture/HowTo/Localization/_TypoScript/_locallang_fluidtemplate.typoscript
Labels: backport 12.4

#4701 add hint about Glob Pattern
  Documentation/Configuration/Yaml/ServicesYaml.rst
Labels: backport 12.4
