Repository TYPO3-Documentation/TYPO3CMS-Reference-CoreApi, pull requests merged in 2024-05, with the labels that each got.

#4371 [BUGFIX] Add names to confvals for $GLOBALS['TYPO3_CONF_VARS']['FE']
  Documentation/ApiOverview/ErrorAndExceptionHandling/Configuration/Index.rst
  Documentation/Configuration/Typo3ConfVars/FE.rst
Labels: backport 11.5, backport 12.4

#4356 [TASK] Remove speeddemo
  Documentation/ApiOverview/Events/Events/Linkvalidator/BeforeRecordIsAnalyzedEvent.rst
  Documentation/ExtensionArchitecture/Tutorials/Kickstart/Make/Index.rst
  Documentation/ExtensionArchitecture/Tutorials/Kickstart/SitepackageBuilder/Index.rst
  Documentation/ExtensionArchitecture/Tutorials/Kickstart/SitepackageBuilder/MinimalExtension.rst
  composer.json
Labels: backport 12.4

#4365 [BUGFIX] Add names to confvals
  Documentation/Configuration/GlobalVariables.rst
Labels: backport 11.5, backport 12.4

#4375 [TASK] Improve documentation on accessing site settings
  Documentation/ApiOverview/SiteHandling/AccessingSiteConfiguration.rst
  Documentation/ApiOverview/SiteHandling/SiteSettings.rst
  Documentation/ApiOverview/SiteHandling/UseSiteInTypoScript.rst
Labels: backport 12.4

#4383 [BUGFIX] Limit cs-fixer to folder "Documentation"
  .php-cs-fixer.dist.php
Labels: backport 11.5, backport 12.4

#4382 [TASK] Improve information on ProductionExceptionHandler
  Documentation/ApiOverview/ErrorAndExceptionHandling/ProductionExceptionHandler/Index.rst
Labels: backport 11.5, backport 12.4

#4372 [TASK] Display extension structure in a directory tree
  Documentation/ExtensionArchitecture/FileStructure/Configuration/Extbase/Persistence/Index.rst
  Documentation/ExtensionArchitecture/FileStructure/Index.rst
  Documentation/ExtensionArchitecture/FileStructure/Tests/Index.rst
Labels: backport-required

#4395 Fix order of words
  Documentation/Testing/Faq.rst
Labels: backport 11.5, backport 12.4

#4393 [TASK] Unify and improve Services.yaml examples
  Documentation/CodeSnippets/Manual/Extension/Configuration/ServicesYaml.rst.txt
  Documentation/Configuration/Yaml/ServicesYaml.rst
  Documentation/Configuration/Yaml/_example_services.yaml
  Documentation/ExtensionArchitecture/FileStructure/Configuration/ServicesYaml.rst
Labels: backport 11.5, backport 12.4

#4243 [TASK] Embed API for various expression builder expressions
  Documentation/ApiOverview/Database/ExpressionBuilder/Index.rst
  Documentation/CodeSnippets/Manual/Database/ExpressionBuilderLength.rst.txt
  Documentation/CodeSnippets/Manual/Database/ExpressionBuilderTrim.rst.txt
Labels: backport 12.4

#4402 [TASK] Embed API for expression builder
  Documentation/ApiOverview/Database/ExpressionBuilder/Index.rst
  Documentation/ApiOverview/Database/ExpressionBuilder/_ExpressionBuilder.rst.txt
  Documentation/ApiOverview/Database/ExpressionBuilder/_ExpressionBuilderAggregate.rst.txt
  Documentation/ApiOverview/Database/ExpressionBuilder/_ExpressionBuilderComparisons.rst.txt
  Documentation/ApiOverview/Database/ExpressionBuilder/_ExpressionBuilderLength.rst.txt
  Documentation/ApiOverview/Database/ExpressionBuilder/_ExpressionBuilderTrim.rst.txt
  Documentation/ApiOverview/Database/ExpressionBuilder/_RepositoryAgregate.php
  Documentation/ApiOverview/Database/ExpressionBuilder/_RepositoryLength.php
  Documentation/ApiOverview/Database/ExpressionBuilder/_RepositoryWithJunctions.php
  Documentation/ApiOverview/Database/ExpressionBuilder/_RepositoryWithTrim.php
  Documentation/CodeSnippets/Config/Api/Database.php
  Documentation/CodeSnippets/Extbase/Domain/AbstractEntity.rst.txt
  Documentation/CodeSnippets/Extbase/Domain/ModelWithAdditionalGetters.rst.txt
  Documentation/CodeSnippets/Extbase/Domain/ModelWithPublicGetters.rst.txt
  Documentation/CodeSnippets/Extbase/Domain/ModelWithPublicProperty.rst.txt
  Documentation/CodeSnippets/Extbase/Domain/Optional1on1.rst.txt
  Documentation/CodeSnippets/Extbase/Domain/Relationship1onN1.rst.txt
  Documentation/CodeSnippets/Extbase/Domain/Relationship1onNUni.rst.txt
  Documentation/CodeSnippets/Extbase/Domain/RelationshipNonM.rst.txt
Labels: backport 12.4

#2739 Add section $GLOBALS['LANG'] and amend information
  Documentation/ExtensionArchitecture/HowTo/Localization/Php.rst
Labels: backport 11.5, backport 12.4

#4409 [TASK] Document Debugging an Extbase query
  Documentation/ExtensionArchitecture/Extbase/Reference/Domain/Repository.rst
  Documentation/ExtensionArchitecture/Extbase/Reference/Domain/_Repository/_DebugQuery.php
Labels: backport 11.5, backport 12.4

#4411 [TASK] Introduce a Backend module API section
  Documentation/ApiOverview/Backend/BackendModules/Index.rst
  Documentation/ExtensionArchitecture/HowTo/BackendModule/Index.rst
Labels: backport 12.4

#4410 [TASK] Introduce shorter navigation titles
  Documentation/ApiOverview/Assets/Index.rst
  Documentation/ApiOverview/CommandControllers/Index.rst
  Documentation/ApiOverview/CropVariants/Index.rst
  Documentation/ApiOverview/Database/Index.rst
  Documentation/ApiOverview/Fal/Index.rst
  Documentation/ApiOverview/RequestLifeCycle/Index.rst
  Documentation/ApiOverview/Routing/AdvancedRoutingConfiguration.rst
  Documentation/ApiOverview/Routing/Examples.rst
  Documentation/ApiOverview/Routing/ExtendingRouting.rst
  Documentation/ApiOverview/Routing/Index.rst
  Documentation/ApiOverview/Routing/Introduction.rst
  Documentation/ApiOverview/Routing/PageBasedRouting.rst
  Documentation/ApiOverview/Rte/Index.rst
  Documentation/ApiOverview/Seo/Index.rst
  Documentation/ApiOverview/SessionStorageFramework/Index.rst
  Documentation/ApiOverview/SiteHandling/AccessingSiteConfiguration.rst
  Documentation/ApiOverview/SiteHandling/Basics.rst
  Documentation/ApiOverview/SiteHandling/CliTools.rst
  Documentation/ApiOverview/SiteHandling/CreateNew.rst
  Documentation/ApiOverview/SiteHandling/ExtendingSiteConfig.rst
  Documentation/ApiOverview/SiteHandling/UseSiteInConditions.rst
  Documentation/ApiOverview/SiteHandling/UseSiteInTCA.rst
  Documentation/ApiOverview/SiteHandling/UseSiteInTypoScript.rst
  Documentation/ApiOverview/SiteHandling/UsingEnvVars.rst
  Documentation/ApiOverview/Xclasses/Index.rst
  Documentation/CodingGuidelines/CglJavaScript/Index.rst
  Documentation/CodingGuidelines/CglPhp/Index.rst
  Documentation/CodingGuidelines/CglRest/Index.rst
  Documentation/CodingGuidelines/CglTsConfig.rst
  Documentation/CodingGuidelines/CglTypeScript/Index.rst
  Documentation/CodingGuidelines/CglTypoScript/Index.rst
  Documentation/CodingGuidelines/CglXliff/Index.rst
  Documentation/CodingGuidelines/CglYaml.rst
  Documentation/CodingGuidelines/CodingBestPractices/Index.rst
  Documentation/CodingGuidelines/Introduction.rst
  Documentation/Configuration/Typo3Information.rst
  Documentation/ExtensionArchitecture/Extbase/Examples/Index.rst
  Documentation/ExtensionArchitecture/Extbase/Introduction/Index.rst
  Documentation/ExtensionArchitecture/Extbase/Reference/Index.rst
  Documentation/ExtensionArchitecture/Tutorials/Extbase.rst
  Documentation/ExtensionArchitecture/Tutorials/Kickstart/Index.rst
  Documentation/ExtensionArchitecture/Tutorials/Tea/Index.rst
Labels: backport 11.5, backport 12.4

#4417 [TASK] Cross-reference section on migrating assets (upgrade guide)
  Documentation/ApiOverview/DirectoryStructure/Index.rst
Labels: backport 12.4

#4416 [FEATURE] Document ModuleTemplate
  Documentation/ApiOverview/Backend/BackendModules/Index.rst
  Documentation/ApiOverview/Backend/BackendModules/ModuleTemplate.rst
  Documentation/ApiOverview/Backend/BackendModules/ModuleTemplateFactory.rst
  Documentation/ApiOverview/Backend/BackendModules/_BackendModuleController.php
  Documentation/ApiOverview/Backend/BackendModules/_BackendModuleController_ModuleTemplate.php
  Documentation/ApiOverview/Backend/BackendModules/_ModuleTemplate.rst.txt
  Documentation/ApiOverview/Backend/BackendModules/_ModuleTemplateFactory.rst.txt
  Documentation/CodeSnippets/Config/Api/BackendApi.php
Labels: backport 12.4

#4423 [TASK] Set a more suitable group identifier
  Documentation/ApiOverview/ContentElements/_AddingYourOwnContentElements/_tt_content.php
Labels: backport 12.4

#4419 [FEATURE] Add link to feature toggles in SYS section
  Documentation/Configuration/Typo3ConfVars/SYS.rst
Labels: backport 11.5, backport 12.4

#4424 [FEATURE] Automatically describe console commands
  Documentation/ApiOverview/CommandControllers/ListCommands.rst
  Documentation/ApiOverview/CommandControllers/commands.json
  Makefile
Labels: backport 12.4

#4429 [TASK] ext_emconfig is also needed for functional tests
  Documentation/ExtensionArchitecture/FileStructure/ExtEmconf.rst
Labels: backport 11.5, backport 12.4

#4432 [BUGFIX] Fix typo from #4429
  Documentation/ExtensionArchitecture/FileStructure/ExtEmconf.rst
Labels: backport 11.5, backport 12.4

#4438 [TASK] Separate Backend Module Info in API and how to
  Documentation/ApiOverview/Backend/BackendModules/BackendGUI.rst
  Documentation/ApiOverview/Backend/BackendModules/Index.rst
  Documentation/ApiOverview/Backend/BackendModules/ModuleConfiguration/Index.rst
  Documentation/ApiOverview/Backend/BackendModules/ModuleConfiguration/ThirdlevelModules.rst
  Documentation/ApiOverview/Backend/BackendModules/ModuleConfiguration/ToplevelModules.rst
  Documentation/ApiOverview/Backend/BackendModules/ModuleConfiguration/_ModuleConfiguration/_AliasIdentifier.php
  Documentation/ApiOverview/Backend/BackendModules/ModuleConfiguration/_ModuleConfiguration/_AliasModule.php
  Documentation/ApiOverview/Backend/BackendModules/ModuleConfiguration/_ModuleConfiguration/_ControllerActions.php
  Documentation/ApiOverview/Backend/BackendModules/ModuleConfiguration/_ModuleConfiguration/_ModuleData.php
  Documentation/ApiOverview/Backend/BackendModules/ModuleConfiguration/_ModuleConfiguration/_Routes.php
  Documentation/ApiOverview/Backend/BackendModules/ModuleDataObject.rst
  Documentation/ApiOverview/Backend/BackendModules/ModuleProviderAPI.rst
  Documentation/ApiOverview/Backend/BackendModules/ModuleTypoScript.rst
  Documentation/ExtensionArchitecture/HowTo/BackendModule/CreateModule.rst
  Documentation/ExtensionArchitecture/HowTo/BackendModule/CreateModuleWithExtbase.rst
  Documentation/ExtensionArchitecture/HowTo/BackendModule/Index.rst
  Documentation/ExtensionArchitecture/HowTo/BackendModule/ModuleConfiguration.rst
  Documentation/ExtensionArchitecture/HowTo/BackendModule/Tutorials.rst
Labels: backport 12.4

#4437 Fix incorrect path of namespace in constant reference
  Documentation/ApiOverview/Database/QueryBuilder/Index.rst
Labels: backport 11.5, backport 12.4

#4435 [BUGFIX] Do not reuse DataHandler
  Documentation/ApiOverview/DataHandler/Database/_BasicUsage.php
  Documentation/ApiOverview/DataHandler/UsingDataHandler/Index.rst
  Documentation/ApiOverview/DataHandler/UsingDataHandler/_ClearCache.php
  Documentation/ApiOverview/DataHandler/UsingDataHandler/_ErrorHandling.php
  Documentation/ApiOverview/DataHandler/UsingDataHandler/_ExecuteCommands.php
  Documentation/ApiOverview/DataHandler/UsingDataHandler/_SubmitComplexData.php
  Documentation/ApiOverview/DataHandler/UsingDataHandler/_SubmitData.php
  Documentation/ApiOverview/DataHandler/UsingDataHandler/_UseAlternativeUser.php
  Documentation/ApiOverview/Fal/UsingFal/_ExamplesFileFolder/_CreatingFileReference.php
Labels: backport 11.5, backport 12.4

#4446 [TASK] Improve linking between backend module sections
  Documentation/ApiOverview/Backend/BackendModules/Index.rst
  Documentation/ApiOverview/Backend/BackendModules/ModuleConfiguration/ThirdlevelModules.rst
  Documentation/ApiOverview/Backend/BackendModules/ModuleConfiguration/ToplevelModules.rst
  Documentation/ApiOverview/Backend/BackendModules/ModuleDataObject.rst
  Documentation/ApiOverview/Backend/BackendModules/ModuleInterface.rst
  Documentation/ApiOverview/Backend/BackendModules/ModuleProviderAPI.rst
  Documentation/ApiOverview/Backend/BackendModules/ModuleTypoScript.rst
  Documentation/ExtensionArchitecture/HowTo/BackendModule/CreateModule.rst
  Documentation/ExtensionArchitecture/HowTo/BackendModule/CreateModuleWithExtbase.rst
  Documentation/ExtensionArchitecture/HowTo/BackendModule/Index.rst
  Documentation/ExtensionArchitecture/HowTo/BackendModule/ModuleConfiguration.rst
Labels: backport 12.4

#4450 [TASK] Update deprecated container directive syntax
  Documentation/ExtensionArchitecture/Index.rst
  Documentation/ExtensionArchitecture/Tutorials/Index.rst
  Documentation/ExtensionArchitecture/Tutorials/Kickstart/Index.rst
Labels: backport 12.4

#4421 Add documentation for fileExtensionToMimeType
  Documentation/Configuration/Typo3ConfVars/SYS.rst
Labels: backport 11.5, backport 12.4

#4440 [TASK] Add a warning note about `_assets` not containing symlinks
  Documentation/ApiOverview/DirectoryStructure/Index.rst
Labels: backport 12.4

#4458 call it plugin without Extbase
  Documentation/ApiOverview/FlexForms/Index.rst
Labels: backport 12.4

#4459 only 2 possibilities for frontend plugins
  Documentation/ApiOverview/ContentElements/CreatePlugins.rst
Labels: backport 12.4

#4463 use a note box instead of quotation
  Documentation/ApiOverview/DependencyInjection/Index.rst
Labels: backport 12.4
