Repository TYPO3-Documentation/TYPO3CMS-Reference-CoreApi, pull requests merged in 2025-03, with the labels that each got.

#5397 [DOCS] Fix example of SwitchableControllerActionUpgradeWizard (#5396)
  Documentation/ExtensionArchitecture/HowTo/UpdateExtensions/UpdateWizards/_SwitchableControllerActionUpgradeWizard.php
Labels: backport 12.4, backport 13.4

#5399 [TASK] Update routing examples
  Documentation/ApiOverview/Routing/Examples.rst
  Documentation/ApiOverview/Routing/_Examples/_StaticDatabaseMapper.php
  Documentation/ApiOverview/Routing/_Examples/_blog_archive.yaml
  Documentation/ApiOverview/Routing/_Examples/_blog_author.yaml
  Documentation/ApiOverview/Routing/_Examples/_blog_category.yaml
  Documentation/ApiOverview/Routing/_Examples/_blog_feeds.yaml
  Documentation/ApiOverview/Routing/_Examples/_blog_posts.yaml
  Documentation/ApiOverview/Routing/_Examples/_blog_tags.yaml
  Documentation/ApiOverview/Routing/_Examples/_full.yaml
  Documentation/ApiOverview/Routing/_Examples/_glossary.yaml
  Documentation/ApiOverview/Routing/_Examples/_imports.yaml
  Documentation/ApiOverview/Routing/_Examples/_news.yaml
Labels: backport 13.4

#5405 [TASK] Update RTE chapters
  Documentation/ApiOverview/Rte/InTheBackend/Index.rst
  Documentation/ApiOverview/Rte/InTheBackend/Introduction.rst
  Documentation/ApiOverview/Rte/InTheBackend/_FlexForm.xml
  Documentation/ApiOverview/Rte/InTheBackend/_RichTextNodeResolver.php
  Documentation/ApiOverview/Rte/InTheBackend/_tca-rte.php
  Documentation/ApiOverview/Rte/InTheFrontend/Index.rst
  Documentation/ApiOverview/Rte/InTheFrontend/Introduction.rst
  Documentation/ApiOverview/Rte/Index.rst
  Documentation/ApiOverview/Rte/RenderingInTheFrontend/Index.rst
  Documentation/ApiOverview/Rte/RenderingInTheFrontend/_parsefunc.typoscript
  Documentation/ApiOverview/Rte/RteCkeditorSysext.rst
Labels: backport 13.4

#5408 [TASK] Remove leftover reference to EMU::getFileFieldTCAConfig()
  Documentation/CodeSnippets/Config/Tutorials/Tea.php
  Documentation/CodeSnippets/Tutorials/Tea/Configuration/TCA/TeaColumnImage.rst.txt
  Documentation/ExtensionArchitecture/Tutorials/Tea/Model.rst
  Documentation/ExtensionArchitecture/Tutorials/Tea/_Model/_image_tca.php
Labels: backport 12.4, backport 13.4

#5410 [TASK] Remove ext_tables.sql from tea model example
  Documentation/CodeSnippets/Tutorials/Tea/ExtTablesSql.rst.txt
  Documentation/ExtensionArchitecture/Tutorials/Tea/Model.rst
Labels: backport 13.4

#5401 [TASK] Update page based routing page
  Documentation/ApiOverview/Routing/PageBasedRouting.rst
Labels: backport 13.4

#5402 [TASK] Update page type chapter
  Documentation/ApiOverview/PageTypes/Index.rst
  Documentation/ApiOverview/PageTypes/Introduction.rst
  Documentation/ApiOverview/PageTypes/RedirectHeaders.rst
  Documentation/Images/ManualScreenshots/PageTypes/Overview.png
Labels: backport 12.4, backport 13.4

#5411 [TASK] Update TeaController and Repository
  Documentation/CodeSnippets/Tutorials/Tea/Classes/Domain/Repository/InjectRepository.rst.txt
  Documentation/CodeSnippets/Tutorials/Tea/Classes/Domain/Repository/StoragePageAgnosticTrait.rst.txt
  Documentation/CodeSnippets/Tutorials/Tea/Classes/Domain/Repository/TeaRepository.rst.txt
  Documentation/CodeSnippets/Tutorials/Tea/Classes/Domain/Repository/UseRepository.rst.txt
  Documentation/ExtensionArchitecture/Tutorials/Tea/Controller.rst
  Documentation/ExtensionArchitecture/Tutorials/Tea/Repository.rst
  Documentation/ExtensionArchitecture/Tutorials/Tea/_Repository/_BasicRepository.php
  Documentation/ExtensionArchitecture/Tutorials/Tea/_Repository/_InjectRepository.php
  Documentation/ExtensionArchitecture/Tutorials/Tea/_Repository/_TeaRepository.php
Labels: backport 13.4

#5407 [TASK] Remove duplicate FlexForm example
  Documentation/ExtensionArchitecture/HowTo/Configuration.rst
Labels: backport 13.4

#5375 [TASK] Create a frontend request in a console command
  Documentation/ApiOverview/CommandControllers/Tutorial.rst
  Documentation/ApiOverview/CommandControllers/_Tutorial/_InitializeRequest.php
  Documentation/ApiOverview/RequestLifeCycle/Typo3Request.rst
Labels: backport 12.4, backport 13.4

#5421 Remove doubled backslashes in FQCNs in links
  Documentation/ApiOverview/Events/Events/Frontend/FilterMenuItemsEvent.rst
Labels: backport 12.4, backport 13.4

#5429 Remove outdated hint for @Lazy annotation
  Documentation/ExtensionArchitecture/Extbase/Reference/_Annotations/_Lazy.php
Labels: backport 13.4

#5430 Remove outdated hint for `@Lazy`/`@Cascade` annotations
  Documentation/ExtensionArchitecture/Extbase/Reference/_Annotations/_Multiple.php
Labels: backport 13.4

#5435 [TASK] Improve static routes example
  Documentation/ApiOverview/SiteHandling/_static-routes-assets.yaml
  Documentation/ApiOverview/SiteHandling/_static-routes-static-text.yaml
  Documentation/ApiOverview/SiteHandling/_static-routes-uri.yaml
Labels: backport 13.4

#5436 [TASK] Improve syntax and titles in Extbase chapters
  Documentation/ExtensionArchitecture/Extbase/Examples/Index.rst
  Documentation/ExtensionArchitecture/Extbase/Index.rst
  Documentation/ExtensionArchitecture/Extbase/Introduction/Index.rst
  Documentation/ExtensionArchitecture/Extbase/Reference/Annotations.rst
  Documentation/ExtensionArchitecture/Extbase/Reference/Caching.rst
  Documentation/ExtensionArchitecture/Extbase/Reference/Controller/ActionController.rst
  Documentation/ExtensionArchitecture/Extbase/Reference/Controller/ErrorAction.rst
  Documentation/ExtensionArchitecture/Extbase/Reference/Controller/Index.rst
  Documentation/ExtensionArchitecture/Extbase/Reference/Controller/PropertyMapping.rst
  Documentation/ExtensionArchitecture/Extbase/Reference/Controller/TypeConverter.rst
  Documentation/ExtensionArchitecture/Extbase/Reference/Domain/Model.rst
  Documentation/ExtensionArchitecture/Extbase/Reference/Domain/Persistence.rst
  Documentation/ExtensionArchitecture/Extbase/Reference/Index.rst
  Documentation/ExtensionArchitecture/Extbase/Reference/Localization.rst
  Documentation/ExtensionArchitecture/Extbase/Reference/TypoScriptConfiguration.rst
  Documentation/ExtensionArchitecture/Extbase/Reference/UriArguments.rst
  Documentation/ExtensionArchitecture/Extbase/Reference/UriBuilder.rst
  Documentation/ExtensionArchitecture/Extbase/Reference/Validation.rst
  Documentation/ExtensionArchitecture/Extbase/Reference/View/Index.rst
  Documentation/ExtensionArchitecture/Extbase/Reference/_Localization/_locallang.xlf
Labels: backport 13.4

#5439 [TASK] Document ability to use distinct flashmessage queues
  Documentation/ApiOverview/FlashMessages/Extbase.rst
Labels: backport 12.4, backport 13.4

#5441 Update content of TYPO3 extbase start page
  Documentation/ExtensionArchitecture/Extbase/Index.rst
Labels: backport 12.4, backport 13.4

#5449 Correct heading of UriBuilder used in Fluid
  Documentation/ExtensionArchitecture/Extbase/Reference/UriBuilder.rst
Labels: backport 12.4

#5447 Update URL to Site Package Builder
  Documentation/ExtensionArchitecture/Tutorials/Kickstart/Index.rst
  Documentation/Introduction/Index.rst
Labels: backport 12.4, backport 13.4

#5456 fix a typo
  Documentation/ApiOverview/SystemRegistry/Index.rst
Labels: backport 12.4, backport 13.4

#5462 Add example for ModifyQueryBeforeFetchingObjectDataEvent
  Documentation/ApiOverview/Events/Events/Extbase/Persistence/ModifyQueryBeforeFetchingObjectDataEvent.rst
  Documentation/ApiOverview/Events/Events/Extbase/Persistence/_ModifyQueryBeforeFetchingObjectDataEvent/_DisableRespectStoragePage.php
Labels: backport 13.4

#5467 [TASK] Move Extbase Validation into one topic
  Documentation/ApiOverview/RequestLifeCycle/Typo3Request.rst
  Documentation/ExtensionArchitecture/Extbase/Reference/Index.rst
  Documentation/ExtensionArchitecture/Extbase/Reference/Validation/CustomValidator/Index.rst
  Documentation/ExtensionArchitecture/Extbase/Reference/Validation/CustomValidator/_MyCustomValidator.php
  Documentation/ExtensionArchitecture/Extbase/Reference/Validation/CustomValidator/_ObjectValidator.rst.txt
  Documentation/ExtensionArchitecture/Extbase/Reference/Validation/CustomValidator/_ObjectValidatorUsage.php
  Documentation/ExtensionArchitecture/Extbase/Reference/Validation/CustomValidator/_PropertyValidator.rst.txt
  Documentation/ExtensionArchitecture/Extbase/Reference/Validation/CustomValidator/_PropertyValidatorUsage.php
  Documentation/ExtensionArchitecture/Extbase/Reference/Validation/CustomValidator/_RequestValidator.php
  Documentation/ExtensionArchitecture/Extbase/Reference/Validation/Index.rst
  Documentation/ExtensionArchitecture/Extbase/Reference/Validation/_Validation/_ValidatorWithArgumentUsage.php
Labels: backport 13.4
