Repository TYPO3-Documentation/TYPO3CMS-Reference-CoreApi, pull requests merged in 2025-08, with the labels that each got.

#5940 Update InstallationWizard.rst
  Documentation/Administration/Installation/ClassicMode/InstallationWizard.rst
Labels: backport 12.4, backport 13.4

#5946 [TASK] Add Anchor
  Documentation/ApiOverview/Seo/PageTitleApi.rst
Labels: backport 12.4, backport 13.4

#5945 [TASK] Add Anchor
  Documentation/ApiOverview/DependencyInjection/Index.rst
Labels: backport 12.4, backport 13.4

#5937 Clarification of FTP protocol in footnote
  Documentation/Administration/Installation/ClassicMode/Index.rst
Labels: backport 12.4, backport 13.4

#5932 Update TypeConverter.rst
  Documentation/ExtensionArchitecture/Extbase/Reference/Controller/TypeConverter.rst
Labels: backport 13.4

#5941 Update Index.rst
  Documentation/Administration/Installation/SystemRequirements/Index.rst
Labels: backport 12.4, backport 13.4

#5966 [FEATURE] Allow install tool sessions without shared file system
  Documentation/Configuration/Typo3ConfVars/BE.rst
Labels: main only

#5968 [TASK] Update codesnippets
  Documentation/CodeSnippets/Events/Backend/ModifyClearCacheActionsEvent.rst.txt
  Documentation/CodeSnippets/Manual/Country/CountryProvider.rst.txt
Labels: main only

#5969 [TASK] Overhaul FlexForm chapters
  Documentation/ApiOverview/ContentElements/AddingYourOwnContentElements.rst
  Documentation/ApiOverview/FlexForms/Definition/Index.rst
  Documentation/ApiOverview/FlexForms/Index.rst
  Documentation/ApiOverview/FlexForms/Modify/Index.rst
  Documentation/ApiOverview/FlexForms/Modify/_FlexformModificationService.php
  Documentation/ApiOverview/FlexForms/Reading/Index.rst
  Documentation/ApiOverview/FlexForms/Reading/_codesnippets/_NonExtbaseController.php
  Documentation/ApiOverview/FlexForms/Reading/_codesnippets/_dataproccessor.typoscript
  Documentation/ApiOverview/FlexForms/Reading/_codesnippets/_flexformContent.typoscript
  Documentation/ApiOverview/FlexForms/Reading/_codesnippets/_fluidtemplate.typoscript
  Documentation/ApiOverview/FlexForms/T3datastructure/Elements/Index.rst
  Documentation/ApiOverview/FlexForms/T3datastructure/Index.rst
  Documentation/ApiOverview/FlexForms/T3datastructure/Parsing/Index.rst
  Documentation/ApiOverview/FlexForms/T3datastructure/SheetReferences/Index.rst
  Documentation/ApiOverview/FlexForms/T3datastructure/SheetReferences/_DefaultSheet.xml
  Documentation/ApiOverview/FlexForms/T3datastructure/SheetReferences/_Main.xml
  Documentation/ApiOverview/FlexForms/_codesnippets/_ExtbaseFlexForm.xml
  Documentation/ApiOverview/FlexForms/_codesnippets/_extbase_plugin.php
  Documentation/ApiOverview/FlexForms/_codesnippets/_plain_plugin.php
  Documentation/Images/AutomaticScreenshots/FlexForms/FlexFormCarousel.png
  Documentation/Images/AutomaticScreenshots/FlexForms/FlexFormCarousel.rst.txt
Labels: backport 13.4

#5974 Remove parameter from method call
  Documentation/ApiOverview/RequestLifeCycle/_CodeSnippets/_ViewHelper.php
Labels: backport 13.4

#5971 [TASK] Remove deprecation information for list-type
  Documentation/ApiOverview/ContentElements/Index.rst
  Documentation/ApiOverview/ContentElements/MigrationListType.rst
  Documentation/ApiOverview/ContentElements/_Migration/PluginListTypeToCTypeUpdate.php
  Documentation/ApiOverview/ContentElements/_Migration/_ext_localconf.php.diff
  Documentation/ApiOverview/ContentElements/_Migration/_non_extbase_tca.diff
  Documentation/ApiOverview/ContentElements/_Migration/_tca_registration.php.diff
  Documentation/ApiOverview/ContentElements/_Migration/_typoscript.diff
  Documentation/ExtensionArchitecture/BestPractises/NamingConventions.rst
  Documentation/ExtensionArchitecture/Extbase/Reference/FrontendPlugins.rst
  Documentation/ExtensionArchitecture/HowTo/FrontendPlugin/Index.rst
Labels: main only

#5983 [TASK] Add usermapping for linux
  Makefile
Labels: backport 12.4, backport 13.4
