Repository TYPO3-Documentation/TYPO3CMS-Reference-CoreApi, pull requests merged in 2025-05, with the labels that each got.

#5570 [TASK] Condense settings start page
  Documentation/Configuration/Index.rst
Labels: backport 13.4

#5569 [TASK] Merge and condense config overview chapters
  Documentation/Configuration/ConfigurationFiles.rst
  Documentation/Configuration/ConfigurationOverview.rst
  Documentation/Configuration/Index.rst
  Documentation/Configuration/Typo3ConfVars/Index.rst
  Documentation/Configuration/Typo3ConfVars/_codesnippets/_DefaultConfiguration.php
  Documentation/Configuration/Typo3ConfVars/_codesnippets/_additional.php
  Documentation/Configuration/Typo3ConfVars/_codesnippets/_settings.php
Labels: backport 12.4, backport 13.4

#5572 Update SYS.rst
  Documentation/Configuration/Typo3ConfVars/SYS.rst
Labels: backport 12.4, backport 13.4

#5577 site sets small changes
  Documentation/ApiOverview/SiteHandling/SiteSets.rst
Labels: backport 13.4

#5579 [TASK] Update database tables section
  Documentation/ApiOverview/Database/DatabaseStructure/Index.rst
Labels: backport 13.4

#5580 [TASK] Update database upgrade section
  Documentation/Administration/Upgrade/Major/PostupgradeTasks/DatabaseAnalyser.rst.txt
  Documentation/Administration/Upgrade/Minor/Index.rst
  Documentation/ApiOverview/Database/DatabaseUpgrade/Index.rst
  Documentation/ExtensionArchitecture/FileStructure/ExtTables.rst
  Documentation/Images/AutomaticScreenshots/AdminTools/AnalyzeDatabase.png
  Documentation/Images/AutomaticScreenshots/AdminTools/AnalyzeDatabase.rst.txt
  Documentation/Images/AutomaticScreenshots/AdminTools/DatabaseUpgradeWizard.png
  Documentation/Images/AutomaticScreenshots/AdminTools/DatabaseUpgradeWizard.rst.txt
  Documentation/Images/ManualScreenshots/AdminTools/AnalyzeDatabase.png
Labels: backport 13.4

#5584 Fix inlineLocalizeSynchronize code example
  Documentation/ApiOverview/DataHandler/Database/Index.rst
Labels: backport 13.4

#5582 [TASK] Mention Extbase Queries in Database section
  Documentation/ApiOverview/Database/Extbase/Index.rst
  Documentation/ApiOverview/Database/Index.rst
Labels: backport 13.4

#5595 Fix typo in Model.rst
  Documentation/ExtensionArchitecture/Tutorials/Tea/Model.rst
Labels: backport-required

#5594 Fix Typo in ModuleConfiguration.rst
  Documentation/ExtensionArchitecture/HowTo/BackendModule/ModuleConfiguration.rst
Labels: backport-required

#5593 [TASK] Move Deployment and Tuning out of Installation into Administra…
  Documentation/Administration/Deployment/Environment/Index.rst
  Documentation/Administration/Deployment/Environment/_codesnippets/_additional-context.php
  Documentation/Administration/Deployment/Environment/_codesnippets/_additional-native.php
  Documentation/Administration/Deployment/Environment/_codesnippets/_additional.php
  Documentation/Administration/Deployment/Environment/_codesnippets/_dotenv-symfony.php
  Documentation/Administration/Deployment/Environment/_codesnippets/_dotenv-vlucas.php
  Documentation/Administration/Deployment/Environment/_codesnippets/_environment.php
  Documentation/Administration/Deployment/Environment/_codesnippets/_example.env
  Documentation/Administration/Deployment/Index.rst
  Documentation/Administration/Deployment/Tools/Deployer/Index.rst
  Documentation/Administration/Deployment/Tools/Deployer/_gitlab-deploy.yaml
  Documentation/Administration/Deployment/Tools/Index.rst
  Documentation/Administration/Deployment/Tools/Magallanes/Index.rst
  Documentation/Administration/Deployment/Tools/Magallanes/_mage.yml
  Documentation/Administration/Deployment/Tools/Rsync/Index.rst
  Documentation/Administration/Deployment/Tools/Surf/Index.rst
  Documentation/Administration/Deployment/Tools/Surf/_MyDeployment.php
  Documentation/Administration/ExtensionManagement/ClassicMode/Index.rst
  Documentation/Administration/ExtensionManagement/Index.rst
  Documentation/Administration/Index.rst
  Documentation/Administration/Installation/ClassicMode/Index.rst
  Documentation/Administration/Installation/ClassicMode/ReleaseIntegrity.rst
  Documentation/Administration/Installation/ComposerMode/Index.rst
  Documentation/Administration/Installation/Index.rst
  Documentation/Administration/SystemSettings/ProductionSettings/Index.rst
  Documentation/Administration/Tuning/Index.rst
Labels: backport 12.4, backport 13.4

#5598 `NEW` must not be followed by an underscore
  Documentation/ApiOverview/DataHandler/Database/Index.rst
Labels: backport 12.4, backport 13.4

#5601 [TASK] CI/CD in deployment for TYPO3 projects
  Documentation/Administration/Deployment/Automated/Index.rst
  Documentation/Administration/Deployment/Index.rst
Labels: backport 12.4, backport 13.4

#5604 [TASK] How to access the request, cobject and DB in a ViewHelper
  Documentation/ApiOverview/Fluid/DevelopCustomViewhelper.rst
Labels: backport 13.4

#5612 [TASK] Update and improve Classic mode installation chapters
  Documentation/Administration/Installation/ClassicMode/Index.rst
  Documentation/Administration/Installation/ClassicMode/InstallationWizard.rst
  Documentation/Administration/Installation/ClassicMode/ReleaseIntegrity.rst
  Documentation/Administration/Installation/ClassicMode/TarballZip.rst
  Documentation/Administration/Installation/ClassicMode/WgetSymlink.rst
  Documentation/Administration/Installation/ClassicMode/Windows.rst
Labels: backport 13.4

#5615 adjust note that TSFE->no_cache is not available on v13.4
  Documentation/ApiOverview/RequestLifeCycle/RequestAttributes/FrontendCacheInstruction.rst
Labels: backport 13.4

#5614 [TASK] Deployment running Git pull and Composer
  Documentation/Administration/Deployment/Tools/GitComposer/Index.rst
  Documentation/Administration/Deployment/Tools/Index.rst
Labels: backport 12.4, backport 13.4

#5628 [TASK] Update Restrict access Security Guidelines
  Documentation/Security/GuidelinesAdministrators/RestrictAccessToFiles.rst
  Documentation/Security/GuidelinesAdministrators/_codesnippets/_nginx.config
Labels: backport 12.4, backport 13.4

#5631 [TASK] Update File integrity Security Guidelines
  Documentation/Security/GuidelinesAdministrators/IntegrityOfTypo3Packages.rst
  Documentation/Security/GuidelinesAdministrators/OtherServices.rst
Labels: backport 12.4, backport 13.4

#5640 [TASK] Update main security chapter titles, navigation, and introductions
  Documentation/Security/GeneralGuidelines/Index.rst
  Documentation/Security/GuidelinesEditors/Index.rst
  Documentation/Security/GuidelinesExtensionDevelopment/Index.rst
  Documentation/Security/GuidelinesIntegrators/Index.rst
  Documentation/Security/HackedSite/Index.rst
  Documentation/Security/Index.rst
  Documentation/Security/Introduction/Index.rst
  Documentation/Security/SecurityTeam/Index.rst
  Documentation/Security/TypesOfThreats/Index.rst
  Documentation/Security/Versions/Index.rst
Labels: backport 12.4, backport 13.4

#5643 Fix display errors
  Documentation/ApiOverview/Fal/Architecture/Events.rst
Labels: backport 12.4, backport 13.4

#5645 [BUGFIX] Align Extbase DateTime handling to FormEngine and DataHandler
  Documentation/ExtensionArchitecture/Extbase/Reference/Domain/Model/PropertyTypes/Index.rst
Labels: backport 13.4

#5639 [TASK] Move Backup into Administration chapter
  Documentation/Administration/Backups/Index.rst
  Documentation/Administration/Index.rst
  Documentation/Security/Backups/Index.rst
  Documentation/Security/GuidelinesAdministrators/Backups.rst
  Documentation/Security/GuidelinesAdministrators/Index.rst
  Documentation/Security/Index.rst
Labels: backport 12.4, backport 13.4

#5616 [TASK] Running TYPO3 classic mode demo using Docker
  Documentation/Administration/Docker/DockerComposeDemo/Index.rst
  Documentation/Administration/Docker/DockerComposeDemo/_codesnippets/_docker-compose.yaml
  Documentation/Administration/Docker/DockerDemo/Index.rst
  Documentation/Administration/Docker/DockerDemo/_codesnippets/_DockerDbDemo.sh
  Documentation/Administration/Docker/DockerDemo/_codesnippets/_DockerDirDemo.sh
  Documentation/Administration/Docker/DockerDemo/_codesnippets/_DockerResetDemo.sh
  Documentation/Administration/Docker/DockerDemo/_codesnippets/_DockerRunTypo3Demo.sh
  Documentation/Administration/Docker/Index.rst
  Documentation/Administration/Docker/Production/Index.rst
  Documentation/Administration/Index.rst
  Documentation/Administration/Installation/ClassicMode/Index.rst
Labels: backport 12.4, backport 13.4

#5622 [TASK] Multi-stage environment workflows
  Documentation/Administration/Deployment/EnvironmentStages/Configuration/Index.rst
  Documentation/Administration/Deployment/EnvironmentStages/Configuration/_codesnippets/_additional-context.php
  Documentation/Administration/Deployment/EnvironmentStages/Configuration/_codesnippets/_additional-native.php
  Documentation/Administration/Deployment/EnvironmentStages/Configuration/_codesnippets/_additional.php
  Documentation/Administration/Deployment/EnvironmentStages/Configuration/_codesnippets/_dotenv-symfony.php
  Documentation/Administration/Deployment/EnvironmentStages/Configuration/_codesnippets/_dotenv-vlucas.php
  Documentation/Administration/Deployment/EnvironmentStages/Configuration/_codesnippets/_environment.php
  Documentation/Administration/Deployment/EnvironmentStages/Configuration/_codesnippets/_example.env
  Documentation/Administration/Deployment/EnvironmentStages/Database/Index.rst
  Documentation/Administration/Deployment/EnvironmentStages/Index.rst
  Documentation/Administration/Deployment/EnvironmentStages/UserUpload/Index.rst
  Documentation/Administration/Deployment/EnvironmentStages/UserUpload/_codesnippets/_filefill.php
  Documentation/Administration/Deployment/Index.rst
Labels: backport 12.4, backport 13.4

#5653 [TASK] Extension installation with composer
  Documentation/Administration/ExtensionManagement/Composer/Index.rst
  Documentation/Administration/ExtensionManagement/Composer/_codesnippets/_repositories.json
  Documentation/Administration/ExtensionManagement/Composer/_codesnippets/_setupscripts.json
  Documentation/Administration/ExtensionManagement/Index.rst
  Documentation/Administration/Upgrade/UpgradingExtensions/Index.rst
Labels: backport 12.4, backport 13.4

#5651 [TASK] Add page stub about security to Administration
  Documentation/Administration/Index.rst
  Documentation/Administration/Security/Index.rst
  Documentation/Administration/SystemSettings/Index.rst
Labels: backport 12.4, backport 13.4

#5667 Update MigrationListType.rst
  Documentation/ApiOverview/ContentElements/MigrationListType.rst
Labels: backport 13.4

#5637 [TASK] Update Directory Indexing chapter
  Documentation/Images/ManualScreenshots/Security/DirectoryIndexing.png
  Documentation/Security/GuidelinesAdministrators/DirectoryIndexing.rst
Labels: backport 12.4, backport 13.4

#5634 [TASK] Update more admin Security Guidelines
  Documentation/Security/GuidelinesAdministrators/ContentSecurityPolicy.rst
  Documentation/Security/GuidelinesAdministrators/FileExtensionHandling.rst
  Documentation/Security/GuidelinesAdministrators/FurtherActions.rst
  Documentation/Security/GuidelinesAdministrators/_codesnippets/_additional.php
  Documentation/Security/GuidelinesAdministrators/_codesnippets/_sameorigin.htaccess
Labels: backport 12.4, backport 13.4
