Repository TYPO3-Documentation/TYPO3CMS-Reference-CoreApi, pull requests merged in 2025-09, with the labels that each got.

#5988 Update VersionControl.rst
  Documentation/Administration/Upgrade/MigrateToComposer/VersionControl.rst
Labels: backport 12.4, backport 13.4

#5933 Update ModifyClearCacheActionsEvent.rst
  Documentation/ApiOverview/Events/Events/Backend/ModifyClearCacheActionsEvent.rst
Labels: backport 12.4, backport 13.4

#5991 some spelling modification
  Documentation/ExtensionArchitecture/Extbase/Reference/Domain/Model.rst
Labels: backport 12.4, backport 13.4

#6002 [TASK] Make a list of page title providers
  Documentation/ApiOverview/Seo/PageTitleApi.rst
Labels: backport 13.4

#6009 [TASK] Separate Caching backend and frontend pages
  Documentation/ApiOverview/CachingFramework/Frontends/Index.rst
  Documentation/ApiOverview/CachingFramework/FrontendsBackends/Index.rst
  Documentation/ApiOverview/CachingFramework/Index.rst
Labels: backport 12.4, backport 13.4

#6015 [TASK] Improve caching frontend page
  Documentation/ApiOverview/CachingFramework/Frontends/Index.rst
  Documentation/CodeSnippets/Config/Api/Cache.php
  Documentation/CodeSnippets/Manual/Cache/FrontendInterface.rst.txt
Labels: backport 13.4

#6006 [!!!][FEATURE] Add PSR-14 Events to manipulate form before created or…
  Documentation/ApiOverview/Events/Events/Form/BeforeFormIsCreatedEvent.rst
  Documentation/ApiOverview/Events/Events/Form/BeforeFormIsSavedEvent.rst
  Documentation/ApiOverview/Events/Events/Form/_BeforeFormIsCreatedEvent/_MyEventListener.php
  Documentation/ApiOverview/Events/Events/Form/_BeforeFormIsSavedEvent/_MyEventListener.php
  Documentation/CodeSnippets/Config/Api/Events/EventsForm.php
  Documentation/CodeSnippets/Events/Form/BeforeFormIsCreatedEvent.rst.txt
  Documentation/CodeSnippets/Events/Form/BeforeFormIsSavedEvent.rst.txt
Labels: main only

#6025 [TASK] Document "optionalDependencies" for Site Sets
  Documentation/ApiOverview/SiteHandling/SiteSets.rst
  Documentation/ApiOverview/SiteHandling/_Sets/_config_optional.rst.txt
Labels: backport 13.4

#6023 Raise severity of TER ext_emconf.php limitations
  Documentation/ExtensionArchitecture/FileStructure/ExtEmconf.rst
Labels: backport 12.4, backport 13.4

#6020 [BUGFIX] Update _crowdin.yaml
  Documentation/ApiOverview/Localization/TranslationServer/Crowdin/_codesnippets/_crowdin.yaml
Labels: backport 12.4, backport 13.4

#6021 [TASK] Add info about necessary scopes
  Documentation/ApiOverview/Localization/TranslationServer/Crowdin/ExtensionIntegration.rst
Labels: backport 12.4, backport 13.4

#6038 [BUGFIX] Correct link to Redis eviction policies and configuration docs
  Documentation/ApiOverview/CachingFramework/Backends/Index.rst
Labels: backport 12.4, backport 13.4

#6049 [FEATURE] Introduce scheduler task wizard
  Documentation/ApiOverview/Events/Events/Scheduler/Index.rst
  Documentation/ApiOverview/Events/Events/Scheduler/ModifyNewSchedulerTaskWizardItemsEvent.rst
  Documentation/ApiOverview/Events/Events/Scheduler/_ModifyNewSchedulerTaskWizardItemsEvent/_MyEventListener.php
  Documentation/CodeSnippets/Config/Api/Events/All.php
  Documentation/CodeSnippets/Config/Api/Events/EventsScheduler.php
  Documentation/CodeSnippets/Events/Scheduler/ModifyNewSchedulerTaskWizardItemsEvent.rst.txt
Labels: main only

#6047 [!!!][FEATURE] Use symfony/translation for translatable labels
  Documentation/Administration/Upgrade/Major/Index.rst
  Documentation/Administration/Upgrade/Major/Version14.rst
  Documentation/ApiOverview/Events/Events/Core/Country/BeforeCountriesEvaluatedEvent.rst
  Documentation/ApiOverview/Events/Events/Core/Country/_BeforeCountriesEvaluatedEvent/_ext_localconf.php
  Documentation/ApiOverview/Localization/LocalizationApi/TranslationLoaders.rst
  Documentation/ApiOverview/Localization/LocalizationApi/_codesnippets/_JsonFileLoader.php
  Documentation/ApiOverview/Localization/ManagingTranslations.rst
  Documentation/ApiOverview/Localization/XliffFormat.rst
  Documentation/ApiOverview/Localization/_ext_localconf.php
  Documentation/Configuration/Typo3ConfVars/LANG.rst
  Documentation/Configuration/Typo3ConfVars/SYS.rst
  Documentation/Configuration/Typo3ConfVars/_codesnippets/_settings.php
  Documentation/PhpArchitecture/NamedArguments.rst
Labels: main only

#6051 ci: upgrade actions/checkout to version 5
  .github/workflows/apply-precommit.yml
  .github/workflows/test-documentation.yml
  .github/workflows/tests.yml
Labels: backport 12.4, backport 13.4
