Repository TYPO3-Documentation/TYPO3CMS-Reference-CoreApi, pull requests merged in 2025-07, with the labels that each got.

#5864 [TASK] Describe how to save data in the fe user session
  Documentation/ApiOverview/Authentication/Sessions/Index.rst
  Documentation/ApiOverview/Authentication/Sessions/SessionData.rst
  Documentation/ApiOverview/Authentication/Sessions/SessionStorage.rst
  Documentation/ApiOverview/Authentication/Sessions/UserSessionManagement.rst
  Documentation/ApiOverview/Authentication/Sessions/_codesnippets/_ShoppingCartController.php
Labels: backport 12.4, backport 13.4

#5866 feat: add missing [Before|After]SectionMarkupGeneratedEvent
  Documentation/ApiOverview/Events/Events/Backend/AfterSectionMarkupGeneratedEvent.rst
  Documentation/ApiOverview/Events/Events/Backend/BeforeSectionMarkupGeneratedEvent.rst
  Documentation/ApiOverview/Events/Events/Backend/_AfterSectionMarkupGeneratedEvent/_MyEventListener.php
  Documentation/ApiOverview/Events/Events/Backend/_BeforeSectionMarkupGeneratedEvent/_MyEventListener.php
  Documentation/CodeSnippets/Config/Api/Events/EventsBackend.php
  Documentation/CodeSnippets/Events/Backend/AfterSectionMarkupGeneratedEvent.rst.txt
  Documentation/CodeSnippets/Events/Backend/BeforeSectionMarkupGeneratedEvent.rst.txt
Labels: backport 13.4

#5881 [BUGFIX] Store and process site settings.yaml as a map
  Documentation/Administration/DirectoryStructure/SiteFolder.rst
  Documentation/ApiOverview/SiteHandling/SiteSets.rst
  Documentation/ApiOverview/SiteHandling/SiteSettings.rst
  Documentation/ApiOverview/SiteHandling/_Sets/_site-package/_settings-map.yaml
  Documentation/ApiOverview/SiteHandling/_site-settings.yaml
  Documentation/ExtensionArchitecture/FileStructure/Configuration/Sets/Index.rst
Labels: backport 13.4

#5891 Update Tutorial.rst
  Documentation/ApiOverview/CommandControllers/Tutorial.rst
Labels: backport 12.4, backport 13.4

#5897 [TASK] Command: Correct indentation and headlines
  Documentation/ApiOverview/CommandControllers/Index.rst
  Documentation/ApiOverview/CommandControllers/ListCommands.rst
  Documentation/ApiOverview/CommandControllers/Tutorial.rst
Labels: backport 12.4, backport 13.4

#5900 [DOCS] Update command introduction
  Documentation/ApiOverview/CommandControllers/CustomCommands.rst
  Documentation/ApiOverview/CommandControllers/Index.rst
  Documentation/ApiOverview/CommandControllers/ListCommands.rst
  Documentation/ApiOverview/CommandControllers/Tutorial.rst
Labels: backport 12.4, backport 13.4

#5893 [FEATURE] Introduce Sudo-Mode Events
  Documentation/ApiOverview/Authentication/BackendUsers/Index.rst
  Documentation/ApiOverview/Events/Events/Backend/SudoModeRequiredEvent.rst
  Documentation/ApiOverview/Events/Events/Backend/SudoModeVerifyEvent.rst
  Documentation/ApiOverview/Events/Events/Backend/_SudoModeRequiredEvent/_Services.yaml
  Documentation/ApiOverview/Events/Events/Backend/_SudoModeRequiredEvent/_SkipSudoModeDialog.php
  Documentation/ApiOverview/Events/Events/Backend/_SudoModeVerifyEvent/_StaticPasswordVerification.php
  Documentation/CodeSnippets/Config/Api/Events/EventsBackend.php
  Documentation/CodeSnippets/Events/Backend/SudoModeRequiredEvent.rst.txt
  Documentation/CodeSnippets/Events/Backend/SudoModeVerifyEvent.rst.txt
  Documentation/Images/ManualScreenshots/AdminTools/SudoMode.png
Labels: backport 12.4, backport 13.4

#5912 [DOCS] Mention command to create models and tables
  Documentation/ApiOverview/Database/DatabaseRecords/Index.rst
  Documentation/ExtensionArchitecture/Extbase/Reference/Domain/Model/Index.rst
Labels: backport 12.4, backport 13.4

#5892 [DOCS] Document mounting volumes in Docker
  Documentation/Administration/Docker/Production/Index.rst
  Documentation/Administration/Docker/Production/Volumes/Index.rst
Labels: backport 13.4

#5745 [!!!][TASK] Remove static function parameter in AuthenticationService
  Documentation/ApiOverview/Authentication/AuthenticationService/Index.rst
Labels: main only

#5921 [DOCS] Move information on frontend requests to requests chapter
  Documentation/ApiOverview/CommandControllers/Tutorial.rst
  Documentation/ApiOverview/RequestLifeCycle/FrontendRequest.rst
Labels: backport 12.4, backport 13.4

#5911 [DOCS] Improve Extbase controller overview
  Documentation/ExtensionArchitecture/Extbase/Reference/Controller/Index.rst
  Documentation/ExtensionArchitecture/Extbase/Reference/Domain/Repository/Index.rst
Labels: backport 12.4, backport 13.4

#5928 Fix reference to cookieDomain
  Documentation/Configuration/Typo3ConfVars/BE.rst
Labels: backport 12.4, backport 13.4
