Repository TYPO3-Documentation/TYPO3CMS-Reference-CoreApi, pull requests merged in 2025-02, with the labels that each got.

#5286 [TASK] Move directory structure to administration
  Documentation/Administration/DirectoryStructure/ClassicInstallations.rst
  Documentation/Administration/DirectoryStructure/Index.rst
  Documentation/Administration/Index.rst
Labels: backport 12.4, backport 13.4

#5290 [TASK] Remove outdated Routing video which is now private
  Documentation/ApiOverview/Routing/Introduction.rst
Labels: backport 12.4, backport 13.4

#5289 [TASK] Replace "tl;dr" with "In short"
  Documentation/ApiOverview/DependencyInjection/Index.rst
Labels: backport 12.4, backport 13.4

#5282 [TASK] List common class locations as files
  Documentation/ExtensionArchitecture/FileStructure/Classes/Index.rst
Labels: backport 12.4, backport 13.4

#5281 [TASK] List common extension files as files
  Documentation/ApiOverview/Autoloading/Background.rst
  Documentation/ApiOverview/Events/EventDispatcher/Index.rst
  Documentation/ExtensionArchitecture/BestPractises/NamingConventions.rst
  Documentation/ExtensionArchitecture/FileStructure/ComposerJson.rst
  Documentation/ExtensionArchitecture/FileStructure/ExtConfTemplate.rst
  Documentation/ExtensionArchitecture/FileStructure/ExtEmconf.rst
  Documentation/ExtensionArchitecture/FileStructure/ExtLocalconf.rst
  Documentation/ExtensionArchitecture/FileStructure/ExtTables.rst
  Documentation/ExtensionArchitecture/FileStructure/ExtTablesSql.rst
  Documentation/ExtensionArchitecture/FileStructure/ExtTablesStaticAdtSql.rst
  Documentation/ExtensionArchitecture/FileStructure/ExtTyposcriptConstantsTyposcript.rst
  Documentation/ExtensionArchitecture/FileStructure/ExtTyposcriptSetupTyposcript.rst
  Documentation/ExtensionArchitecture/FileStructure/Index.rst
  Documentation/ExtensionArchitecture/HowTo/BackendModule/Tutorials.rst
  Documentation/ExtensionArchitecture/HowTo/CreateNewExtension.rst
  Documentation/ExtensionArchitecture/Tutorials/Kickstart/Make/Index.rst
  Documentation/ExtensionArchitecture/Tutorials/Tea/DirectoryStructure.rst
  Documentation/ExtensionArchitecture/Tutorials/Tea/ExtensionConfiguration.rst
  Documentation/Security/GuidelinesAdministrators/RestrictAccessToFiles.rst
  Documentation/Testing/FunctionalTesting/Index.rst
  Documentation/Testing/Tutorial/Acceptance.rst
  Documentation/Testing/Tutorial/Enetcache.rst
Labels: backport-required, backport 13.4

#5284 [TASK] List files commonly stored in the Ressources folder as files
  Documentation/ExtensionArchitecture/FileStructure/Resources/Index.rst
  Documentation/ExtensionArchitecture/FileStructure/Resources/Private/Language.rst
  Documentation/ExtensionArchitecture/FileStructure/Resources/Public/Index.rst
Labels: backport 12.4, backport 13.4

#5305 Installing extension composer or legacy
  Documentation/ExtensionArchitecture/HowTo/CreateNewExtension.rst
Labels: backport 12.4, backport 13.4

#5304 [TASK] Document possible files in the site folder
  Documentation/Administration/DirectoryStructure/ClassicInstallations.rst
  Documentation/Administration/DirectoryStructure/Index.rst
  Documentation/Administration/DirectoryStructure/SiteFolder.rst
  Documentation/ApiOverview/SiteHandling/Basics.rst
Labels: backport-required, backport 13.4

#5285 [TASK] List common template locations as files
  Documentation/ExtensionArchitecture/FileStructure/Resources/Private/Index.rst
Labels: backport-required, backport 13.4

#5310 Clarify configuration of pageIdSelector
  Documentation/ApiOverview/LinkHandling/Configuration.rst
Labels: backport 13.4

#5312 [TASK] List common files in a site set
  Documentation/ApiOverview/SiteHandling/SiteSets.rst
  Documentation/ApiOverview/SiteHandling/SiteSettingDefinitions.rst
  Documentation/ApiOverview/SiteHandling/SiteSettings.rst
  Documentation/ExtensionArchitecture/FileStructure/Configuration/Sets/Index.rst
Labels: backport 13.4

#5315 add info who is encapsulating calls
  Documentation/ApiOverview/SessionStorageFramework/UserSessionManagement.rst
Labels: backport 13.4

#5317 [TASK] About readonly
  Documentation/ApiOverview/DependencyInjection/Index.rst
  Documentation/PhpArchitecture/Index.rst
  Documentation/PhpArchitecture/Readonly.rst
Labels: backport 13.4

#5322 [TASK] Delete Screenshots not in use anymore
  Documentation/Images/AutomaticScreenshots/AdminTools/AdminToolsUpgradeOverview.png
  Documentation/Images/AutomaticScreenshots/AdminTools/AdminToolsUpgradeOverview.rst.txt
  Documentation/Images/AutomaticScreenshots/Fal/ArchitectureFoldersProcessedFolder.png
  Documentation/Images/AutomaticScreenshots/Fal/ArchitectureFoldersProcessedFolder.rst.txt
  Documentation/Images/AutomaticScreenshots/QuickInstall/EnableFirstInstall.png
  Documentation/Images/AutomaticScreenshots/QuickInstall/EnableFirstInstall.rst.txt
  Documentation/Images/AutomaticScreenshots/Upgrade/UpgradeWizardExecute.png
  Documentation/Images/AutomaticScreenshots/Upgrade/UpgradeWizardExecute.rst.txt
  Documentation/Images/ManualScreenshots/AccessControl/AccessUserAndGroupHomeDirectories.png
  Documentation/Images/ManualScreenshots/Backend/content_element_on_page.png
Labels: backport 13.4

#5324 [DOCS] Fix confvals syntax structure in BE.rst
  Documentation/Configuration/Typo3ConfVars/BE.rst
Labels: backport 12.4, backport 13.4

#5320 [TASK] Harden TCA file regex
  Documentation/ExtensionArchitecture/FileStructure/Configuration/TCA/Index.rst
Labels: backport 13.4

#5331 misspelling refered
  Documentation/ApiOverview/Routing/Introduction.rst
Labels: backport 12.4, backport 13.4

#5335 fix: correct spelling of Extbase
  Documentation/ApiOverview/DatabaseRecords/Index.rst
Labels: backport 13.4

#5334 [TASK] Allow site-specific Content-Security-Policy endpoints
  Documentation/ApiOverview/ContentSecurityPolicy/Index.rst
  Documentation/ApiOverview/ContentSecurityPolicy/_csp_reporting_custom.yaml
  Documentation/ApiOverview/ContentSecurityPolicy/_csp_reporting_false.yaml
  Documentation/Configuration/Typo3ConfVars/BE.rst
  Documentation/Configuration/Typo3ConfVars/FE.rst
Labels: backport 12.4, backport 13.4

#5330 [TASK] Unify backend labels for file mounts
  Documentation/ApiOverview/Backend/AccessControl/AccessControlOptions/Index.rst
  Documentation/ApiOverview/Backend/AccessControl/MoreAboutFileMounts/Index.rst
  Documentation/ApiOverview/Backend/ContextualMenu.rst
Labels: backport 13.4

#5342 Update fieldControl example in _pages.php
  Documentation/ApiOverview/FormEngine/Rendering/Index.rst
  Documentation/ApiOverview/FormEngine/Rendering/_pages.php
Labels: backport 12.4, backport 13.4

#5346 [BUGFIX] Default lifetime for cache tags
  Documentation/ApiOverview/RequestLifeCycle/RequestAttributes/FrontendCacheCollector.rst
Labels: backport 13.4

#5341 Update create page type documentation #5050
  Documentation/ApiOverview/PageTypes/CreateNewPageType.rst
  Documentation/ApiOverview/PageTypes/_pages.php
  Documentation/ApiOverview/PageTypes/_pagesCopyDefaultPageType.php
Labels: backport 12.4, backport 13.4

#5340 Clean Up indents in doc Directory Structure
  Documentation/Administration/DirectoryStructure/Index.rst
Labels: backport 13.4

#5349 [FEATURE] Add UNION Clause support to the QueryBuilder
  Documentation/ApiOverview/Database/QueryBuilder/Index.rst
  Documentation/ApiOverview/Database/QueryBuilder/_UnionExample.php
Labels: backport 13.4

#5355 Add hint to dynamically load language from backend user in cli
  Documentation/ApiOverview/Backend/BackendUserObject.rst
Labels: backport 13.4

#5354 [TASK] Remove outdated TYPO3 11.x version hints
  Documentation/ApiOverview/Backend/AccessControl/MoreAboutFileMounts/Index.rst
  Documentation/ApiOverview/Database/ExpressionBuilder/Index.rst
  Documentation/ApiOverview/Events/Events/Backend/ModifyClearCacheActionsEvent.rst
  Documentation/ApiOverview/Events/Events/Core/Cache/CacheFlushEvent.rst
  Documentation/ApiOverview/Events/Events/Core/Cache/CacheWarmupEvent.rst
  Documentation/ApiOverview/Events/Events/Core/Core/BootCompletedEvent.rst
  Documentation/ApiOverview/Events/Events/Core/Package/AfterPackageActivationEvent.rst
  Documentation/ApiOverview/Events/Events/Core/Package/AfterPackageDeactivationEvent.rst
  Documentation/ApiOverview/Events/Events/Core/Package/PackagesMayHaveChangedEvent.rst
  Documentation/ApiOverview/Events/Events/Core/Resource/AfterFileCommandProcessedEvent.rst
  Documentation/ApiOverview/Events/Events/Core/Resource/ModifyFileDumpEvent.rst
  Documentation/ApiOverview/Events/Events/ExtensionManager/AvailableActionsForExtensionEvent.rst
  Documentation/ApiOverview/Events/Events/Filelist/ProcessFileListActionsEvent.rst
  Documentation/ApiOverview/Events/Events/Frontend/ModifyResolvedFrontendGroupsEvent.rst
  Documentation/ApiOverview/Events/Events/FrontendLogin/BeforeRedirectEvent.rst
  Documentation/ApiOverview/Fal/Architecture/Events.rst
  Documentation/ApiOverview/Mail/Index.rst
  Documentation/ApiOverview/RequestLifeCycle/Typo3Request.rst
  Documentation/ApiOverview/SiteHandling/AccessingSiteConfiguration.rst
  Documentation/Configuration/Typo3ConfVars/FE.rst
  Documentation/ExtensionArchitecture/BestPractises/ConfigurationFiles.rst
  Documentation/ExtensionArchitecture/FileStructure/ComposerJson.rst
  Documentation/ExtensionArchitecture/FileStructure/ExtEmconf.rst
Labels: backport 13.4

#5350 [FEATURE] Add castText() expression support to ExpressionBuilder
  Documentation/ApiOverview/Database/ExpressionBuilder/Index.rst
  Documentation/ApiOverview/Database/ExpressionBuilder/_RepositoryCastText.php
Labels: backport 13.4

#5363 Added available variables for CType backend preview via TSconfig
  Documentation/ApiOverview/ContentElements/CustomBackendPreview.rst
Labels: backport 12.4, backport 13.4

#5361 [TASK] Use confval to describe ext_emconf.php
  Documentation/ExtensionArchitecture/FileStructure/ExtEmconf.rst
  Documentation/ExtensionArchitecture/FileStructure/_ExtEmconf/_ext_emconf.php
  Documentation/ExtensionArchitecture/FileStructure/_ExtEmconf/_ext_emconf_autoload.php
  Documentation/ExtensionArchitecture/FileStructure/_ExtEmconf/_ext_emconf_autoload_psr_4.php
  Documentation/ExtensionArchitecture/FileStructure/_ExtEmconf/_ext_emconf_constraints.php
Labels: backport 12.4, backport 13.4

#5351 [TASK] Describe settings.php / additional.php as files
  Documentation/Configuration/ConfigurationFiles.rst
Labels: backport 12.4, backport 13.4

#5352 [TASK] Describe Flag files as files
  Documentation/Administration/SystemSettings/MaintenanceMode/Index.rst
  Documentation/Configuration/FlagFiles/Index.rst
  Documentation/Configuration/Typo3ConfVars/BE.rst
  Documentation/Security/GuidelinesIntegrators/InstallTool.rst
Labels: backport 12.4, backport 13.4

#5358 [TASK] Move chapters not fit for configuration
  Documentation/Administration/DirectoryStructure/FlagFiles.rst
  Documentation/ApiOverview/FeatureToggleApi/Index.rst
  Documentation/ApiOverview/Typo3Information/Index.rst
  Documentation/Configuration/Index.rst
Labels: backport 12.4, backport 13.4

#5369 [TASK] Move Backend Entry Point into Administration
  Documentation/Administration/SystemSettings/BackendEntryPoint/Index.rst
  Documentation/Configuration/Index.rst
Labels: backport 13.4

#5371 [TASK] Move Application context into Administration
  Documentation/Administration/SystemSettings/ApplicationContext/Index.rst
  Documentation/Administration/SystemSettings/ApplicationContext/_CodeSnippets/SunnyProducts.php
  Documentation/Administration/SystemSettings/Index.rst
  Documentation/Configuration/Index.rst
Labels: backport 13.4

#5368 Update and condense general information on settings/configuration
  Documentation/Configuration/ConfigurationOverview.rst
  Documentation/Configuration/Glossary.rst
  Documentation/Configuration/Index.rst
Labels: backport 13.4

#5362 [TASK] Change Authentification chapter into a general chapter
  Documentation/ApiOverview/Authentication/AuthenticationService/CSRFlikeRequestTokenHandling.rst
  Documentation/ApiOverview/Authentication/AuthenticationService/Index.rst
  Documentation/ApiOverview/Authentication/AuthenticationService/_CSRFlikeRequestTokenHandling/_MyController.php
  Documentation/ApiOverview/Authentication/AuthenticationService/_CSRFlikeRequestTokenHandling/_MyProcessController.php
  Documentation/ApiOverview/Authentication/BackendUsers/Index.rst
  Documentation/ApiOverview/Authentication/FrontendUsers/Index.rst
  Documentation/ApiOverview/Authentication/Index.rst
Labels: backport 13.4

#5376 [TASK] Move password policies into authentification
  Documentation/ApiOverview/Authentication/Index.rst
  Documentation/ApiOverview/Authentication/PasswordPolicies/Index.rst
  Documentation/ApiOverview/Authentication/PasswordPolicies/_PrivateKeyGeneratorCommand.php
Labels: backport 12.4, backport 13.4

#5378 See also: Granting System Maintainer rights
  Documentation/Administration/UserManagement/BackendPrivileges/Index.rst
Labels: backport 13.4

#5381 [TASK] Update Screenshots for Administrators
  Documentation/Administration/UserManagement/BackendPrivileges/Index.rst
  Documentation/Images/ManualScreenshots/UserManagement/Administrator.png
  Documentation/Images/ManualScreenshots/UserManagement/SystemMaintainer.png
  Documentation/Images/ManualScreenshots/UserManagement/admin-tools-open.png
  Documentation/Images/ManualScreenshots/UserManagement/admin-tools.png
  Documentation/Images/ManualScreenshots/UserManagement/system.png
  Documentation/Images/ManualScreenshots/UserManagement/system_open.png
Labels: backport 13.4

#5384 [BUGFIX] Fix link to installation chapter
  Documentation/Administration/Installation/Index.rst
Labels: backport 12.4, backport 13.4

#5374 [TASK] Move YAMl API chapters into API
  Documentation/ApiOverview/YamlApi/Index.rst
  Documentation/ApiOverview/YamlApi/Syntax.rst
  Documentation/ApiOverview/YamlApi/_ExamplePlaceholderProcessor.php
  Documentation/Configuration/Index.rst
  Documentation/Configuration/Yaml/Index.rst
  Documentation/Configuration/Yaml/ServicesYaml.rst
  Documentation/Configuration/Yaml/YamlSyntax.rst
  Documentation/ExtensionArchitecture/FileStructure/Configuration/ServicesYaml.rst
  Documentation/ExtensionArchitecture/FileStructure/Configuration/_snippets/_example_services.yaml
Labels: backport 13.4

#5389 [TASK] Move session handling into authentification
  Documentation/ApiOverview/Authentication/Index.rst
  Documentation/ApiOverview/Authentication/Sessions/Index.rst
  Documentation/ApiOverview/Authentication/Sessions/SessionStorage.rst
  Documentation/ApiOverview/Authentication/Sessions/UserSessionManagement.rst
  Documentation/ApiOverview/Authentication/Sessions/_SessionManager.rst.txt
  Documentation/ApiOverview/Authentication/Sessions/_UserSession.rst.txt
  Documentation/ApiOverview/Authentication/Sessions/_UserSessionManager.rst.txt
  Documentation/ExtensionArchitecture/FileStructure/Configuration/ServicesYaml.rst
Labels: backport 13.4

#5387 [TASK] Update Fluid theme section
  Documentation/ApiOverview/Fluid/Introduction.rst
  Documentation/ApiOverview/Fluid/_Introduction/_Content.html
  Documentation/ApiOverview/Fluid/_Introduction/_Default.html
  Documentation/ApiOverview/Fluid/_Introduction/_Jumbotron.html
  Documentation/ApiOverview/Fluid/_Introduction/_PageLayout.html
  Documentation/ApiOverview/Fluid/_Introduction/_Subpage.html
  Documentation/ApiOverview/Fluid/_Introduction/_ThreeColumn.html
  Documentation/ApiOverview/Fluid/_Introduction/_lib.dynamicContent.typoscript
  Documentation/ApiOverview/Fluid/_Introduction/_pageview.typoscript
Labels: backport 13.4

#5393 [DOCS] Use correct backend route name in extbase example
  Documentation/ApiOverview/Backend/BackendModules/ModuleConfiguration/Index.rst
Labels: backport 12.4, backport 13.4
